import { type LessonContent } from './lesson-content'

function lc(
  w: [string,string,string,string,string][],
  gt: string, ge: string,
  gx: {s:string,t:string,c:boolean}[],
  gm: {w:string,cr:string,e:string}[],
  dl: [string,'A'|'B',string,string][],
  pi: [string,string,string,string][]
): LessonContent {
  return {
    vocab: w.map(([en,fr,ph,ex,et])=>({english:en,french:fr,phonetic:ph,example:ex,exampleTranslation:et})),
    grammar:{title:gt,explanation:ge,examples:gx.map(e=>({sentence:e.s,translation:e.t,isCorrect:e.c})),commonMistakes:gm.map(m=>({wrong:m.w,correct:m.cr,explanation:m.e}))},
    conversation:dl.map(([sp,r,en,fr])=>({speaker:sp,role:r,text:en,translation:fr})),
    pronunciation:pi.map(([wd,ph,mn,tp])=>({word:wd,phonetic:ph,meaning:mn,tip:tp})),
  }
}

export const A1_LESSONS: Record<string, LessonContent> = {
// ═══ Unit 1: Greetings & Introductions ═══
'a1-l1': lc( // Hello & Goodbye (vocabulary)
  [['Hello','Bonjour','/həˈloʊ/','Hello, how are you?','Bonjour, comment allez-vous ?'],['Goodbye','Au revoir','/ɡʊdˈbaɪ/','Goodbye, see you tomorrow!','Au revoir, à demain !'],['Good morning','Bonjour (matin)','/ɡʊd ˈmɔːrnɪŋ/','Good morning, class!','Bonjour la classe !'],['Good night','Bonne nuit','/ɡʊd naɪt/','Good night, sleep well!','Bonne nuit, dors bien !']],
  'Present Simple: Be','Le verbe "be" (être) : I am, you are, he/she/it is, we are, they are. Contractions : I\'m, you\'re, he\'s, she\'s, it\'s, we\'re, they\'re.',
  [{s:'I am a student.',t:'Je suis étudiant.',c:true},{s:'She are from France.',t:'',c:false},{s:'They are my friends.',t:'Ce sont mes amis.',c:true},{s:'He is happy today.',t:'Il est content aujourd\'hui.',c:true}],
  [{w:'She are tired.',cr:'She is tired.',e:'On utilise "is" avec he/she/it.'},{w:'I am agree.',cr:'I agree.',e:'En anglais, on dit "I agree" sans le verbe be.'}],
  [['Léa','A','Hello! My name is Léa.','Bonjour ! Je m\'appelle Léa.'],['Tom','B','Hi Léa! I\'m Tom. Nice to meet you!','Salut Léa ! Je suis Tom. Enchanté !'],['Léa','A','Nice to meet you too! Where are you from?','Enchantée aussi ! D\'où viens-tu ?'],['Tom','B','I\'m from London. And you?','Je suis de Londres. Et toi ?'],['Léa','A','I\'m from Paris. I\'m a student.','Je suis de Paris. Je suis étudiante.'],['Tom','B','That\'s great! Goodbye, Léa!','Super ! Au revoir, Léa !']],
  [['Hello','/həˈloʊ/','Bonjour','Le "h" anglais est expiré, pas muet comme en français.'],['Goodbye','/ɡʊdˈbaɪ/','Au revoir','Prononcez "gued-baï" — le "oo" est court.'],['Morning','/ˈmɔːrnɪŋ/','Matin','Le "or" se prononce "or" long : "mor-ning".'],['Night','/naɪt/','Nuit','Le "igh" = "aï" : "naït". Le "t" est muet dans night.']]
),
'a1-l2': lc( // How Are You? (conversation)
  [['Fine','Bien','/faɪn/','I\'m fine, thank you.','Je vais bien, merci.'],['Tired','Fatigué','/taɪərd/','She is tired today.','Elle est fatiguée aujourd\'hui.'],['Happy','Heureux','/ˈhæpi/','I am very happy!','Je suis très heureux !'],['Busy','Occupé','/ˈbɪzi/','He is busy at work.','Il est occupé au travail.']],
  'Questions with How','Pour demander comment quelqu\'un va : "How are you?" (Comment allez-vous ?). Réponses : "I\'m fine" (Je vais bien), "I\'m tired" (Je suis fatigué), "Not bad" (Pas mal).',
  [{s:'How are you?',t:'Comment allez-vous ?',c:true},{s:'How is she?',t:'Comment va-t-elle ?',c:true},{s:'How old you are?',t:'',c:false},{s:'How are they?',t:'Comment vont-ils ?',c:true}],
  [{w:'How old you are?',cr:'How old are you?',e:'L\'auxiliaire précède le sujet dans les questions.'},{w:'How you are?',cr:'How are you?',e:'Inversion sujet/verbe obligatoire dans les questions.'}],
  [['Sarah','A','Hi! How are you today?','Salut ! Comment vas-tu aujourd\'hui ?'],['Marc','B','I\'m fine, thanks. And you?','Je vais bien, merci. Et toi ?'],['Sarah','A','I\'m a bit tired. I worked late yesterday.','Je suis un peu fatiguée. J\'ai travaillé tard hier.'],['Marc','B','Oh, that\'s too bad. Are you busy today?','Oh, c\'est dommage. Es-tu occupé aujourd\'hui ?'],['Sarah','A','No, I\'m not busy. I\'m happy it\'s Friday!','Non, je ne suis pas occupé. Je suis content que ce soit vendredi !'],['Marc','B','Me too! Have a good day!','Moi aussi ! Bonne journée !']],
  [['Fine','/faɪn/','Bien','Le "i" est long : "faïn". Ne dites pas "fin".'],['Tired','/taɪərd/','Fatigué','Prononcez "taï-erd" — le "i" est long.'],['Happy','/ˈhæpi/','Heureux','Le "a" est ouvert comme dans "chat" : "ha-pi".'],['Busy','/ˈbɪzi/','Occupé','Le "u" est court comme dans "lit" : "bi-zi".']]
),
'a1-l3': lc( // Introducing Yourself (conversation)
  [['Name','Nom','/neɪm/','My name is Pierre.','Je m\'appelle Pierre.'],['Age','Âge','/eɪdʒ/','What is your age?','Quel est votre âge ?'],['Country','Pays','/ˈkʌntri/','My country is France.','Mon pays est la France.'],['From','De','/frɒm/','I am from Paris.','Je suis de Paris.']],
  'Introducing Yourself — Key Phrases','Pour se présenter : "My name is..." (Je m\'appelle...), "I am from..." (Je suis de...), "I am ... years old" (J\'ai ... ans). "Nice to meet you" = Enchanté(e).',
  [{s:'My name is Sophie.',t:'Je m\'appelle Sophie.',c:true},{s:'I am from France.',t:'Je suis de France.',c:true},{s:'I have 25 years old.',t:'',c:false},{s:'Nice to meet you!',t:'Enchanté(e) !',c:true}],
  [{w:'I have 25 years old.',cr:'I am 25 years old.',e:'En anglais, on utilise "am" pas "have" pour l\'âge.'},{w:'I\'m come from France.',cr:'I come from France. / I am from France.',e:'On dit "I come from" ou "I am from", pas les deux ensemble.'}],
  [['Pierre','A','Hello! My name is Pierre. What is your name?','Bonjour ! Je m\'appelle Pierre. Comment tu t\'appelles ?'],['Amina','B','Hi Pierre! I\'m Amina. Nice to meet you!','Salut Pierre ! Je suis Amina. Enchantée !'],['Pierre','A','Where are you from, Amina?','D\'où viens-tu, Amina ?'],['Amina','B','I\'m from Morocco. And you?','Je suis du Maroc. Et toi ?'],['Pierre','A','I\'m from France. I am 30 years old. How old are you?','Je suis de France. J\'ai 30 ans. Quel âge as-tu ?'],['Amina','B','I am 25. It\'s nice to meet you too!','J\'ai 25 ans. Enchantée aussi !']],
  [['Name','/neɪm/','Nom','Le "a" est long : "nèïm".'],['Age','/eɪdʒ/','Âge','Prononcez "èïd-j" — le son "dj" comme dans "djinn".'],['Country','/ˈkʌntri/','Pays','Le "ou" est ouvert : "keun-tri".'],['From','/frɒm/','De','Le "o" est ouvert : "from" avec un "o" comme dans "bon".']]
),
'a1-l4': lc( // Present Simple: Be (grammar)
  [['Am','Suis','/æm/','I am a teacher.','Je suis professeur.'],['Is','Est','/ɪz/','She is my sister.','Elle est ma sœur.'],['Are','Êtes/Sommes/Sont','/ɑːr/','We are students.','Nous sommes étudiants.'],['Not','Non/Pas','/nɒt/','He is not here.','Il n\'est pas ici.']],
  'Present Simple: Be — Full Conjugation','Le verbe "be" : I am (je suis), you are (tu es/vous êtes), he/she/it is (il/elle est), we are (nous sommes), they are (ils/elles sont). Négatif : am not, is not (isn\'t), are not (aren\'t). Questions : Am I...? Are you...? Is he...?',
  [{s:'She is a doctor.',t:'Elle est médecin.',c:true},{s:'We are not tired.',t:'Nous ne sommes pas fatigués.',c:true},{s:'They is happy.',t:'',c:false},{s:'Is he your brother?',t:'Est-il ton frère ?',c:true}],
  [{w:'They is happy.',cr:'They are happy.',e:'"They" prend toujours "are", jamais "is".',},{w:'You is beautiful.',cr:'You are beautiful.',e:'"You" prend "are", pas "is".']],
  [['Teacher','A','Are you a new student?','Êtes-vous un nouvel étudiant ?'],['Student','B','Yes, I am. My name is Ali. Is this the right classroom?','Oui. Je m\'appelle Ali. C\'est la bonne salle ?'],['Teacher','A','Yes, it is. We are in Room 5. Is she your friend?','Oui. Nous sommes dans la salle 5. Est-elle ton amie ?'],['Student','B','No, she is not my friend. She is my sister.','Non, elle n\'est pas mon amie. Elle est ma sœur.'],['Teacher','A','Oh, I see! Is she a student too?','Oh, je vois ! Est-elle aussi étudiante ?'],['Student','B','Yes, she is. We are from the same city.','Oui. Nous sommes de la même ville.']],
  [['Am','/æm/','Suis','Le "a" est très ouvert, comme dans "chat".'],['Is','/ɪz/','Est','Le "s" est sonore : "izz".'],['Are','/ɑːr/','Êtes/Sont','Prononcez "ar" avec le "r" légèrement roulé.'],['Isn\'t','/ˈɪzənt/','N\'est pas','Prononcez "iz-ent" — le "t" final est léger.']]
),
'a1-l5': lc( // Greeting Sounds (pronunciation)
  [['Hi','Salut','/haɪ/','Hi! How are you?','Salut ! Comment vas-tu ?'],['Hey','Hé','/heɪ/','Hey! Over here!','Hé ! Par ici !'],['Welcome','Bienvenue','/ˈwelkəm/','Welcome to our school!','Bienvenue dans notre école !'],['See you','À plus','/siː juː/','See you later!','À plus tard !']],
  'Short Forms in Greetings','Dans les salutations informelles, on utilise des formes courtes : "Hi" au lieu de "Hello", "See you" au lieu de "I will see you", "Bye" au lieu de "Goodbye". "Morning" peut remplacer "Good morning".',
  [{s:'Hi! How are you?',t:'Salut ! Comment vas-tu ?',c:true},{s:'Morning! Nice day!',t:'Bonjour ! Belle journée !',c:true},{s:'See you on tomorrow.',t:'',c:false},{s:'Welcome to Paris!',t:'Bienvenue à Paris !',c:true}],
  [{w:'See you on tomorrow.',cr:'See you tomorrow.',e:'On ne met pas "on" avant "tomorrow".',},{w:'Welcome in Paris.',cr:'Welcome to Paris.',e:'Après "welcome", on utilise "to" pas "in".']],
  [['Host','A','Hi! Welcome to our home!','Salut ! Bienvenue chez nous !'],['Guest','B','Hey, thank you! Nice to see you!','Hé, merci ! Content de te voir !'],['Host','A','How are you? Is everything fine?','Comment vas-tu ? Tout va bien ?'],['Guest','B','I\'m great, thanks! See you brought snacks!','Super, merci ! Je vois que tu as apporté des snacks !'],['Host','A','Yes! Help yourself. Morning was busy but I cooked!','Oui ! Sers-toi. Le matin était chargé mais j\'ai cuisiné !'],['Guest','B','That\'s so kind! See you around, I\'ll grab a plate!','C\'est gentil ! À plus, je vais prendre une assiette !']],
  [['Hi','/haɪ/','Salut','Le "h" est expiré et le "i" est long : "haï".'],['Hey','/heɪ/','Hé','Prononcez "héï" — le "h" est expiré comme une petite expiration.'],['Welcome','/ˈwelkəm/','Bienvenue','Le "l" est sombre : "ouél-kem".'],['See you','/siː juː/','À plus','Le "ee" est long : "sii-iou". Lien fluide entre les mots.']]
),

// ═══ Unit 2: Numbers & Counting ═══
'a1-l6': lc( // Numbers 1-20 (vocabulary)
  [['One','Un','/wʌn/','I have one brother.','J\'ai un frère.'],['Five','Cinq','/faɪv/','There are five students.','Il y a cinq étudiants.'],['Twelve','Douze','/twelv/','It is twelve o\'clock.','Il est midi.'],['Twenty','Vingt','/ˈtwenti/','She is twenty years old.','Elle a vingt ans.']],
  'Singular & Plural with Numbers','Après un nombre supérieur à 1, le nom est toujours au pluriel : one book mais two books. Pluriel régulier : on ajoute -s. Pluriels irréguliers : man→men, woman→women, child→children.',
  [{s:'I have two books.',t:'J\'ai deux livres.',c:true},{s:'She has three child.',t:'',c:false},{s:'There are ten students.',t:'Il y a dix étudiants.',c:true},{s:'Five woman are here.',t:'',c:false}],
  [{w:'Three child',cr:'Three children',e:'Le pluriel de "child" est "children", pas "childs".',},{w:'Five woman',cr:'Five women',e:'Le pluriel de "woman" est "women" (prononcé "wimmen").']],
  [['Lucie','A','How many brothers do you have?','Combien de frères as-tu ?'],['Kevin','B','I have one brother and two sisters.','J\'ai un frère et deux sœurs.'],['Lucie','A','That\'s nice! How old are they?','C\'est sympa ! Quel âge ont-ils ?'],['Kevin','B','My brother is twelve and my sisters are five and eight.','Mon frère a douze ans et mes sœurs ont cinq et huit ans.'],['Lucie','A','I have three children. They are one, three, and seven.','J\'ai trois enfants. Ils ont un, trois et sept ans.'],['Kevin','B','Wow, that\'s a big family! Twenty people at Christmas?','Wow, grande famille ! Vingt personnes à Noël ?']],
  [['One','/wʌn/','Un','Prononcez "ouanne" — le "o" est ouvert.'],['Five','/faɪv/','Cinq','Le "i" est long : "faïv".'],['Twelve','/twelv/','Douze','Le "w" : arrondissez les lèvres. "Touelv".'],['Twenty','/ˈtwenti/','Vingt','Prononcez "toué-ni" — le "t" final est léger.']]
),
'a1-l7': lc( // Numbers 20-100 (vocabulary)
  [['Thirty','Trente','/ˈθɜːrti/','She is thirty years old.','Elle a trente ans.'],['Fifty','Cinquante','/ˈfɪfti/','The book costs fifty dollars.','Le livre coûte cinquante dollars.'],['Seventy','Soixante-dix','/ˈsevənti/','My grandfather is seventy.','Mon grand-père a soixante-dix ans.'],['Hundred','Cent','/ˈhʌndrəd/','There are a hundred pages.','Il y a cent pages.']],
  'Expressing Quantities','Pour exprimer des quantités : "about thirty" (environ trente), "over fifty" (plus de cinquante), "nearly a hundred" (presque cent). "A hundred" = cent, "hundreds of" = des centaines de.',
  [{s:'There are about thirty people.',t:'Il y a environ trente personnes.',c:true},{s:'It costs over fifty dollars.',t:'Ça coûte plus de cinquante dollars.',c:true},{s:'Hundred of people came.',t:'',c:false},{s:'A hundred students are here.',t:'Cent étudiants sont ici.',c:true}],
  [{w:'Hundred of people',cr:'Hundreds of people',e:'"Hundreds of" avec "s" pour dire des centaines. Sans "s" : "a hundred" = cent.'},{w:'Two hundreds',cr:'Two hundred',e:'Après un nombre, "hundred" ne prend pas de "s" : two hundred.']],
  [['Claire','A','How many people live in your city?','Combien de personnes vivent dans ta ville ?'],['Romain','B','About fifty thousand. And yours?','Environ cinquante mille. Et la tienne ?'],['Claire','A','Nearly a hundred thousand! It\'s big.','Presque cent mille ! C\'est grand.'],['Romain','B','My building has seventy apartments.','Mon immeuble a soixante-dix appartements.'],['Claire','A','That\'s a lot! Mine has only thirty.','C\'est beaucoup ! Le mien a seulement trente.'],['Romain','B','Well, fifty of them are small studios.','Eh bien, cinquante sont de petits studios.']],
  [['Thirty','/ˈθɜːrti/','Trente','Ne confondez pas "thirty" (30) et "thirteen" (13). Le "th" est crucial.'],['Fifty','/ˈfɪfti/','Cinquante','Prononcez bien le "f" : "fif-ti" et non "fiv-ti".'],['Seventy','/ˈsevənti/','Soixante-dix','L\'accent est sur la première syllabe : "SEV-en-ti".'],['Hundred','/ˈhʌndrəd/','Cent','Le "u" se prononce comme le "o" ouvert : "han-dred".']]
),
'a1-l8': lc( // Telling the Time (conversation)
  [["O'clock","Heure pile","/əˈklɒk/",'It is three o\'clock.','Il est trois heures.'],['Half past','Et demie','/hæf pæst/','It is half past two.','Il est deux heures et demie.'],['Quarter','Quart','/ˈkwɔːrtər/','It is quarter past five.','Il est cinq heures et quart.'],['AM/PM','Matin/Après-midi','/ˌeɪˈem/ /ˌpiːˈem/','The meeting is at 9 AM.','La réunion est à 9h du matin.']],
  'Telling the Time','Pour dire l\'heure : "It is [heure] o\'clock" (pile), "It is half past [heure]" (et demie), "It is quarter past [heure]" (et quart), "It is quarter to [heure]" (moins le quart). "AM" = matin, "PM" = après-midi.',
  [{s:'It is three o\'clock.',t:'Il est trois heures.',c:true},{s:'It is half past seven.',t:'Il est sept heures et demie.',c:true},{s:'It is quarter at ten.',t:'',c:false},{s:'The class starts at 9 AM.',t:'Le cours commence à 9h.',c:true}],
  [{w:'Quarter at ten',cr:'Quarter past ten / Quarter to ten',e:'On dit "quarter past" (et quart) ou "quarter to" (moins le quart), pas "quarter at".',},{w:'Half seven',cr:'Half past seven',e:'En anglais, on dit "half past seven", pas "half seven".']],
  [['Marie','A','What time is it now?','Quelle heure est-il maintenant ?'],['James','B','It is half past ten. We have time.','Il est dix heures et demie. On a le temps.'],['Marie','A','When does the train leave?','Quand part le train ?'],['James','B','At quarter past eleven. That\'s in 45 minutes.','À onze heures et quart. C\'est dans 45 minutes.'],['Marie','A','Good! And the meeting? I think it\'s at 2 PM.','Bien ! Et la réunion ? Je pense qu\'elle est à 14h.'],['James','B','Yes, at quarter to two. Don\'t be late!','Oui, à deux heures moins le quart. Ne sois pas en retard !']],
  [["O'clock",'/əˈklɒk/','Heure pile','Prononcez "e-klok" — le "c" est lu "k".'],['Quarter','/ˈkwɔːrtər/','Quart','Le "qu" = "k" : "kor-ter".'],['Half','/hæf/','Moitié/Demie','En anglais britannique, le "l" est muet : "haf".'],['Past','/pæst/','Passé/Après','Prononcez "past" avec le "a" ouvert.']]
),
'a1-l9': lc( // Days & Months (vocabulary)
  [['Monday','Lundi','/ˈmʌndeɪ/','I have class on Monday.','J\'ai cours le lundi.'],['Friday','Vendredi','/ˈfraɪdeɪ/','Friday is my favorite day.','Vendredi est mon jour préféré.'],['January','Janvier','/ˈdʒænjueri/','My birthday is in January.','Mon anniversaire est en janvier.'],['December','Décembre','/dɪˈsembər/','Christmas is in December.','Noël est en décembre.']],
  'Prepositions of Time — Days & Months','Avec les jours : "on Monday" (le lundi). Avec les mois : "in January" (en janvier). Avec les saisons : "in summer" (en été). "Every Monday" = chaque lundi. "Next Friday" = vendredi prochain.',
  [{s:'I study on Tuesday.',t:'J\'étudie le mardi.',c:true},{s:'She was born in March.',t:'Elle est née en mars.',c:true},{s:'We meet at Friday.',t:'',c:false},{s:'School starts in September.',t:'L\'école commence en septembre.',c:true}],
  [{w:'We meet at Friday.',cr:'We meet on Friday.',e:'On utilise "on" avec les jours, pas "at".',{w:'I go in Monday.',cr:'I go on Monday.',e:'Avec les jours de la semaine, c\'est toujours "on".']],
  [['Sophie','A','What day is it today?','Quel jour sommes-nous ?'],['Mike','B','It\'s Friday! I love Fridays.','C\'est vendredi ! J\'adore les vendredis.'],['Sophie','A','Me too! When is your birthday?','Moi aussi ! Quand est ton anniversaire ?'],['Mike','B','It\'s in January. And yours?','C\'est en janvier. Et le tien ?'],['Sophie','A','In December! I love winter. Every Monday I play tennis.','En décembre ! J\'adore l\'hiver. Chaque lundi je joue au tennis.'],['Mike','B','Cool! On Saturday I usually go swimming.','Cool ! Le samedi je vais généralement nager.']],
  [['Monday','/ˈmʌndeɪ/','Lundi','Le "o" est ouvert : "man-deï".'],['Friday','/ˈfraɪdeɪ/','Vendredi','Le "i" est long : "fraï-deï".'],['January','/ˈdʒænjueri/','Janvier','Le "j" anglais = "dj" : "djan-iou-eri".'],['December','/dɪˈsembər/','Décembre','L\'accent est sur "cem" : "di-SEM-ber".']]
),
'a1-l10': lc( // Number Pronunciation (pronunciation)
  [['Thirteen','Treize','/θɜːrˈtiːn/','She is thirteen.','Elle a treize ans.'],['Thirty','Trente','/ˈθɜːrti/','He is thirty.','Il a trente ans.'],['Fourteen','Quatorze','/fɔːrˈtiːn/','The number is fourteen.','Le nombre est quatorze.'],['Forty','Quarante','/ˈfɔːrti/','There are forty students.','Il y a quarante étudiants.']],
  'Teen vs. Ty — Number Stress','Les nombres en "-teen" (13-19) ont l\'accent sur la DEUXIÈME syllabe : thir-TEEN. Les dizaines en "-ty" (20, 30, 40...) ont l\'accent sur la PREMIÈRE syllabe : THIR-ty. C\'est crucial pour ne pas confondre 13 et 30 !',
  [{s:'She is thir-TEEN.',t:'Elle a treize ans.',c:true},{s:'He is THIR-ty years old.',t:'Il a trente ans.',c:true},{s:'There are four-TEEN people.',t:'Il y a quatorze personnes.',c:true},{s:'I have FOR-ty dollars.',t:'J\'ai quarante dollars.',c:true}],
  [{w:'thir-TEEN vs THIR-ty',cr:'Accent sur 2e syllabe pour -teen, 1re pour -ty',e:'Confondre ces accents peut changer le sens : 13 ≠ 30 !'},{w:'four-TEEN vs FOR-ty',cr:'Même règle : accent 2e pour -teen, 1re pour -ty',e:'14 ≠ 40 ! Notez aussi que "forty" s\'écrit sans "u".']],
  [['Teacher','A','Can you say the number: thirteen or thirty?','Pouvez-vous dire le nombre : treize ou trente ?'],['Student','B','Thir-TEEN is 13. THIR-ty is 30.','Thir-TINE est 13. THIR-ti est 30.'],['Teacher','A','Very good! Now: fourteen or forty?','Très bien ! Maintenant : quatorze ou quarante ?'],['Student','B','Four-TEEN is 14. FOR-ty is 40.','Four-TINE est 14. FOR-ti est 40.'],['Teacher','A','Perfect! How about fifty and fifteen?','Parfait ! Et cinquante et quinze ?'],['Student','B','FIF-ty is 50. Fif-TEEN is 15.','FIF-ti est 50. Fif-TINE est 15.']],
  [['Thirteen','/θɜːrˈtiːn/','Treize','Accent sur TEEN : "ther-TINE". Le "th" est expiré.'],['Thirty','/ˈθɜːrti/','Trente','Accent sur THIR : "THER-ti". Plus court à la fin.'],['Fourteen','/fɔːrˈtiːn/','Quatorze','Accent sur TEEN : "for-TINE".'],['Forty','/ˈfɔːrti/','Quarante','Accent sur FOR : "FOR-ti". Notez : pas de "u" dans "forty".']]
),

// ═══ Unit 3: Everyday Objects ═══
'a1-l11': lc( // Classroom Objects (vocabulary)
  [['Pen','Stylo','/pen/','Can I borrow your pen?','Puis-je emprunter ton stylo ?'],['Book','Livre','/bʊk/','Open your book to page five.','Ouvrez votre livre à la page cinq.'],['Table','Table','/ˈteɪbəl/','Put it on the table.','Mets-le sur la table.'],['Chair','Chaise','/tʃer/','Please sit on the chair.','Asseyez-vous sur la chaise.']],
  'Plural of Nouns — Regular','Pluriel régulier : on ajoute -s (book→books, pen→pens). Après s, ss, sh, ch, x : on ajoute -es (bus→buses, box→boxes). Après consonne+y : y→i+es (city→cities). Après voyelle+y : on ajoute -s (day→days).',
  [{s:'I have two books.',t:'J\'ai deux livres.',c:true},{s:'There are three boxs.',t:'',c:false},{s:'The cities are big.',t:'Les villes sont grandes.',c:true},{s:'She has five pens.',t:'Elle a cinq stylos.',c:true}],
  [{w:'Three boxs',cr:'Three boxes',e:'Après x, on ajoute -es : box→boxes.'},{w:'Two citys',cr:'Two cities',e:'Après consonne+y : y→i+es : city→cities.']],
  [['Teacher','A','Please open your books to page twelve.','Ouvrez vos livres à la page douze.'],['Student','B','I don\'t have a book. Can I share?','Je n\'ai pas de livre. Je peux partager ?'],['Teacher','A','Of course. Sit at this table with Marie.','Bien sûr. Assieds-toi à cette table avec Marie.'],['Student','B','Thank you! Can I borrow a pen too?','Merci ! Je peux aussi emprunter un stylo ?'],['Teacher','A','Yes, here is a pen. Now, everyone, sit on your chairs.','Oui, voici un stylo. Maintenant, asseyez-vous sur vos chaises.'],['Student','B','Got it! The pen is on the table.','C\'est bon ! Le stylo est sur la table.']],
  [['Pen','/pen/','Stylo','Le "e" est fermé comme dans "pé".'],['Book','/bʊk/','Livre','Le "oo" est court : "bouk" — pas "bououk".'],['Table','/ˈteɪbəl/','Table','Prononcez "té-bal" avec le "a" très réduit.'],['Chair','/tʃer/','Chaise','Le "ch" = "tch" : "tchér".']]
),
'a1-l12': lc( // Articles: A & An (grammar)
  [['Apple','Pomme','/ˈæpəl/','I eat an apple every day.','Je mange une pomme chaque jour.'],['University','Université','/ˌjuːnɪˈvɜːrsəti/','She goes to a university.','Elle va à une université.'],['Hour','Heure','/aʊr/','I study for an hour.','J\'étudie pendant une heure.'],['European','Européen','/ˌjʊrəˈpiːən/','He is a European student.','C\'est un étudiant européen.']],
  'Articles: A vs An','On utilise "a" devant un mot commençant par un SON consonantique, et "an" devant un SON vocalique. Attention : c\'est le SON qui compte, pas l\'orthographe ! "A university" (son "you") mais "an hour" (le "h" est muet).',
  [{s:'I have a dog.',t:'J\'ai un chien.',c:true},{s:'She is an teacher.',t:'',c:false},{s:'He wants an orange.',t:'Il veut une orange.',c:true},{s:'There is a university here.',t:'Il y a une université ici.',c:true}],
  [{w:'An university',cr:'A university',e:'"University" commence par le son "you" qui est consonantique → "a".',{w:'A hour',cr:'An hour',e:'"Hour" commence par le son "aou" (h muet) qui est vocalique → "an".']],
  [['Alex','A','I want an apple. Do you have a banana?','Je veux une pomme. As-tu une banane ?'],['Sara','B','No banana, but I have an orange!','Pas de banane, mais j\'ai une orange !'],['Alex','A','Great! An orange is good too. Is it a European orange?','Super ! Une orange c\'est bien aussi. C\'est une orange européenne ?'],['Sara','B','No, it\'s a Moroccan orange! I bought it an hour ago.','Non, c\'est une orange marocaine ! Je l\'ai achetée il y a une heure.'],['Alex','A','A student at my university sells them.','Un étudiant de mon université les vend.'],['Sara','B','Oh? I study at a European university too!','Oh ? J\'étudie aussi dans une université européenne !']],
  [['Apple','/ˈæpəl/','Pomme','Le "a" est très ouvert : "ap-pl".'],['University','/ˌjuːnɪˈvɜːrsəti/','Université','Commence par le son "you" : "iou-ni-ver-si-ti".'],['Hour','/aʊr/','Heure','Le "h" est MUET : "aour" — comme en français !'],['European','/ˌjʊrəˈpiːən/','Européen','Commence par le son "you" : "you-ro-pi-en".']]
),
'a1-l13': lc( // This & That (grammar)
  [['This','Ceci/Ce','/ðɪs/','This is my pen.','Ceci est mon stylo.'],['That','Cela/Ce','/ðæt/','That is your book.','Cela est ton livre.'],['These','Ces','/ðiːz/','These are my shoes.','Ce sont mes chaussures.'],['Those','Ces (loin)','/ðoʊz/','Those are your chairs.','Ce sont vos chaises.']],
  'Demonstratives: This/That/These/Those',"This" (proche, singulier), "that" (éloigné, singulier), "these" (proche, pluriel), "those" (éloigné, pluriel). En français, "ce/cet/cette" pour singulier et "ces" pour pluriel, sans distinction de distance.',
  [{s:'This is my book.',t:'Ceci est mon livre.',c:true},{s:'That are my shoes.',t:'',c:false},{s:'These are my pens.',t:'Ce sont mes stylos.',c:true},{s:'Those is your chairs.',t:'',c:false}],
  [{w:'That are my books.',cr:'Those are my books.',e:'Au pluriel, on utilise "those" et non "that".',{w:'This is my shoes.',cr:'These are my shoes.',e:'"Shoes" est pluriel, on utilise "these" au lieu de "this".']],
  [['Anna','A','What is this?','Qu\'est-ce que c\'est ?'],['Paul','B','This is a pen. It\'s on the table.','C\'est un stylo. Il est sur la table.'],['Anna','A','And what is that over there?','Et qu\'est-ce que c\'est là-bas ?'],['Paul','B','That is a computer. It\'s near the window.','C\'est un ordinateur. Il est près de la fenêtre.'],['Anna','A','Are these your books?','Ce sont tes livres ?'],['Paul','B','No, those are Maria\'s books. These are mine.','Non, ceux-là sont les livres de Maria. Ceux-ci sont à moi.']],
  [['This','/ðɪs/','Ceci','Le "th" est expiré, langue entre les dents : "diss".'],['That','/ðæt/','Cela','Le "a" est ouvert : "dhat".'],['These','/ðiːz/','Ces (proche)','Le "ee" est long : "dhii-z".'],['Those','/ðoʊz/','Ces (loin)','Le "o" est long : "dho-z".']]
),
'a1-l14': lc( // At the Office (conversation)
  [['Computer','Ordinateur','/kəmˈpjuːtər/','Turn on the computer.','Allume l\'ordinateur.'],['Phone','Téléphone','/foʊn/','The phone is ringing.','Le téléphone sonne.'],['Desk','Bureau','/desk/','Your papers are on the desk.','Tes papiers sont sur le bureau.'],['Printer','Imprimante','/ˈprɪntər/','I need to use the printer.','J\'ai besoin d\'utiliser l\'imprimante.']],
  'Prepositions of Place','Les prépositions de lieu : "on" (sur), "in" (dans), "under" (sous), "next to" (à côté de), "between" (entre), "behind" (derrière), "in front of" (devant).',
  [{s:'The pen is on the desk.',t:'Le stylo est sur le bureau.',c:true},{s:'The computer is in the desk.',t:'',c:false},{s:'She is next to the printer.',t:'Elle est à côté de l\'imprimante.',c:true},{s:'The phone is under the table.',t:'Le téléphone est sous la table.',c:true}],
  [{w:'The computer is in the desk.',cr:'The computer is on the desk.',e:'Un ordinateur est SUR le bureau, pas DANS le bureau.'},{w:'She is next the door.',cr:'She is next to the door.',e:'Il faut "next TO", pas juste "next".']],
  [['Boss','A','Where is the report?','Où est le rapport ?'],['Employee','B','It\'s on your desk, next to the phone.','Il est sur votre bureau, à côté du téléphone.'],['Boss','A','I don\'t see it. Is it under the computer?','Je ne le vois pas. Est-il sous l\'ordinateur ?'],['Employee','B','No, it\'s between the printer and the keyboard.','Non, il est entre l\'imprimante et le clavier.'],['Boss','A','Oh, here it is! Thank you. Can you print another copy?','Oh, le voilà ! Merci. Peux-tu imprimer une autre copie ?'],['Employee','B','Sure! The printer is in the next room, behind the door.','Bien sûr ! L\'imprimante est dans la pièce d\'à côté, derrière la porte.']],
  [['Computer','/kəmˈpjuːtər/','Ordinateur','L\'accent est sur "pu" : "kom-Piou-ter".'],['Phone','/foʊn/','Téléphone','Le "ph" = "f" : "fone".'],['Desk','/desk/','Bureau','Prononcez "dèsk" avec le "e" ouvert.'],['Printer','/ˈprɪntər/','Imprimante','L\'accent sur "print" : "PRIN-ter".']]
),
'a1-l15': lc( // Object Sounds (pronunciation)
  [['Watch','Montre','/wɒtʃ/','Look at my watch.','Regarde ma montre.'],['Switch','Interrupteur','/swɪtʃ/','Turn off the switch.','Éteins l\'interrupteur.'],['Clock','Horloge','/klɒk/','The clock is on the wall.','L\'horloge est sur le mur.'],['Glass','Verre','/ɡlæs/','The glass is on the table.','Le verre est sur la table.']],
  'The "ch" Sound in English','Le "ch" anglais se prononce "tch" : watch (tch), chair (tch), kitchen (tch). ATTENTION : parfois "ch" se prononce "k" : school, chemistry, character. Et parfois "ch" = "sh" : machine, chef.',
  [{s:'I watch TV every day.',t:'Je regarde la télé chaque jour.',c:true},{s:'She goes to shool.',t:'',c:false},{s:'The clock is on the wall.',t:'L\'horloge est sur le mur.',c:true},{s:'The mashine is new.',t:'',c:false}],
  [{w:'Shool',cr:'School',e:'Dans "school", le "ch" = "k" : "skoul".',{w:'Mashine',cr:'Machine',e:'Dans "machine", le "ch" = "sh" : "ma-chine".']],
  [['Tom','A','What time is it? I can\'t find my watch.','Quelle heure est-il ? Je ne trouve pas ma montre.'],['Lisa','B','Look at the clock on the wall!','Regarde l\'horloge sur le mur !'],['Tom','A','Oh! It\'s late. Turn off the switch, let\'s go.','Oh ! Il est tard. Éteins l\'interrupteur, on y va.'],['Lisa','B','Wait! Can you pass me that glass?','Attends ! Peux-tu me passer ce verre ?'],['Tom','A','Sure. Here you go. This switch is hard to reach.','Bien sûr. Tiens. Cet interrupteur est difficile à atteindre.'],['Lisa','B','Thanks! The school clock is always five minutes fast.','Merci ! L\'horloge de l\'école est toujours en avance de cinq minutes.']],
  [['Watch','/wɒtʃ/','Montre','Le "ch" = "tch" : "ouot-tch".'],['Switch','/swɪtʃ/','Interrupteur','Même son "tch" : "souit-tch".'],['Clock','/klɒk/','Horloge','Le "cl" = "kl" : "klok".'],['Glass','/ɡlæs/','Verre','Le "gl" = "gl" : "glès" avec le "a" ouvert.']]
),

// ═══ Unit 4: Food & Drinks ═══
'a1-l16': lc( // Common Foods (vocabulary)
  [['Bread','Pain','/bred/','I eat bread for breakfast.','Je mange du pain au petit-déjeuner.'],['Rice','Riz','/raɪs/','We eat rice with chicken.','Nous mangeons du riz avec du poulet.'],['Meat','Viande','/miːt/','He doesn\'t eat meat.','Il ne mange pas de viande.'],['Vegetables','Légumes','/ˈvedʒtəbəlz/','Eat your vegetables!','Mange tes légumes !']],
  'Countable vs Uncountable Food Words','Certains aliments sont dénombrables (a banana, two eggs) et d\'autres indénombrables (bread, rice, meat, water). Avec les indénombrables, on ne dit PAS "a bread" mais "some bread" ou "a piece of bread".',
  [{s:'I would like some bread.',t:'Je voudrais du pain.',c:true},{s:'Can I have a rice?',t:'',c:false},{s:'She eats two eggs.',t:'Elle mange deux œufs.',c:true},{s:'I need some meat.',t:'J\'ai besoin de viande.',c:true}],
  [{w:'A rice',cr:'Some rice / A bowl of rice',e:'"Rice" est indénombrable. On dit "some rice" ou "a bowl of rice".',{w:'Two breads',cr:'Two pieces of bread / Two slices of bread',e:'"Bread" est indénombrable. On compte les tranches/morceaux.']],
  [['Sophie','A','What do you like to eat?','Qu\'aimes-tu manger ?'],['Mike','B','I like rice and chicken. And you?','J\'aime le riz et le poulet. Et toi ?'],['Sophie','A','I love bread and cheese! Do you eat vegetables?','J\'adore le pain et le fromage ! Manges-tu des légumes ?'],['Mike','B','Yes, I eat some vegetables every day. Not much meat.','Oui, je mange des légumes chaque jour. Pas beaucoup de viande.'],['Sophie','A','Me too. I prefer a piece of bread with some cheese.','Moi aussi. Je préfère un morceau de pain avec du fromage.'],['Mike','B','That sounds delicious! Let\'s have lunch together.','Ça a l\'air délicieux ! Déjeunons ensemble.']],
  [['Bread','/bred/','Pain','Le "ea" = "é" court : "brède".'],['Rice','/raɪs/','Riz','Le "i" est long : "raïce".'],['Meat','/miːt/','Viande','Le "ea" = "ii" long : "miit".'],['Vegetables','/ˈvedʒtəbəlz/','Légumes','Le premier "e" est fermé : "védj-te-belz".']]
),
'a1-l17': lc( // Drinks & Beverages (vocabulary)
  [['Water','Eau','/ˈwɔːtər/','Can I have some water?','Puis-je avoir de l\'eau ?'],['Coffee','Café','/ˈkɒfi/','I drink coffee every morning.','Je bois du café chaque matin.'],['Tea','Thé','/tiː/','She prefers tea.','Elle préfère le thé.'],['Juice','Jus','/dʒuːs/','Orange juice is healthy.','Le jus d\'orange est sain.']],
  'Expressing Preferences — Drinks','Pour exprimer ses préférences de boissons : "I drink" (je bois), "I prefer" (je préfère), "I would like" (je voudrais). "A cup of tea/coffee" (une tasse de), "a glass of water/juice" (un verre de).',
  [{s:'I would like a cup of coffee.',t:'Je voudrais une tasse de café.',c:true},{s:'She prefers tea than coffee.',t:'',c:false},{s:'Can I have a glass of water?',t:'Puis-je avoir un verre d\'eau ?',c:true},{s:'He drinks two cups of tea.',t:'Il boit deux tasses de thé.',c:true}],
  [{w:'I prefer tea than coffee.',cr:'I prefer tea to coffee.',e:'Après "prefer", on utilise "to" pas "than".',{w:'A water please.',cr:'A glass of water please. / Some water please.',e:'"Water" est indénombrable. On dit "a glass of water" ou "some water".']],
  [['Waiter','A','What would you like to drink?','Que souhaitez-vous boire ?'],['Customer','B','I would like a cup of coffee, please.','Je voudrais une tasse de café, s\'il vous plaît.'],['Waiter','A','Regular or decaf? We also have tea and juice.','Normal ou déca ? Nous avons aussi du thé et du jus.'],['Customer','B','Regular, please. My friend prefers tea to coffee.','Normal, s\'il vous plaît. Mon ami préfère le thé au café.'],['Waiter','A','Great! And for your friend?','Très bien ! Et pour votre ami ?'],['Customer','B','A glass of orange juice, please. And some water.','Un verre de jus d\'orange, s\'il vous plaît. Et de l\'eau.']],
  [['Water','/ˈwɔːtər/','Eau','Le "t" au milieu peut sonner comme un "d" en américain : "ouo-der".'],['Coffee','/ˈkɒfi/','Café','Le "o" est ouvert : "ko-fi".'],['Tea','/tiː/','Thé','Le "ea" = "ii" long : "tii".'],['Juice','/dʒuːs/','Jus','Le "j" = "dj" et "u" long : "djouss".']]
),
'a1-l18': lc( // I Like / I Don't Like (grammar)
  [['Like','Aimer','/laɪk/','I like pizza.','J\'aime la pizza.'],['Love','Adorer','/lʌv/','I love chocolate!','J\'adore le chocolat !'],['Hate','Détester','/heɪt/','He hates onions.','Il déteste les oignons.'],['Prefer','Préférer','/prɪˈfɜːr/','I prefer tea.','Je préfère le thé.']],
  'Like / Likes / Don\'t Like / Doesn\'t Like','Avec I/you/we/they : "like" (base). Avec he/she/it : "likes" (+s). Négatif : "don\'t like" / "doesn\'t like". "Love" et "hate" suivent la même règle. Après like/love/hate : nom OU verbe en -ing.',
  [{s:'I like coffee.',t:'J\'aime le café.',c:true},{s:'I don\'t like fish.',t:'Je n\'aime pas le poisson.',c:true},{s:'She like pizza.',t:'',c:false},{s:'He doesn\'t like vegetables.',t:'Il n\'aime pas les légumes.',c:true}],
  [{w:'She like coffee.',cr:'She likes coffee.',e:'Avec he/she/it, on ajoute "s" : likes.'},{w:'He don\'t like rice.',cr:'He doesn\'t like rice.',e:'Avec he/she/it, on utilise "doesn\'t" au lieu de "don\'t".']],
  [['Sophie','A','What food do you like?','Quelle nourriture aimes-tu ?'],['Mike','B','I love pasta and chicken! I hate mushrooms.','J\'adore les pâtes et le poulet ! Je déteste les champignons.'],['Sophie','A','Really? I like mushrooms. Do you like fish?','Vraiment ? J\'aime les champignons. Aimes-tu le poisson ?'],['Mike','B','No, I don\'t like fish. I prefer meat. And you?','Non, je n\'aime pas le poisson. Je préfère la viande. Et toi ?'],['Sophie','A','I like fish a lot! My sister loves sushi.','J\'aime beaucoup le poisson ! Ma sœur adore les sushis.'],['Mike','B','She doesn\'t like French food? That\'s unusual!','Elle n\'aime pas la cuisine française ? C\'est inhabituel !']],
  [['Like','/laɪk/','Aimer','Le "i" est long : "laïk".'],['Love','/lʌv/','Adorer','Le "u" est ouvert : "leuv".'],['Hate','/heɪt/','Détester','Le "h" est expiré : "héït".'],['Prefer','/prɪˈfɜːr/','Préférer','L\'accent sur "fer" : "pri-FER".']]
),
'a1-l19': lc( // Ordering at a Café (conversation)
  [['Order','Commander','/ˈɔːrdər/','I would like to order.','Je voudrais commander.'],['Menu','Menu','/ˈmenjuː/','Can I see the menu?','Puis-je voir le menu ?'],['Bill','L\'addition','/bɪl/','The bill, please.','L\'addition, s\'il vous plaît.'],['Tip','Pourboire','/tɪp/','I left a tip.','J\'ai laissé un pourboire.']],
  'Polite Requests in a Café','Pour commander poliment : "I would like..." (Je voudrais...), "Can I have...?" (Puis-je avoir...?), "Could I get...?" (Pourrais-je obtenir...?). "Please" à la fin de chaque demande. "Thank you" quand on reçoit quelque chose.',
  [{s:'I would like a coffee, please.',t:'Je voudrais un café, s\'il vous plaît.',c:true},{s:'Give me a water.',t:'',c:false},{s:'Can I have the bill, please?',t:'Puis-je avoir l\'addition, s\'il vous plaît ?',c:true},{s:'Could I see the menu?',t:'Pourrais-je voir le menu ?',c:true}],
  [{w:'Give me a water.',cr:'I would like some water, please.',e:'"Give me" est impoli. Utilisez "I would like" + "please".',{w:'I want the bill.',cr:'Could I have the bill, please?',e:'"I want" est trop direct. "Could I have" est plus poli.']],
  [['Waiter','A','Good afternoon! Would you like to order?','Bon après-midi ! Souhaitez-vous commander ?'],['Customer','B','Yes! Can I have the menu, please?','Oui ! Puis-je avoir le menu, s\'il vous plaît ?'],['Waiter','A','Of course! Here it is. Our special today is the chocolate cake.','Bien sûr ! Le voici. Notre spécialité aujourd\'hui est le gâteau au chocolat.'],['Customer','B','I would like a coffee and a piece of chocolate cake, please.','Je voudrais un café et un morceau de gâteau au chocolat, s\'il vous plaît.'],['Waiter','A','Anything else?','Autre chose ?'],['Customer','B','No, thank you. Could I have the bill when you\'re ready?','Non, merci. Pourrais-je avoir l\'addition quand vous serez prêt ?']],
  [['Order','/ˈɔːrdər/','Commander','L\'accent sur "or" : "OR-der".'],['Menu','/ˈmenjuː/','Menu','Le "u" final est long : "mé-niou".'],['Bill','/bɪl/','L\'addition','Le "i" est court : "bil".'],['Tip','/tɪp/','Pourboire','Le "i" est court : "tip".']]
),
'a1-l20': lc( // Food Pronunciation (pronunciation)
  [['Breakfast','Petit-déjeuner','/ˈbrekfəst/','I eat breakfast at seven.','Je prends le petit-déjeuner à sept heures.'],['Lunch','Déjeuner','/lʌntʃ/','Lunch is at noon.','Le déjeuner est à midi.'],['Dinner','Dîner','/ˈdɪnər/','Dinner is at seven PM.','Le dîner est à 19h.'],['Recipe','Recette','/ˈresəpi/','This recipe is easy.','Cette recette est facile.']],
  'Vowel Sounds in Food Words','Les voyelles en anglais peuvent être trompeuses : "breakfast" se prononce "brek-fust" (pas "brék-fest"), "recipe" = "res-si-pi" (pas "ré-saïp"), "dinner" = "din-er" (i court), "lunch" = "leunt-ch" (u ouvert).',
  [{s:'Breakfast is at 8 AM.',t:'Le petit-déjeuner est à 8h.',c:true},{s:'I eat re-saï-pi every day.',t:'',c:false},{s:'Lunch is my favorite meal.',t:'Le déjeuner est mon repas préféré.',c:true},{s:'Dinner time is family time.',t:'L\'heure du dîner est le moment en famille.',c:true}],
  [{w:'Re-saï-pi',cr:'Res-si-pi',e:'"Recipe" se prononce "ré-si-pi", le "i" est court dans les deux dernières syllabes.',{w:'Brék-fest',cr:'Brek-fust',e:'Dans "breakfast", le "ea" = "e" court et le "a" est réduit à "u".']],
  [['Chef','A','Let\'s start with breakfast. What do you eat?','Commençons par le petit-déjeuner. Que mangez-vous ?'],['Student','B','I have breakfast at seven. Usually bread and coffee.','Je prends le petit-déjeuner à sept heures. Généralement du pain et du café.'],['Chef','A','Good. And lunch? What time?','Bien. Et le déjeuner ? À quelle heure ?'],['Student','B','Lunch is at noon. I eat a big lunch, then a small dinner.','Le déjeuner est à midi. Je mange un gros déjeuner, puis un petit dîner.'],['Chef','A','Interesting! Do you cook? What\'s your favorite recipe?','Intéressant ! Cuisinez-vous ? Quelle est votre recette préférée ?'],['Student','B','Yes! My favorite recipe is pasta with vegetables.','Oui ! Ma recette préférée est les pâtes aux légumes.']],
  [['Breakfast','/ˈbrekfəst/','Petit-déjeuner','On prononce "brek-fust" — pas "brék-fest".'],['Lunch','/lʌntʃ/','Déjeuner','Le "u" est ouvert : "leunt-ch". Le "ch" = "tch".'],['Dinner','/ˈdɪnər/','Dîner','Le "i" est court : "din-er".'],['Recipe','/ˈresəpi/','Recette','Prononcez "ré-si-pi" — les "i" sont courts.']]
),

// ═══ Unit 5: Family & Relationships ═══
'a1-l21': lc( // Family Members (vocabulary)
  [['Mother','Mère','/ˈmʌðər/','My mother is a doctor.','Ma mère est médecin.'],['Father','Père','/ˈfɑːðər/','His father works in Paris.','Son père travaille à Paris.'],['Sister','Sœur','/ˈsɪstər/','I have one sister.','J\'ai une sœur.'],['Brother','Frère','/ˈbrʌðər/','My brother is older than me.','Mon frère est plus âgé que moi.']],
  'Family Vocabulary — Possessives','Pour parler de sa famille : "my mother" (ma mère), "his father" (son père), "her sister" (sa sœur). L\'adjectif possessif s\'accorde avec le possesseur : "her brother" = le frère de elle, "his brother" = le frère de lui.',
  [{s:'My mother is a nurse.',t:'Ma mère est infirmière.',c:true},{s:'His father are a teacher.',t:'',c:false},{s:'Her sister is married.',t:'Sa sœur est mariée.',c:true},{s:'Their brother lives in Paris.',t:'Leur frère vit à Paris.',c:true}],
  [{w:'His father are a teacher.',cr:'His father is a teacher.',e:'"Father" est singulier → "is", pas "are".',{w:'She brother is young.',cr:'Her brother is young.',e:'Pour parler du frère de "she", on utilise "her" pas "she".']],
  [['Clara','A','Tell me about your family!','Parle-moi de ta famille !'],['David','B','I have a big family. I have two brothers and one sister.','J\'ai une grande famille. J\'ai deux frères et une sœur.'],['Clara','A','That\'s nice! What does your mother do?','C\'est sympa ! Que fait ta mère ?'],['David','B','My mother is a nurse. My father is an engineer.','Ma mère est infirmière. Mon père est ingénieur.'],['Clara','A','Is your sister older or younger?','Ta sœur est plus âgée ou plus jeune ?'],['David','B','She is younger. She is still a student.','Elle est plus jeune. Elle est encore étudiante.']],
  [['Mother','/ˈmʌðər/','Mère','Le "th" sonore : langue entre les dents, cordes vocales vibrent : "meu-der".'],['Father','/ˈfɑːðər/','Père','Même "th" sonore : "fa-der".'],['Sister','/ˈsɪstər/','Sœur','Prononcez "sis-ter" avec le "i" court.'],['Brother','/ˈbrʌðər/','Frère','Même "th" sonore : "bra-der".']]
),
'a1-l22': lc( // Possessive Adjectives (grammar)
  [['My','Mon/Ma','/maɪ/','This is my book.','C\'est mon livre.'],['Your','Ton/Ta/Votre','/jʊr/','Is this your pen?','Est-ce ton stylo ?'],['His','Son/Sa (masc)','/hɪz/','This is his car.','C\'est sa voiture (à lui).'],['Her','Son/Sa (fém)','/hɜːr/','This is her bag.','C\'est son sac (à elle).']],
  'Possessive Adjectives — Full List','my (mon/ma/mes), your (ton/ta/tes/votre/vos), his (son/sa/ses — de lui), her (son/sa/ses — d\'elle), its (son/sa/ses — de ça), our (notre/nos), their (leur/leurs). L\'adjectif s\'accorde avec le POSSESSEUR, pas l\'objet ! "Her book" = le livre de elle (masculin en anglais car c\'est elle qui possède).',
  [{s:'This is my book.',t:'C\'est mon livre.',c:true},{s:'She loves his family.',t:'Elle aime sa famille (à lui).',c:true},{s:'He loves her mother.',t:'',c:false},{s:'This is their house.',t:'C\'est leur maison.',c:true}],
  [{w:'This is the book of John.',cr:'This is John\'s book.',e:'On utilise l\'apostrophe+s pour la possession : John\'s, pas "of John".',{w:'She loves his mother.',cr:'She loves her mother.',e:'"Her" car c\'est la mère de "she" (elle), pas de "he" (lui).']],
  [['Tom','A','Is this your pen?','Est-ce ton stylo ?'],['Sara','B','No, it\'s not my pen. It\'s his pen — ask Kevin.','Non, ce n\'est pas mon stylo. C\'est son stylo — demande à Kevin.'],['Tom','A','Kevin! Is this your pen?','Kevin ! Est-ce ton stylo ?'],['Kevin','C','No, my pen is blue. That\'s her pen — it\'s Maria\'s.','Non, mon stylo est bleu. C\'est son stylo — c\'est à Maria.'],['Tom','A','Oh! Maria, here is your pen!','Oh ! Maria, voici ton stylo !'],['Maria','D','Thank you! I was looking for it. Our teacher has similar pens.','Merci ! Je le cherchais. Notre professeur a des stylos similaires.']],
  [['My','/maɪ/','Mon/Ma','Le "i" est long : "maï".'],['Your','/jʊr/','Ton/Ta','Prononcez "iour" — comme "your" sans le "y" initial.'],['His','/hɪz/','Son (à lui)','Le "h" est expiré : "hiz". Ne confondez pas avec "he\'s" = "il est".'],['Her','/hɜːr/','Son/Sa (à elle)','Prononcez "heur" — le "h" est expiré.']]
),
'a1-l23': lc( // Describing Family (conversation)
  [['Aunt','Tante','/ænt/','My aunt lives in Lyon.','Ma tante vit à Lyon.'],['Uncle','Oncle','/ˈʌŋkəl/','His uncle is a chef.','Son oncle est chef.'],['Cousin','Cousin/Cousine','/ˈkʌzən/','I have many cousins.','J\'ai beaucoup de cousins.'],['Grandmother','Grand-mère','/ˈɡrændmʌðər/','My grandmother is 80.','Ma grand-mère a 80 ans.']],
  'Describing People — Family Traits','Pour décrire les membres de la famille : "She is tall" (elle est grande), "He is kind" (il est gentil), "They are funny" (ils sont drôles). "Looks like" : "She looks like her mother" (elle ressemble à sa mère). "Takes after" : "He takes after his father" (il tient de son père).',
  [{s:'My aunt is very kind.',t:'Ma tante est très gentille.',c:true},{s:'She look like her mother.',t:'',c:false},{s:'He takes after his uncle.',t:'Il tient de son oncle.',c:true},{s:'My cousins are funny.',t:'Mes cousins sont drôles.',c:true}],
  [{w:'She look like her mother.',cr:'She looks like her mother.',e:'Avec he/she/it, on ajoute "s" : looks.'},{w:'He take after his father.',cr:'He takes after his father.',e:'Même règle : takes avec "s" à la 3e personne.']],
  [['Emma','A','Do you have a big family?','As-tu une grande famille ?'],['Lucas','B','Yes! I have two uncles and three aunts. And many cousins!','Oui ! J\'ai deux oncles et trois tantes. Et beaucoup de cousins !'],['Emma','A','Wow! What does your grandmother look like?','Wow ! À quoi ressemble ta grand-mère ?'],['Lucas','B','She is tall and kind. She looks like my mother.','Elle est grande et gentille. Elle ressemble à ma mère.'],['Emma','A','My grandmother is funny. She is 75 years old.','Ma grand-mère est drôle. Elle a 75 ans.'],['Lucas','B','My grandfather is 80! He takes after his father — very active.','Mon grand-père a 80 ans ! Il tient de son père — très actif.']],
  [['Aunt','/ænt/','Tante','Le "a" est très ouvert : "ant" — comme la fourmi en anglais !'],['Uncle','/ˈʌŋkəl/','Oncle','Le "un" = "eun" : "eung-kel".'],['Cousin','/ˈkʌzən/','Cousin(e)','Prononcez "keuz-én" — le "s" = "z" sonore.'],['Grandmother','/ˈɡrændmʌðər/','Grand-mère','Le "th" sonore : "grannd-meu-der".']]
),
'a1-l24': lc( // Have / Has (grammar)
  [['Have','Avoir','/hæv/','I have a big family.','J\'ai une grande famille.'],['Has','Avoir (3e pers.)','/hæz/','She has two brothers.','Elle a deux frères.'],['Have got','Avoir (variante)','/hæv ɡɒt/','I have got a car.','J\'ai une voiture.'],['Hasn\'t','N\'a pas','/ˈhæzənt/','He hasn\'t got a bike.','Il n\'a pas de vélo.']],
  'Have vs Has vs Have Got','I/you/we/they → "have". He/she/it → "has". "Have got" est plus courant en anglais britannique : "I\'ve got" = "I have". Négatif : "don\'t have" / "doesn\'t have" ou "haven\'t got" / "hasn\'t got". Questions : "Do you have...?" / "Have you got...?"',
  [{s:'I have two sisters.',t:'J\'ai deux sœurs.',c:true},{s:'She have a car.',t:'',c:false},{s:'He has got a new phone.',t:'Il a un nouveau téléphone.',c:true},{s:'They has three children.',t:'',c:false}],
  [{w:'She have a car.',cr:'She has a car.',e:'Avec he/she/it, on utilise "has", pas "have".',{w:'They has three children.',cr:'They have three children.',e:'"They" prend "have", pas "has".']],
  [['Interviewer','A','Do you have any siblings?','As-tu des frères et sœurs ?'],['Candidate','B','Yes, I have two brothers. My older brother has three kids.','Oui, j\'ai deux frères. Mon grand frère a trois enfants.'],['Interviewer','A','That\'s nice! Have you got a pet?','C\'est sympa ! As-tu un animal de compagnie ?'],['Candidate','B','Yes, I\'ve got a cat. She has green eyes.','Oui, j\'ai un chat. Elle a les yeux verts.'],['Interviewer','A','Beautiful! Does your brother have a pet too?','Beau ! Ton frère a-t-il aussi un animal ?'],['Candidate','B','No, he hasn\'t got a pet. He doesn\'t have time.','Non, il n\'a pas d\'animal. Il n\'a pas le temps.']],
  [['Have','/hæv/','Avoir','Le "a" est ouvert : "hav".'],['Has','/hæz/','Avoir (3e)','Le "s" est sonore : "haz".'],['Got','/ɡɒt/','Obtenu/Eu','Le "o" est ouvert : "got".'],['Hasn\'t','/ˈhæzənt/','N\'a pas','Prononcez "ha-zent".']]
),
'a1-l25': lc( // Family Words Sounds (pronunciation)
  [['Daughter','Fille','/ˈdɔːtər/','Their daughter is very smart.','Leur fille est très intelligente.'],['Husband','Mari','/ˈhʌzbənd/','Her husband is a teacher.','Son mari est professeur.'],['Nephew','Neveu','/ˈnefjuː/','My nephew is five years old.','Mon neveu a cinq ans.'],['Niece','Nièce','/niːs/','His niece is adorable.','Sa nièce est adorable.']],
  'The "th" Sound — Voiced vs Voiceless','Deux sons "th" en anglais : 1) Voicing (sonore) : la langue entre les dents, cordes vocales vibrent — "mother", "brother", "this". 2) Voiceless (sourd) : même position mais sans vibration — "think", "three", "thirty". En français, le "th" n\'existe pas.',
  [{s:'Mother — voiced "th"',t:'Mère — "th" sonore',c:true},{s:'Think — voiceless "th"',t:'Penser — "th" sourd',c:true},{s:'This — voiceless "th"',t:'',c:false},{s:'Three — voiceless "th"',t:'Trois — "th" sourd',c:true}],
  [{w:'This — voiceless "th"',cr:'This — voiced "th"',e:'"This" a un "th" sonore (comme "mother"), pas sourd (comme "think").',{w:'Think — voiced "th"',cr:'Think — voiceless "th"',e:'"Think" a un "th" sourd (comme "three"), pas sonore (comme "this").']],
  [['Teacher','A','Let\'s practice the "th" sound. Say "mother".','Pratiquons le son "th". Dites "mother".'],['Student','B','Mu-der. The "th" is voiced, right?','Meu-der. Le "th" est sonore, c\'est ça ?'],['Teacher','A','Perfect! Now "think" — this is voiceless. Air only.','Parfait ! Maintenant "think" — c\'est sourd. Juste de l\'air.'],['Student','B','Think. I feel the air on my tongue!','Think. Je sens l\'air sur ma langue !'],['Teacher','A','Great! Now "daughter" — no "th" here. "Dau-ter."','Super ! Maintenant "daughter" — pas de "th" ici. "Do-ter".'],['Student','B','Daughter. And "nephew" — "ne-fiu"?','Daughter. Et "nephew" — "ne-fiou" ?']],
  [['Daughter','/ˈdɔːtər/','Fille','Le "au" = "o" long ouvert : "do-ter". Pas de "l" !'],['Husband','/ˈhʌzbənd/','Mari','Le "u" = "o" ouvert : "heuz-band".'],['Nephew','/ˈnefjuː/','Neveu','Le "ph" = "f" : "ne-fiou".'],['Niece','/niːs/','Nièce','Le "ie" = "ii" long : "niis".']]
),

// ═══ Unit 6: Daily Routine ═══
'a1-l26': lc( // Morning Routine (vocabulary)
  [['Wake up','Se réveiller','/weɪk ʌp/','I wake up at 7 AM.','Je me réveille à 7h.'],['Brush teeth','Se brosser les dents','/brʌʃ tiːθ/','I brush my teeth after breakfast.','Je me brosse les dents après le petit-déjeuner.'],['Shower','Douche','/ˈʃaʊər/','I take a shower every morning.','Je prends une douche chaque matin.'],['Get dressed','S\'habiller','/ɡet drest/','She gets dressed quickly.','Elle s\'habille vite.']],
  'Daily Routine Verbs','Les verbes de routine au Present Simple : "I wake up" (je me réveille), "I brush" (je brosse), "I take" (je prends), "I get dressed" (je m\'habille). Avec he/she/it : "She wakes up", "He brushes", "She takes", "He gets dressed".',
  [{s:'I wake up at seven.',t:'Je me réveille à sept heures.',c:true},{s:'She brush her teeth.',t:'',c:false},{s:'He takes a shower.',t:'Il prend une douche.',c:true},{s:'They get dressed quickly.',t:'Ils s\'habillent vite.',c:true}],
  [{w:'She brush her teeth.',cr:'She brushes her teeth.',e:'Avec he/she/it, on ajoute -es après -ch : brush→brushes.'},{w:'He wake up early.',cr:'He wakes up early.',e:'Avec he/she/it : wake→wakes.']],
  [['Emma','A','What time do you wake up?','À quelle heure te réveilles-tu ?'],['Lucas','B','I usually wake up at 6:30. Then I take a shower.','Je me réveille habituellement à 6h30. Ensuite je prends une douche.'],['Emma','A','Do you brush your teeth before or after breakfast?','Te brosses-tu les dents avant ou après le petit-déjeuner ?'],['Lucas','B','After breakfast! Then I get dressed and leave at 8.','Après le petit-déjeuner ! Puis je m\'habille et je pars à 8h.'],['Emma','A','I wake up at 7. I always take a cold shower!','Je me réveille à 7h. Je prends toujours une douche froide !'],['Lucas','B','A cold shower?! That\'s brave! I prefer hot showers.','Une douche froide ?! C\'est courageux ! Je préfère les douches chaudes.']],
  [['Wake up','/weɪk ʌp/','Se réveiller','Le "w" initial : arrondissez les lèvres. "Ouék-ap".'],['Brush','/brʌʃ/','Brosser','Le "u" est ouvert : "breuch".'],['Shower','/ˈʃaʊər/','Douche','Le "sh" = "ch" français : "cha-er".'],['Dressed','/drest/','Habillé','Prononcez "drest" — un seul "e" et pas de "é" à la fin.']]
),
'a1-l27': lc( // Present Simple (grammar)
  [['Works','Travaille','/wɜːrks/','She works in a hospital.','Elle travaille dans un hôpital.'],['Studies','Étudie','/ˈstʌdiz/','He studies English.','Il étudie l\'anglais.'],['Goes','Va','/ɡoʊz/','She goes to school.','Elle va à l\'école.'],['Watches','Regarde','/ˈwɒtʃɪz/','He watches TV.','Il regarde la télé.']],
  'Present Simple — Spelling Rules','Règles d\'orthographe à la 3e personne : Verbe + s (works, plays). Après s/ss/sh/ch/x/o : + es (goes, watches, fixes). Consonne + y : y→i+es (study→studies, carry→carries). Voyelle + y : + s (plays, says).',
  [{s:'She works every day.',t:'Elle travaille chaque jour.',c:true},{s:'He studys English.',t:'',c:false},{s:'He watches TV.',t:'Il regarde la télé.',c:true},{s:'She go to work.',t:'',c:false}],
  [{w:'He studys English.',cr:'He studies English.',e:'Après consonne+y : y→i+es : study→studies.'},{w:'She go to work.',cr:'She goes to work.',e:'Après "o", on ajoute -es : go→goes.']],
  [['Teacher','A','What does your sister do?','Que fait ta sœur ?'],['Student','B','She studies medicine. She goes to university.','Elle étudie la médecine. Elle va à l\'université.'],['Teacher','A','And your brother? Does he work?','Et ton frère ? Travaille-t-il ?'],['Student','B','Yes, he works in a bank. He watches the stock market.','Oui, il travaille dans une banque. Il surveille la bourse.'],['Teacher','A','Interesting! What do your parents do?','Intéressant ! Que font tes parents ?'],['Student','B','My mother teaches French. My father fixes computers.','Ma mère enseigne le français. Mon père répare les ordinateurs.']],
  [['Works','/wɜːrks/','Travaille','Le "or" = "eur" : "oueurks".'],['Studies','/ˈstʌdiz/','Étudie','Le "u" est ouvert : "steu-diz".'],['Goes','/ɡoʊz/','Va','Prononcez "go-z" avec le "z" sonore.'],['Watches','/ˈwɒtʃɪz/','Regarde','Le "tch" + "iz" : "ouot-chiz".']]
),
'a1-l28': lc( // A Typical Day (conversation)
  [['Commute','Trajet travail','/kəˈmjuːt/','My commute is 30 minutes.','Mon trajet est de 30 minutes.'],['Lunch break','Pause déjeuner','/lʌntʃ breɪk/','I take a lunch break at noon.','Je prends une pause déjeuner à midi.'],['Gym','Salle de sport','/dʒɪm/','She goes to the gym after work.','Elle va à la salle après le travail.'],['Bedtime','Heure de coucher','/ˈbedtaɪm/','My bedtime is 10 PM.','Mon heure de coucher est 22h.']],
  'Talking About Daily Schedules','Pour parler de son emploi du temps : "I start work at..." (Je commence à...), "I finish at..." (Je finis à...), "I have lunch at..." (Je déjeune à...). "Before" (avant) et "after" (après) pour l\'ordre : "After work, I go to the gym."',
  [{s:'I start work at 9 AM.',t:'Je commence le travail à 9h.',c:true},{s:'After work I go to gym.',t:'',c:false},{s:'She has lunch at noon.',t:'Elle déjeune à midi.',c:true},{s:'My bedtime is at 10.',t:'Mon heure de coucher est 22h.',c:true}],
  [{w:'After work I go to gym.',cr:'After work, I go to the gym.',e:'On dit "go to THE gym" avec l\'article "the".',{w:'I have lunch on noon.',cr:'I have lunch at noon.',e:'Avec les heures, on utilise "at", pas "on".']],
  [['Julie','A','What\'s your typical day like?','Comment est ta journée type ?'],['Mark','B','I wake up at 7, commute to work by 8:30. Start at 9.','Je me lève à 7h, trajet pour être au travail à 8h30. Je commence à 9h.'],['Julie','A','When do you take your lunch break?','Quand prends-tu ta pause déjeuner ?'],['Mark','B','At noon. After work, I go to the gym. Then dinner at 7.','À midi. Après le travail, je vais à la salle. Puis dîner à 19h.'],['Julie','A','That\'s a busy schedule! What\'s your bedtime?','C\'est un emploi du temps chargé ! Quelle est ton heure de coucher ?'],['Mark','B','My bedtime is around 10:30. Before bed, I read for 30 minutes.','Mon coucher est vers 22h30. Avant de dormir, je lis pendant 30 minutes.']],
  [['Commute','/kəˈmjuːt/','Trajet','Prononcez "ke-miou-t" — l\'accent est sur "mute".'],['Break','/breɪk/','Pause','Le "ea" = "éï" : "bréïk".'],['Gym','/dʒɪm/','Salle de sport','Le "g" = "dj" : "djim".'],['Bedtime','/ˈbedtaɪm/','Heure de coucher','Prononcez "béd-taïm".']]
),
'a1-l29': lc( // Time Expressions (vocabulary)
  [['Always','Toujours','/ˈɔːlweɪz/','I always brush my teeth.','Je me brosse toujours les dents.'],['Usually','Habituellement','/ˈjuːʒuəli/','She usually wakes up early.','Elle se lève habituellement tôt.'],['Sometimes','Parfois','/ˈsʌmtaɪmz/','I sometimes walk to work.','Je marche parfois au travail.'],['Never','Jamais','/ˈnevər/','He never eats breakfast.','Il ne prend jamais le petit-déjeuner.']],
  'Adverbs of Frequency','Les adverbes de fréquence : always (100%), usually (80%), often (60%), sometimes (40%), rarely (20%), never (0%). Placement : APRÈS le verbe "be" (I am always late) mais AVANT les autres verbes (I always eat breakfast).',
  [{s:'I always eat breakfast.',t:'Je prends toujours le petit-déjeuner.',c:true},{s:'She is never late.',t:'Elle n\'est jamais en retard.',c:true},{s:'I am always eat breakfast.',t:'',c:false},{s:'He never watches TV.',t:'Il ne regarde jamais la télé.',c:true}],
  [{w:'I am always eat breakfast.',cr:'I always eat breakfast.',e:'L\'adverbe se place APRÈS "be" mais AVANT les autres verbes. "Eat" n\'est pas "be".',{w:'She always is happy.',cr:'She is always happy.',e:'Après "be", l\'adverbe vient APRÈS : "is always", pas "always is".']],
  [['Sam','A','Do you always wake up early?','Te réveilles-tu toujours tôt ?'],['Nina','B','Usually, yes. But sometimes I sleep late on weekends.','Habituellement, oui. Mais parfois je dors tard le week-end.'],['Sam','A','I never sleep late. I always go to the gym at 7.','Je ne dors jamais tard. Je vais toujours à la salle à 7h.'],['Nina','B','Wow! I rarely exercise in the morning. Usually in the evening.','Wow ! Je fais rarement du sport le matin. Habituellement le soir.'],['Sam','A','My sister is always tired. She sometimes stays up very late.','Ma sœur est toujours fatiguée. Elle veille parfois très tard.'],['Nina','B','She should never drink coffee after 6 PM!','Elle ne devrait jamais boire de café après 18h !']],
  [['Always','/ˈɔːlweɪz/','Toujours','Prononcez "ol-ouéz" — le "l" est sombre.'],['Usually','/ˈjuːʒuəli/','Habituellement','Le "s" = son "j" : "iou-jou-a-li".'],['Sometimes','/ˈsʌmtaɪmz/','Parfois','Le "u" est ouvert : "seum-taïmz".'],['Never','/ˈnevər/','Jamais','Le premier "e" est fermé : "né-ver".']]
),
'a1-l30': lc( // Routine Verbs Sounds (pronunciation)
  [['Walked','Marché','/wɔːkt/','She walked to work.','Elle a marché au travail.'],['Played','Joué','/pleɪd/','We played football.','Nous avons joué au football.'],['Washed','Lavé','/wɒʃt/','He washed the car.','Il a lavé la voiture.'],['Listened','Écouté','/ˈlɪsnd/','I listened to music.','J\'ai écouté de la musique.']],
  'The -ed Ending Pronunciation','Trois prononciations pour -ed : 1) /t/ après les sons sourds (p, k, f, sh, ch) : walked→"wokt", washed→"wosht". 2) /d/ après les sons sonores (b, g, v, m, n, l, voyelles) : played→"pleid", listened→"lisnd". 3) /ɪd/ après t ou d : wanted→"wantid", needed→"nidid".',
  [{s:'Walked → /wɔːkt/',t:'Marché → son "t"',c:true},{s:'Played → /pleɪt/',t:'',c:false},{s:'Washed → /wɒʃt/',t:'Lavé → son "t"',c:true},{s:'Needed → /ˈniːdɪd/',t:'Nécessité → son "id"',c:true}],
  [{w:'Played → /pleɪt/',cr:'Played → /pleɪd/',e:'Après un son sonore (voyelle "ei"), -ed se prononce /d/ : "pleid".',{w:'Wanted → /wɒːnt/',cr:'Wanted → /ˈwɒntɪd/',e:'Après "t", -ed se prononce /ɪd/ : "wan-tid".']],
  [['Teacher','A','How do you pronounce "walked"?','Comment prononcez-vous "walked" ?'],['Student','B','Wokt. The -ed sounds like "t".','Ouokt. Le -ed sonne comme "t".'],['Teacher','A','Correct! And "played"?','Correct ! Et "played" ?'],['Student','B','Pleid. The -ed sounds like "d" because "play" ends with a vowel.','Pléïd. Le -ed sonne comme "d" car "play" finit par une voyelle.'],['Teacher','A','Excellent! And "listened"?','Excellent ! Et "listened" ?'],['Student','B','Lisnd. The "e" in -ed is silent. It sounds like "d".','Lisnd. Le "e" de -ed est muet. Ça sonne comme "d".']],
  [['Walked','/wɔːkt/','Marché','Le -ed = "t" car "k" est sourd : "ouokt".'],['Played','/pleɪd/','Joué','Le -ed = "d" car la voyelle est sonore : "pléïd".'],['Washed','/wɒʃt/','Lavé','Le -ed = "t" car "sh" est sourd : "oucht".'],['Listened','/ˈlɪsnd/','Écouté','Le -ed = "d" car "n" est sonore : "lisn-d".']]
),

// ═══ Unit 7: Around the House ═══
'a1-l31': lc( // Rooms in a House (vocabulary)
  [['Kitchen','Cuisine','/ˈkɪtʃɪn/','The kitchen is very big.','La cuisine est très grande.'],['Bedroom','Chambre','/ˈbedruːm/','My bedroom is upstairs.','Ma chambre est à l\'étage.'],['Bathroom','Salle de bain','/ˈbæθruːm/','The bathroom is on the left.','La salle de bain est à gauche.'],['Living room','Salon','/ˈlɪvɪŋ ruːm/','We watch TV in the living room.','Nous regardons la télé dans le salon.']],
  'Rooms & Prepositions','Les pièces de la maison : kitchen (cuisine), bedroom (chambre), bathroom (salle de bain), living room (salon), dining room (salle à manger), hallway (couloir). Prépositions : "upstairs" (en haut), "downstairs" (en bas), "on the left/right" (à gauche/droite).',
  [{s:'The kitchen is downstairs.',t:'La cuisine est en bas.',c:true},{s:'My bedroom are upstairs.',t:'',c:false},{s:'The bathroom is on the right.',t:'La salle de bain est à droite.',c:true},{s:'We eat in the living room.',t:'',c:false}],
  [{w:'My bedroom are upstairs.',cr:'My bedroom is upstairs.',e:'"Bedroom" est singulier → "is", pas "are".',{w:'We eat in the living room.',cr:'We eat in the dining room / kitchen.',e:'On mange dans la "dining room" ou "kitchen", pas le "living room".']],
  [['Julie','A','Is there a kitchen in your apartment?','Y a-t-il une cuisine dans ton appartement ?'],['Mark','B','Yes, there is. The kitchen is downstairs.','Oui. La cuisine est en bas.'],['Julie','A','How many bedrooms are there?','Combien de chambres y a-t-il ?'],['Mark','B','There are two bedrooms and one bathroom upstairs.','Il y a deux chambres et une salle de bain en haut.'],['Julie','A','Is the living room big?','Le salon est-il grand ?'],['Mark','B','Yes, the living room is on the left, next to the dining room.','Oui, le salon est à gauche, à côté de la salle à manger.']],
  [['Kitchen','/ˈkɪtʃɪn/','Cuisine','Le "ch" = "tch" : "kit-chin".'],['Bedroom','/ˈbedruːm/','Chambre','Prononcez "béd-roum" — le "d" et le "r" se lient.'],['Bathroom','/ˈbæθruːm/','Salle de bain','Le "th" est expiré : "bath-roum".'],['Living room','/ˈlɪvɪŋ ruːm/','Salon','Le "i" est court : "li-ving roum".']]
),
'a1-l32': lc( // Furniture & Appliances (vocabulary)
  [['Sofa','Canapé','/ˈsoʊfə/','Sit on the sofa, please.','Asseyez-vous sur le canapé.'],['Bed','Lit','/bed/','The bed is very comfortable.','Le lit est très confortable.'],['Fridge','Frigo','/frɪdʒ/','Put the milk in the fridge.','Mets le lait dans le frigo.'],['Television','Télévision','/ˈtelɪvɪʒn/','Turn on the television.','Allume la télé.']],
  'Describing Furniture — Adjectives','Pour décrire les meubles : "big" (grand), "small" (petit), "comfortable" (confortable), "new" (nouveau), "old" (vieux/ancien), "modern" (moderne), "wooden" (en bois), "soft" (doux). Position : "The sofa is in front of the TV."',
  [{s:'The bed is very comfortable.',t:'Le lit est très confortable.',c:true},{s:'She has a wooden table.',t:'Elle a une table en bois.',c:true},{s:'The sofa are very soft.',t:'',c:false},{s:'The fridge is new.',t:'Le frigo est neuf.',c:true}],
  [{w:'The sofa are very soft.',cr:'The sofa is very soft.',e:'"Sofa" est singulier → "is", pas "are".',{w:'The bed are comfortable.',cr:'The bed is comfortable.',e:'"Bed" est singulier → "is".']],
  [['Anna','A','Your apartment is nice! I love that sofa.','Ton appart est sympa ! J\'adore ce canapé.'],['Paul','B','Thanks! It\'s very comfortable. And it\'s new.','Merci ! Il est très confortable. Et il est neuf.'],['Anna','A','Is the fridge old?','Le frigo est vieux ?'],['Paul','B','No, the fridge is modern. It\'s a big fridge.','Non, le frigo est moderne. C\'est un grand frigo.'],['Anna','A','What about the bed? Is it soft?','Et le lit ? Il est doux ?'],['Paul','B','Yes, the bed is very soft. It\'s a wooden bed frame.','Oui, le lit est très doux. C\'est un cadre en bois.']],
  [['Sofa','/ˈsoʊfə/','Canapé','Le "o" est long : "so-fa" avec le "a" réduit.'],['Bed','/bed/','Lit','Le "e" est ouvert : "bède".'],['Fridge','/frɪdʒ/','Frigo','Le "i" est court et le "dge" = "dj" : "frij-dj".'],['Television','/ˈtelɪvɪʒn/','Télévision','L\'accent sur "tel" : "TÉ-li-vi-jon".']]
),
'a1-l33': lc( // There is / There are (grammar)
  [['There is','Il y a','/ðer ɪz/','There is a sofa here.','Il y a un canapé ici.'],['There are','Il y a (pluriel)','/ðer ɑːr/','There are three chairs.','Il y a trois chaises.'],['Is there','Y a-t-il','/ɪz ðer/','Is there a kitchen?','Y a-t-il une cuisine ?'],['Are there','Y a-t-il (pl.)','/ɑːr ðer/','Are there any windows?','Y a-t-il des fenêtres ?']],
  'There is vs There are',"There is" + singulier : "There is a table." "There are" + pluriel : "There are two beds." Négatif : "There isn\'t a..." / "There aren\'t any..." Questions : "Is there a...?" / "Are there any...?" Attention : "There is" + liste commence par singulier : "There is a sofa and two chairs."',
  [{s:'There is a sofa in the living room.',t:'Il y a un canapé dans le salon.',c:true},{s:'There are three bedrooms.',t:'Il y a trois chambres.',c:true},{s:'There is two bathrooms.',t:'',c:false},{s:'Is there a kitchen?',t:'Y a-t-il une cuisine ?',c:true}],
  [{w:'There is two chairs.',cr:'There are two chairs.',e:'Avec un pluriel (two chairs), on utilise "there are".',{w:'There are a table.',cr:'There is a table.',e:'Avec un singulier (a table), on utilise "there is".']],
  [['Julie','A','Tell me about your house. Is there a garden?','Parle-moi de ta maison. Y a-t-il un jardin ?'],['Mark','B','Yes, there is a small garden. There are many flowers.','Oui, il y a un petit jardin. Il y a beaucoup de fleurs.'],['Julie','A','Are there any trees?','Y a-t-il des arbres ?'],['Mark','B','No, there aren\'t any trees. But there is a nice fence.','Non, il n\'y a pas d\'arbres. Mais il y a une jolie clôture.'],['Julie','A','How many rooms are there?','Combien de pièces y a-t-il ?'],['Mark','B','There are five rooms. There is a big kitchen and two bathrooms.','Il y a cinq pièces. Il y a une grande cuisine et deux salles de bain.']],
  [['There is','/ðer ɪz/','Il y a','Prononcez "dér-iz" — le "th" est sonore.'],['There are','/ðer ɑːr/','Il y a (pl.)','Prononcez "dér-ar" — lier les deux mots.'],['Isn\'t','/ˈɪzənt/','N\'y a pas','Prononcez "iz-ent".'],['Aren\'t','/ɑːrnt/','N\'y a pas (pl.)','Prononcez "ar-nt" — le "t" est léger.']]
),
'a1-l34': lc( // My Home (conversation)
  [['Rent','Loyer','/rent/','The rent is 800 dollars.','Le loyer est de 800 dollars.'],['Apartment','Appartement','/əˈpɑːrtmənt/','I live in an apartment.','Je vis dans un appartement.'],['Garden','Jardin','/ˈɡɑːrdən/','The garden is beautiful.','Le jardin est beau.'],['Neighbor','Voisin','/ˈneɪbər/','My neighbor is very friendly.','Mon voisin est très sympa.']],
  'Describing Your Home','Pour décrire son logement : "I live in a/an..." (Je vis dans...), "It has..." (Il/Elle a...), "There is/are..." (Il y a...). Types : apartment (appartement), house (maison), studio (studio), flat (appartement — britannique).',
  [{s:'I live in an apartment.',t:'Je vis dans un appartement.',c:true},{s:'It have three rooms.',t:'',c:false},{s:'The rent is 500 dollars.',t:'Le loyer est de 500 dollars.',c:true},{s:'My neighbor are friendly.',t:'',c:false}],
  [{w:'It have three rooms.',cr:'It has three rooms.',e:'Avec "it", on utilise "has" pas "have".',{w:'My neighbor are friendly.',cr:'My neighbor is friendly. / My neighbors are friendly.',e:'Singulier : neighbor → is. Pluriel : neighbors → are.']],
  [['Lucie','A','Do you live in a house or an apartment?','Tu vis dans une maison ou un appartement ?'],['Kevin','B','I live in an apartment. The rent is 750 dollars a month.','Je vis dans un appartement. Le loyer est de 750 dollars par mois.'],['Lucie','A','That\'s reasonable! How many rooms are there?','C\'est raisonnable ! Combien de pièces y a-t-il ?'],['Kevin','B','There are four rooms. It has a small garden too.','Il y a quatre pièces. Il a aussi un petit jardin.'],['Lucie','A','A garden in an apartment? That\'s nice! Are your neighbors friendly?','Un jardin dans un appart ? C\'est sympa ! Tes voisins sont sympas ?'],['Kevin','B','Yes, my neighbor on the left is very nice. She has a cat!','Oui, ma voisine à gauche est très gentille. Elle a un chat !']],
  [['Rent','/rent/','Loyer','Le "e" est ouvert : "rènt".'],['Apartment','/əˈpɑːrtmənt/','Appartement','L\'accent sur "part" : "a-PART-ment".'],['Garden','/ˈɡɑːrdən/','Jardin','Le "ar" = "ar" : "gar-den".'],['Neighbor','/ˈneɪbər/','Voisin','Le "ei" = "éï" : "néï-ber".']]
),
'a1-l35': lc( // House Words Sounds (pronunciation)
  [['Cupboard','Placard','/ˈkʌbərd/','The cups are in the cupboard.','Les tasses sont dans le placard.'],['Ceiling','Plafond','/ˈsiːlɪŋ/','The ceiling is very high.','Le plafond est très haut.'],['Curtain','Rideau','/ˈkɜːrtn/','Open the curtains.','Ouvre les rideaux.'],['Drawer','Tiroir','/drɔːr/','Put it in the drawer.','Mets-le dans le tiroir.']],
  'Silent Letters in House Words','Lettres muettes dans les mots de la maison : "cupboard" → le "p" est muet : "cuberd". "Curtain" → le "n" final est très léger. "Drawer" → ne dites PAS "draw-er" mais "dror". "Ceiling" → le "ei" = "ii" long.',
  [{s:'Cupboard → /ˈkʌbərd/',t:'Placard → "p" muet',c:true},{s:'Ceiling → /ˈkeɪlɪŋ/',t:'',c:false},{s:'Curtain → /ˈkɜːrtn/',t:'Rideau → "n" léger',c:true},{s:'Drawer → /drɔːr/',t:'Tiroir → un seul son "or"',c:true}],
  [{w:'Ceiling → /ˈkeɪlɪŋ/',cr:'Ceiling → /ˈsiːlɪŋ/',e:'Le "ei" dans "ceiling" = "ii" long : "sii-ling", pas "kéï-ling".',{w:'Cupboard → /ˈkʌpbɔːrd/',cr:'Cupboard → /ˈkʌbərd/',e:'Le "p" est muet dans "cupboard" : "cuberd".']],
  [['Tom','A','Where are the plates?','Où sont les assiettes ?'],['Lisa','B','In the cupboard, above the sink.','Dans le placard, au-dessus de l\'évier.'],['Tom','A','I can\'t reach! The ceiling is too high in this kitchen!','Je n\'atteins pas ! Le plafond est trop haut dans cette cuisine !'],['Lisa','B','Use the step stool. And close the curtains, the sun is strong.','Utilise l\'escabeau. Et ferme les rideaux, le soleil est fort.'],['Tom','A','Good idea. Where should I put the keys?','Bonne idée. Où dois-je mettre les clés ?'],['Lisa','B','In the top drawer, next to the window.','Dans le tiroir du haut, à côté de la fenêtre.']],
  [['Cupboard','/ˈkʌbərd/','Placard','Le "p" est MUET : "keu-berd".'],['Ceiling','/ˈsiːlɪŋ/','Plafond','Le "ei" = "ii" long : "sii-ling".'],['Curtain','/ˈkɜːrtn/','Rideau','L\'accent sur "cur" : "ker-tn".'],['Drawer','/drɔːr/','Tiroir','Prononcez "dror" — une seule syllabe, pas "dro-ouer".']]
),

// ═══ Unit 8: At the Store ═══
'a1-l36': lc( // Shopping Vocabulary (vocabulary)
  [['Buy','Acheter','/baɪ/','I want to buy a shirt.','Je veux acheter une chemise.'],['Sell','Vendre','/sel/','They sell shoes here.','Ils vendent des chaussures ici.'],['Price','Prix','/praɪs/','What is the price?','Quel est le prix ?'],['Cheap','Bon marché','/tʃiːp/','This is very cheap!','C\'est très bon marché !']],
  'Money & Shopping Vocabulary','Argent et shopping : "How much is it?" (Combien ça coûte ?), "It costs..." (Ça coûte...), "sale" (soldes/promotion), "discount" (réduction), "receipt" (reçu/ticket), "cash" (espèces), "credit card" (carte de crédit).',
  [{s:'How much does it cost?',t:'Combien ça coûte ?',c:true},{s:'It is on sale.',t:'C\'est en promotion.',c:true},{s:'How many does it cost?',t:'',c:false},{s:'Can I pay by credit card?',t:'Puis-je payer par carte ?',c:true}],
  [{w:'How many does it cost?',cr:'How much does it cost?',e:'Pour le prix, on utilise "how much" (indénombrable), pas "how many".',{w:'It is in sale.',cr:'It is on sale.',e:'On dit "on sale" (en promotion), pas "in sale".']],
  [['Customer','A','Excuse me, how much does this cost?','Excusez-moi, combien ça coûte ?'],['Seller','B','It\'s twenty dollars. It\'s on sale this week!','C\'est vingt dollars. C\'est en promo cette semaine !'],['Customer','A','That\'s cheap! Do you sell bags too?','C\'est bon marché ! Vendez-vous aussi des sacs ?'],['Seller','B','Yes, we sell bags. The price starts at fifteen dollars.','Oui, nous vendons des sacs. Le prix commence à quinze dollars.'],['Customer','A','Great! I want to buy this shirt and a bag.','Super ! Je veux acheter cette chemise et un sac.'],['Seller','B','Would you like a receipt? Cash or credit card?','Voulez-vous un reçu ? Espèces ou carte ?']],
  [['Buy','/baɪ/','Acheter','Le "u" après "b" = son "aï" : "baï".'],['Sell','/sel/','Vendre','Le "e" est ouvert : "sèle".'],['Price','/praɪs/','Prix','Le "i" est long : "praïs" — ne dites pas "prize".'],['Cheap','/tʃiːp/','Bon marché','Le "ch" = "tch" et "ea" = "ii" : "tchii-p".']]
),
'a1-l37': lc( // How Much Is It? (conversation)
  [['Dollar','Dollar','/ˈdɒlər/','It costs five dollars.','Ça coûte cinq dollars.'],['Cent','Cent','/sent/','It\'s ninety-nine cents.','Ça fait quatre-vingt-dix-neuf cents.'],['Discount','Réduction','/ˈdɪskaʊnt/','I have a discount code.','J\'ai un code de réduction.'],['Sale','Solde/Promo','/seɪl/','The sale starts today.','Les soldes commencent aujourd\'hui.']],
  'Asking About Prices','Pour demander le prix : "How much is this?" (Combien ça coûte ?), "How much are these?" (Combien coûtent ceux-ci ?), "What\'s the price?" (Quel est le prix ?). Réponses : "It\'s [prix]" (C\'est [prix]), "They\'re [prix]" (Ils/Elles sont [prix]).',
  [{s:'How much is this shirt?',t:'Combien coûte cette chemise ?',c:true},{s:'How much are these shoes?',t:'Combien coûtent ces chaussures ?',c:true},{s:'What is the price of this?',t:'Quel est le prix de ceci ?',c:true},{s:'It cost twenty dollars.',t:'',c:false}],
  [{w:'It cost twenty dollars.',cr:'It costs twenty dollars.',e:'Avec "it", on utilise "costs" (3e personne), pas "cost".',{w:'How many is this?',cr:'How much is this?',e:'Pour le prix, on utilise "how much", pas "how many".']],
  [['Nadia','A','Excuse me, how much is this dress?','Excusez-moi, combien coûte cette robe ?'],['Clerk','B','It\'s forty-five dollars. But we have a discount — 20% off!','C\'est quarante-cinq dollars. Mais nous avons une réduction — 20% !'],['Nadia','A','That\'s a good sale! How much are these shoes?','C\'est une bonne promo ! Combien coûtent ces chaussures ?'],['Clerk','B','They\'re thirty dollars. Originally fifty — they\'re on sale.','Elles sont trente dollars. Cinquante à l\'origine — elles sont en solde.'],['Nadia','A','So the total would be...?','Donc le total serait... ?'],['Clerk','B','The dress is thirty-six dollars with the discount. Plus the shoes, sixty-six dollars total.','La robe est trente-six dollars avec la réduction. Plus les chaussures, soixante-six dollars en tout.']],
  [['Dollar','/ˈdɒlər/','Dollar','Prononcez "dol-er" — le "o" est ouvert.'],['Cent','/sent/','Cent','Le "e" est fermé : "sènt".'],['Discount','/ˈdɪskaʊnt/','Réduction','L\'accent sur "count" : "dis-KAOUNT".'],['Sale','/seɪl/','Solde/Promo','Le "ai" = "éï" : "séïl".']]
),
'a1-l38': lc( // Can I Have...? (grammar)
  [['Can I','Puis-je','/kæn aɪ/','Can I have a bag?','Puis-je avoir un sac ?'],['Would like','Voudrais','/wʊd laɪk/','I would like some water.','Je voudrais de l\'eau.'],['Could I','Pourrais-je','/kʊd aɪ/','Could I try this on?','Pourrais-je essayer ceci ?'],['May I','Puis-je (formel)','/meɪ aɪ/','May I help you?','Puis-je vous aider ?']],
  'Polite Requests — Can / Could / Would / May','Du moins poli au plus poli : "I want" (je veux — impoli), "Can I have...?" (Puis-je avoir...?), "I would like..." (Je voudrais...), "Could I have...?" (Pourrais-je avoir...?), "May I...?" (Puis-je...? — très formel). Toujours ajouter "please" !',
  [{s:'I would like a coffee, please.',t:'Je voudrais un café, s\'il vous plaît.',c:true},{s:'Give me some water.',t:'',c:false},{s:'Could I try this on?',t:'Pourrais-je essayer ceci ?',c:true},{s:'Can I have the bill, please?',t:'Puis-je avoir l\'addition, s\'il vous plaît ?',c:true}],
  [{w:'Give me some water.',cr:'Could I have some water, please?',e:'"Give me" est impoli. Utilisez "Could I have" + "please".',{w:'I want a coffee.',cr:'I would like a coffee, please.',e:'"I want" est trop direct. "I would like" est plus poli.']],
  [['Nadia','A','Excuse me, can I have this shirt in size M?','Excusez-moi, puis-je avoir cette chemise en taille M ?'],['Clerk','B','Of course! Would you like to try it on?','Bien sûr ! Voudriez-vous l\'essayer ?'],['Nadia','A','Yes, could I try it on? Where is the fitting room?','Oui, pourrais-je l\'essayer ? Où est la cabine d\'essayage ?'],['Clerk','B','It\'s on the right. May I help you with anything else?','C\'est à droite. Puis-je vous aider avec autre chose ?'],['Nadia','A','I would like to see the blue one too, please.','Je voudrais voir la bleue aussi, s\'il vous plaît.'],['Clerk','B','Sure! Here it is. Can I get you a different size?','Bien sûr ! La voici. Puis-je vous apporter une autre taille ?']],
  [['Can','/kæn/','Pouvoir','Le "a" est ouvert : "kan" — souvent réduit à "ken" en conversation.'],['Would','/wʊd/','Voudrais','Le "ou" = "ou" court : "ououd".'],['Could','/kʊd/','Pourrais','Le "ou" = "ou" court : "koud".'],['May','/meɪ/','Pouvoir (formel)','Le "ay" = "éï" : "méï".']]
),
'a1-l39': lc( // Colors & Sizes (vocabulary)
  [['Red','Rouge','/red/','I like the red dress.','J\'aime la robe rouge.'],['Blue','Bleu','/bluː/','The sky is blue.','Le ciel est bleu.'],['Small','Petit','/smɔːl/','I need a small size.','J\'ai besoin d\'une petite taille.'],['Large','Grand','/lɑːrdʒ/','Do you have this in large?','Avez-vous ceci en grand ?']],
  'Colors & Sizes in English','Couleurs : red (rouge), blue (bleu), green (vert), yellow (jaune), black (noir), white (blanc), orange (orange), pink (rose), purple (violet), brown (marron), grey/gray (gris). Tailles : XS (extra small), S (small), M (medium), L (large), XL (extra large).',
  [{s:'The red bag is beautiful.',t:'Le sac rouge est beau.',c:true},{s:'She wears a blue shoes.',t:'',c:false},{s:'I need a medium size.',t:'J\'ai besoin d\'une taille moyenne.',c:true},{s:'Do you have this in large?',t:'Avez-vous ceci en grand ?',c:true}],
  [{w:'She wears a blue shoes.',cr:'She wears blue shoes.',e:'"Shoes" est pluriel, pas besoin de "a" devant un adjectif pluriel.'},{w:'The reds bag.',cr:'The red bag.',e:'L\'adjectif ne prend pas de "s" en anglais : "red bag", pas "reds bag".']],
  [['Customer','A','Do you have this shirt in blue?','Avez-vous cette chemise en bleu ?'],['Seller','B','Yes, we have blue, red, and white. What size?','Oui, nous avons bleu, rouge et blanc. Quelle taille ?'],['Customer','A','Small, please. I usually wear a small.','Petit, s\'il vous plaît. Je porte généralement du S.'],['Seller','B','Here\'s the small. Would you like to try the medium too?','Voici le S. Voulez-vous essayer le M aussi ?'],['Customer','A','Yes, I\'ll take both. The blue in small and the red in medium.','Oui, je prends les deux. Le bleu en S et le rouge en M.'],['Seller','B','Great choice! The large is also available in black if you\'re interested.','Beau choix ! Le L est aussi disponible en noir si ça vous intéresse.']],
  [['Red','/red/','Rouge','Le "e" est ouvert : "rède".'],['Blue','/bluː/','Bleu','Le "ue" = "ou" long : "blou".'],['Small','/smɔːl/','Petit','Le "aw" = "o" ouvert : "smol".'],['Large','/lɑːrdʒ/','Grand','Le "ar" = "ar" et "ge" = "dj" : "lard-j".']]
),
'a1-l40': lc( // Shopping Sounds (pronunciation)
  [['Shopping','Shopping','/ˈʃɒpɪŋ/','I go shopping on Saturdays.','Je fais du shopping le samedi.'],['Receipt','Reçu','/rɪˈsiːt/','Keep your receipt.','Gardez votre reçu.'],['Bargain','Bonne affaire','/ˈbɑːrɡən/','This is a real bargain!','C\'est une vraie bonne affaire !'],['Customer','Client','/ˈkʌstəmər/','The customer is always right.','Le client a toujours raison.']],
  'Tricky Shopping Words','Mots de shopping difficiles : "receipt" → le "p" est MUET : "ri-siit" (pas "re-si-pit"). "Shopping" → le "o" est ouvert : "shop-ing". "Bargain" → le "ai" = "i" court : "bar-gin" (pas "bar-gaïn"). "Customer" → l\'accent sur "cus" : "KES-to-mer".',
  [{s:'Receipt → /rɪˈsiːt/',t:'Reçu → "p" muet',c:true},{s:'Bargain → /ˈbɑːrɡaɪn/',t:'',c:false},{s:'Shopping → /ˈʃɒpɪŋ/',t:'Shopping → "o" ouvert',c:true},{s:'Customer → /ˈkʌstəmər/',t:'Client → accent sur "cus"',c:true}],
  [{w:'Bargain → /ˈbɑːrɡaɪn/',cr:'Bargain → /ˈbɑːrɡɪn/',e:'Dans "bargain", le "ai" = "i" court : "bar-gin", pas "bar-gaïn".',{w:'Receipt → /riˈsiːpit/',cr:'Receipt → /rɪˈsiːt/',e:'Le "p" est MUET dans "receipt" : "ri-siit".']],
  [['Sam','A','I love shopping on Saturdays! Do you?','J\'adore le shopping le samedi ! Et toi ?'],['Nina','B','Sometimes! I always check for bargains first.','Parfois ! Je vérifie toujours les bonnes affaires d\'abord.'],['Sam','A','Can I see your receipt? Was it a good deal?','Puis-je voir ton reçu ? C\'était une bonne affaire ?'],['Nina','B','Yes! This jacket was 50% off. A real bargain!','Oui ! Cette veste était à 50%. Une vraie bonne affaire !'],['Sam','A','The customer service here is great too.','Le service client ici est génial aussi.'],['Nina','B','Agreed! The cashier even gave me a discount code for next time.','D\'accord ! La caissière m\'a même donné un code promo pour la prochaine fois.']],
  [['Shopping','/ˈʃɒpɪŋ/','Shopping','Le "o" est ouvert : "cho-ping".'],['Receipt','/rɪˈsiːt/','Reçu','Le "p" est MUET : "ri-siit". Ne dites PAS "re-sip-it" !'],['Bargain','/ˈbɑːrɡɪn/','Bonne affaire','Le "ai" = "i" court : "bar-gin". Pas "bar-gaïn" !'],['Customer','/ˈkʌstəmər/','Client','L\'accent sur "cus" : "KEUS-to-mer".']]
),
}
