import type { LessonContent } from './lesson-content'

// ════════════════════════════════════════════════════════════════════════════════
// C1 ADVANCED — UNIT 9: CULTURAL NUANCES (c1-l41 through c1-l45)
// YOELANG English Learning App for Francophone Users
// Advanced: cultural vocabulary, connotation & pragmatics, cross-cultural talk,
// cultural misunderstandings, cultural/linguistic pronunciation
// ════════════════════════════════════════════════════════════════════════════════

// ─── c1-l41: Cultural Vocabulary ──────────────────────────────────────────────────
export const C1_L41: LessonContent = {
  vocab: [
    { english: 'idiom', french: 'idiome / expression idiomatique', phonetic: '/ˈɪdiəm/', example: 'The idiom « break the ice » has no literal equivalent in French.', exampleTranslation: 'L\'idiome « break the ice » n\'a pas d\'équivalent littéral en français.' },
    { english: 'connotation', french: 'connotation', phonetic: '/ˌkɒnəˈteɪʃn/', example: 'The word « ambitious » carries a positive connotation in English but can be negative in French.', exampleTranslation: 'Le mot « ambitious » porte une connotation positive en anglais mais peut être négatif en français.' },
    { english: 'pragmatics', french: 'pragmatique (linguistique)', phonetic: '/præɡˈmætɪks/', example: 'Pragmatics studies how context influences the interpretation of meaning.', exampleTranslation: 'La pragmatique étudie comment le contexte influence l\'interprétation du sens.' },
    { english: 'register', french: 'registre (de langue)', phonetic: '/ˈredʒɪstər/', example: 'Switching from a formal to an informal register can signal a shift in the relationship.', exampleTranslation: 'Passer d\'un registre formel à un registre informel peut signaler un changement dans la relation.' },
    { english: 'euphemism', french: 'euphémisme', phonetic: '/ˈjuːfəmɪzəm/', example: '« Let go » is a euphemism for « fire » — it softens the impact of bad news.', exampleTranslation: '« Let go » est un euphémisme pour « fire » — il atténue l\'impact d\'une mauvaise nouvelle.' },
  ],
  grammar: {
    title: 'Le vocabulaire culturel anglais : idiomes, connotations et registres',
    explanation: 'La compétence culturelle en anglais va bien au-delà de la grammaire — elle suppose une maîtrise des nuances que les dictionnaires ne capturent pas toujours : (1) « Idiom » ≠ « expression » : un idiom est une expression dont le sens global ne se déduit pas du sens littéral des mots. « Break the ice » ≠ casser la glace (en français, cela signifie détruire quelque chose) ; en anglais, cela signifie lancer la conversation. Les idiomes sont intraductibles mot à mot. (2) « Connotation » = la charge émotive ou culturelle d\'un mot, par opposition à sa « denotation » (sens littéral). Exemple : « ambitious » (connotation positive en anglais = entreprenant) ≠ « ambitieux » (connotation souvent négative en français = prétentieux). De même, « propaganda » est toujours péjoratif en anglais, alors que « propagande » peut être neutre en français. (3) « Register » = le niveau de langue adapté au contexte social. L\'anglais distingue au moins cinq registres : frozen (rituel), formal (soutenu), consultative (courant professionnel), casual (familier), intimate (intime). Les francophones ont du mal car le français fonctionne sur un système similar mais les frontières ne sont pas au même endroit. (4) « Euphemism » = mot ou expression atténuant une réalité déplaisante. L\'anglais est extrêmement riche en euphémismes : « pass away » (mourir), « between jobs » (au chômage), « vertically challenged » (de petite taille), « collateral damage » (victimes civiles). Cette tendance reflète une volonté de « politeness » anglo-saxonne que les francophones trouvent parfois hypocrite.',
    examples: [
      { sentence: 'The idiom « hit the nail on the head » means to describe exactly what is causing a problem.', translation: 'L\'idiome « hit the nail on the head » signifie décrire exactement ce qui cause un problème.', isCorrect: true },
      { sentence: 'She used a euphemism when she said he was « between jobs » instead of unemployed.', translation: 'Elle a utilisé un euphémisme quand elle a dit qu\'il était « between jobs » au lieu de chômeur.', isCorrect: true },
      { sentence: 'The word « propaganda » has a neutral connotation in English.', translation: '', isCorrect: false },
      { sentence: 'Using the appropriate register shows awareness of the social context and relationship.', translation: 'Utiliser le registre approprié montre une conscience du contexte social et de la relation.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'The word « propaganda » has a neutral connotation in English.', correct: 'The word « propaganda » has a strongly negative connotation in English.', explanation: 'En anglais, « propaganda » est toujours péjoratif (= désinformation manipulatrice). En français, « propagande » peut être neutre (= diffusion d\'idées). C\'est un faux ami culturel majeur — utiliser « propaganda » en anglais quand on veut dire « communication » ou « campaign » est une grave erreur.' },
      { wrong: 'He broke the ice by destroying the tension in the room.', correct: 'He broke the ice by making a joke that eased the tension in the room.', explanation: '« Break the ice » en anglais signifie « lancer la conversation / détendre l\'atmosphère », pas « détruire la tension » au sens littéral. C\'est un idiom — le sens figuré est totalement différent du sens littéral. Ne traduisez jamais un idiom mot à mot.' },
    ],
  },
  conversation: [
    { speaker: 'Professor Lahens', role: 'A', text: 'Today we\'re examining how connotations differ across cultures. Take the word « ambitious » — what does it evoke for you?', translation: 'Aujourd\'hui, nous examinons comment les connotations diffèrent selon les cultures. Prenons le mot « ambitious » — qu\'évoque-t-il pour vous ?' },
    { speaker: 'Student Morel', role: 'B', text: 'In French, « ambitieux » often suggests someone who is pushy or self-serving. But I\'ve noticed English speakers use it as a compliment.', translation: 'En français, « ambitieux » suggère souvent quelqu\'un de poussif ou d\'égoïste. Mais j\'ai remarqué que les anglophones l\'utilisent comme un compliment.' },
    { speaker: 'Professor Lahens', role: 'A', text: 'Precisely. That\'s a connotation gap. Similarly, « propaganda » in English is always negative — never use it to mean « public awareness campaign ». What about euphemisms?', translation: 'Précisément. C\'est un décalage de connotation. De même, « propaganda » en anglais est toujours négatif — ne l\'utilisez jamais pour dire « campagne de sensibilisation ». Et les euphémismes ?' },
    { speaker: 'Student Morel', role: 'B', text: 'I find English euphemisms confusing. When someone is « let go », they\'re fired — why not just say it?', translation: 'Je trouve les euphémismes anglais déroutants. Quand quelqu\'un est « let go », il est licencié — pourquoi ne pas le dire directement ?' },
    { speaker: 'Professor Lahens', role: 'A', text: 'Because in Anglo-Saxon culture, directness about negative news is seen as harsh. The register shifts toward euphemism to preserve « face » — a concept we\'ll explore next week.', translation: 'Parce que dans la culture anglo-saxonne, la directivité concernant les mauvaises nouvelles est perçue comme brutale. Le registre bascule vers l\'euphémisme pour préserver la « face » — un concept que nous explorerons la semaine prochaine.' },
    { speaker: 'Student Morel', role: 'B', text: 'So pragmatics is really about reading between the lines — understanding what\'s meant, not just what\'s said.', translation: 'Donc la pragmatique, c\'est vraiment lire entre les lignes — comprendre ce qui est voulu, pas seulement ce qui est dit.' },
  ],
  conversationTitle: 'Connotations culturelles : quand les mots trahissent les valeurs',
  pronunciation: [
    { word: 'Idiom', phonetic: '/ˈɪdiəm/', meaning: 'Idiome', tip: 'L\'accent est sur « ID » : « ID-ee-uhm ». Le « i » est bref comme dans « bit ». Ne dites pas « ee-dyom » à la française. La terminaison « -om » = « uhm ».' },
    { word: 'Connotation', phonetic: '/ˌkɒnəˈteɪʃn/', meaning: 'Connotation', tip: 'L\'accent est sur « TAY » : « kon-uh-TAY-shun ». Le « co » initial est réduit. La terminaison « -tion » = « shun ». Ne dites pas « ko-no-ta-sion ».' },
    { word: 'Pragmatics', phonetic: '/præɡˈmætɪks/', meaning: 'Pragmatique', tip: 'L\'accent est sur « MAT » : « prag-MAT-iks ». Le « a » est ouvert comme dans « cat ». Le « g » est dur. Ne dites pas « pra-gma-tiks » avec l\'accent sur la première syllabe.' },
    { word: 'Euphemism', phonetic: '/ˈjuːfəmɪzəm/', meaning: 'Euphémisme', tip: 'L\'accent est sur « YOU » : « YOU-fuh-miz-uhm ». Le « eu » initial = « you ». Le « ph » = « f ». La terminaison « -ism » = « iz-uhm ». Ne dites pas « eu-fé-misme ».' },
  ],
}

// ─── c1-l42: Connotation & Pragmatics ─────────────────────────────────────────────
export const C1_L42: LessonContent = {
  vocab: [
    { english: 'denotation', french: 'dénotation / sens littéral', phonetic: '/ˌdiːnəˈteɪʃn/', example: 'The denotation of « snake » is a legless reptile; its connotation may be deceit or danger.', exampleTranslation: 'La dénotation de « snake » est un reptile apode ; sa connotation peut être la tromperie ou le danger.' },
    { english: 'implicature', french: 'implicature / sens implicite', phonetic: '/ˈɪmplɪkətʃər/', example: 'When she says « Some students passed », the implicature is that not all did.', exampleTranslation: 'Quand elle dit « Some students passed », l\'implicature est que tous n\'ont pas réussi.' },
    { english: 'to entail', french: 'impliquer / entraîner logiquement', phonetic: '/ɪnˈteɪl/', example: 'Saying « I baked a cake » entails that there is a cake — it logically follows.', exampleTranslation: 'Dire « I baked a cake » implique qu\'il y a un gâteau — cela découle logiquement.' },
    { english: 'presupposition', french: 'présupposition', phonetic: '/ˌpriːsʌpəˈzɪʃn/', example: 'The question « Have you stopped cheating? » carries the presupposition that you once cheated.', exampleTranslation: 'La question « Have you stopped cheating? » porte la présupposition que vous avez autrefois triché.' },
    { english: 'speech act', french: 'acte de langage', phonetic: '/ˈspiːtʃ ækt/', example: 'Saying « I apologise » is a speech act — the utterance itself performs the action.', exampleTranslation: 'Dire « I apologise » est un acte de langage — l\'énoncé lui-même accomplit l\'action.' },
  ],
  grammar: {
    title: 'Connotation et pragmatique : comment les mots portent un bagage culturel',
    explanation: 'La pragmatique est la branche de la linguistique qui étudie le sens en contexte — ce que les mots VEULENT DIRE au-delà de leur sens littéral : (1) Connotation vs dénotation : la dénotation est le sens littéral du dictionnaire ; la connotation est la charge affective, culturelle ou sociale. Exemples : « thrifty » (dénotation = qui économise, connotation +) vs « stingy » (dénotation = qui économise, connotation −) ; « slender » (+) vs « skinny » (−) ; « confident » (+) vs « arrogant » (−). Les francophones confondent souvent ces paires car le français ne distingue pas toujours ces nuances. (2) Implicature (concept de Grice) : ce qui est communiqué sans être dit explicitement. Si quelqu\'un dit « It\'s cold in here », l\'implicature est souvent « Fermez la fenêtre ». Les anglophones comptent enormément sur l\'implicature — les francophones, habitués à plus de directivité, risquent de prendre les énoncés au pied de la lettre. (3) Présupposition : ce qui est tenu pour acquis dans un énoncé. « Have you stopped smoking? » présuppose que vous fumiez. En anglais, les présuppositions sont souvent exploitées dans la diplomatie et les négociations. (4) Speech act = acte de langage : certains énoncés FAISANT quelque chose plutôt que de DIRE quelque chose. « I promise », « I apologise », « I name this ship » — ces énoncés sont des actions. En anglais, « I\'m sorry » peut être un speech act d\'excuse OU un simple expression de sympathie (« I\'m sorry to hear that ») — cette ambiguité n\'existe pas de la même façon en français. (5) Le principe de coopération de Grice : les anglophones suivent quatre maximes — quantité (ni trop ni trop peu), qualité (vérité), relation (pertinence), manière (clarté). Quand une maxime est violée, l\'auditeur cherche une implicature.',
    examples: [
      { sentence: 'The denotation of « cheap » is inexpensive, but its connotation suggests poor quality.', translation: 'La dénotation de « cheap » est peu coûteux, mais sa connotation suggère une mauvaise qualité.', isCorrect: true },
      { sentence: 'When the host says « It\'s getting late », the implicature is often that it\'s time for the guests to leave.', translation: 'Quand l\'hôte dit « It\'s getting late », l\'implicature est souvent qu\'il est temps que les invités partent.', isCorrect: true },
      { sentence: 'Saying « I apologise » and « I\'m sorry » always mean exactly the same thing in English.', translation: '', isCorrect: false },
      { sentence: 'The question « When did you stop lying? » carries the presupposition that the person used to lie.', translation: 'La question « When did you stop lying? » porte la présupposition que la personne mentait autrefois.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'Saying « I apologise » and « I\'m sorry » always mean exactly the same thing in English.', correct: '« I apologise » is a speech act of apology (formal), while « I\'m sorry » can express sympathy without accepting fault.', explanation: '« I apologise » est un acte de langage formel qui reconnaît une faute. « I\'m sorry » peut exprimer de la sympathie sans reconnaître de faute (« I\'m sorry for your loss »). Confondre les deux peut avoir des conséquences juridiques — « I\'m sorry » après un accident peut être interprété comme un aveu de faute dans certains contextes juridiques anglo-saxons.' },
      { wrong: 'She is very thrifty with her employees — she never praises them.', correct: 'She is very stingy with her employees — she never praises them.', explanation: '« Thrifty » a une connotation positive (économe, sensé) ; « stingy » a une connotation négative (avare, pingre). Être « thrifty with praise » est un contresens — on utilise « stingy with praise » ou « sparing with praise ».' },
    ],
  },
  conversation: [
    { speaker: 'Lecturer Okonkwo', role: 'A', text: 'Let\'s consider how pragmatics shapes professional communication. If your British colleague says « That\'s an interesting approach », what do they mean?', translation: 'Considérons comment la pragmatique façonne la communication professionnelle. Si votre collègue britannique dit « That\'s an interesting approach », que veut-il dire ?' },
    { speaker: 'Student Beaumont', role: 'B', text: 'Literally, they find it interesting. But the implicature might be the opposite — they could be politely expressing doubt.', translation: 'Littéralement, il la trouve intéressante. Mais l\'implicature pourrait être l\'inverse — il pourrait exprimer poliment un doute.' },
    { speaker: 'Lecturer Okonkwo', role: 'A', text: 'Exactly. The connotation of « interesting » in that context, with that intonation, is often scepticism. This is where denotation and pragmatic meaning diverge entirely.', translation: 'Exactement. La connotation de « interesting » dans ce contexte, avec cette intonation, est souvent du scepticisme. C\'est là que dénotation et sens pragmatique divergent totalement.' },
    { speaker: 'Student Beaumont', role: 'B', text: 'And what about « I hear what you say »? A French speaker might think it means agreement.', translation: 'Et que dire de « I hear what you say » ? Un francophone pourrait penser que cela signifie un accord.' },
    { speaker: 'Lecturer Okonkwo', role: 'A', text: 'That\'s a classic case of presupposition failure. « I hear what you say » in British English means « I completely disagree ». The presupposition of agreement is false — a dangerous misunderstanding in negotiations.', translation: 'C\'est un cas classique d\'échec de présupposition. « I hear what you say » en anglais britannique signifie « Je suis totalement en désaccord ». La présupposition d\'accord est fausse — un malentendu dangereux dans les négociations.' },
    { speaker: 'Student Beaumont', role: 'B', text: 'So pragmatics isn\'t optional — it\'s essential. Without it, you understand the words but miss the meaning entirely.', translation: 'Donc la pragmatique n\'est pas optionnelle — elle est essentielle. Sans elle, on comprend les mots mais on rate totalement le sens.' },
  ],
  conversationTitle: 'Pragmatique en contexte : décoder le sens au-delà des mots',
  pronunciation: [
    { word: 'Denotation', phonetic: '/ˌdiːnəˈteɪʃn/', meaning: 'Dénotation', tip: 'L\'accent est sur « TAY » : « dee-nuh-TAY-shun ». Le « de » initial est long. La terminaison « -tion » = « shun ». Ne dites pas « dé-no-ta-sion ».' },
    { word: 'Implicature', phonetic: '/ˈɪmplɪkətʃər/', meaning: 'Implicature', tip: 'L\'accent est sur « IM » : « IM-pli-kuh-chur ». Le « i » initial est bref. La terminaison « -ture » = « chur » comme dans « nature ». Ne dites pas « an-pli-ka-ture ».' },
    { word: 'Entail', phonetic: '/ɪnˈteɪl/', meaning: 'Impliquer', tip: 'L\'accent est sur « TAIL » : « in-TAIL ». Le « en » initial est réduit. Le « ai » = « éï ». Ne dites pas « on-tèl ».' },
    { word: 'Presupposition', phonetic: '/ˌpriːsʌpəˈzɪʃn/', meaning: 'Présupposition', tip: 'L\'accent principal est sur « ZISH » : « pree-suh-puh-ZISH-un ». C\'est un mot de 5 syllabes. Le « pre » est long. La terminaison « -tion » = « shun ».' },
  ],
}

// ─── c1-l43: Cross-cultural Talk ──────────────────────────────────────────────────
export const C1_L43: LessonContent = {
  vocab: [
    { english: 'high-context', french: 'à contexte fort (communication)', phonetic: '/haɪ ˈkɒntekst/', example: 'In high-context cultures, much of the meaning is conveyed through silence and body language.', exampleTranslation: 'Dans les cultures à contexte fort, une grande partie du sens est transmise par le silence et le langage corporel.' },
    { english: 'low-context', french: 'à contexte faible (communication)', phonetic: '/ləʊ ˈkɒntekst/', example: 'Low-context cultures prefer explicit verbal communication over implied meaning.', exampleTranslation: 'Les cultures à contexte faible préfèrent une communication verbale explicite au sens implicite.' },
    { english: 'to accommodate', french: 's\'adapter / accommoder', phonetic: '/əˈkɒmədeɪt/', example: 'Successful expatriates learn to accommodate the communication style of their host country.', exampleTranslation: 'Les expatriés réussis apprennent à s\'adapter au style de communication de leur pays d\'accueil.' },
    { english: 'rapport', french: 'relation / bon rapport', phonetic: '/ræˈpɔːr/', example: 'Building rapport is essential before discussing business in many cultures.', exampleTranslation: 'Créer un bon rapport est essentiel avant de discuter affaires dans de nombreuses cultures.' },
    { english: 'small talk', french: 'conversation légère / bavardage social', phonetic: '/smɔːl tɔːk/', example: 'In American business culture, small talk at the beginning of a meeting signals goodwill.', exampleTranslation: 'Dans la culture d\'affaires américaine, le small talk en début de réunion signale la bonne volonté.' },
  ],
  grammar: {
    title: 'Communication interculturelle : contexte fort vs contexte faible et adaptation',
    explanation: 'La théorie d\'Edward Hall distingue deux modes de communication fondamentaux : (1) Communication « high-context » (contexte fort) : le sens repose sur le contexte partagé — relations, statut, non-dits, silence. Le Japon, la Chine, les pays arabes et les pays méditerranéens sont des cultures high-context. On ne dit pas tout explicitement ; le silence est significatif ; la relation prime sur le message. Exemple : au Japon, « it\'s difficult » signifie souvent « non ». (2) Communication « low-context » (contexte faible) : le sens est porté par les mots explicites. Les États-Unis, l\'Allemagne, les pays scandinaves sont des cultures low-context. On dit ce qu\'on pense ; la clarté est valorisée ; le message prime sur la relation. (3) La France est une culture intermédiaire mais plus proche du pôle high-context que les francophones ne le pensent. Le sous-entendu, l\'ironie, la litote et le « non-dit » sont centraux en français — ce qui rapproche la France du modèle high-context. Cependant, les francophones valorisent aussi la rigueur verbale, ce qui crée un profil hybride. (4) « Small talk » : en culture anglo-saxonne (low-context), le small talk n\'est PAS du bavardage futile — c\'est un rituel de « rapport-building » essentiel. Sauter le small talk et passer directement aux affaires est perçu comme agressif ou froid. En France, on peut passer plus vite au « vif du sujet » sans offenser. (5) « Accommodate » en contexte interculturel = s\'adapter au style de l\'autre, pas simplement « héberger ». C\'est une compétence active : ajuster son degré de directivité, de formalité, et d\'expressivité verbale.',
    examples: [
      { sentence: 'In a high-context culture, saying « maybe » often means « no » without causing loss of face.', translation: 'Dans une culture à contexte fort, dire « maybe » signifie souvent « non » sans provoquer de perte de face.', isCorrect: true },
      { sentence: 'In low-context cultures, explicit communication is preferred because it reduces ambiguity.', translation: 'Dans les cultures à contexte faible, la communication explicite est préférée car elle réduit l\'ambiguïté.', isCorrect: true },
      { sentence: 'In American business culture, it is better to skip small talk and get straight to the point.', translation: '', isCorrect: false },
      { sentence: 'Accommodating different communication styles is a sign of cultural intelligence, not weakness.', translation: 'S\'adapter à différents styles de communication est un signe d\'intelligence culturelle, pas de faiblesse.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'In American business culture, it is better to skip small talk and get straight to the point.', correct: 'In American business culture, small talk is expected at the start of a meeting — skipping it signals impatience or disinterest.', explanation: 'Le small talk est un rituel social obligatoire dans les cultures anglo-saxonnes. Le sauter pour « aller droit au but » est perçu comme froid, impatient ou désintéressé par la relation. C\'est une erreur typique des francophones qui considèrent le bavardage comme une perte de temps.' },
      { wrong: 'He has a good rapport with his employees because he tells them exactly what to do.', correct: 'He has a good rapport with his employees because he listens to their concerns and builds trust.', explanation: '« Rapport » en anglais = relation de confiance et de compréhension mutuelle, pas une relation d\'autorité. Donner des ordres directs ne crée pas du rapport — l\'écoute et la confiance, si. Le faux ami : en français, « un rapport » peut signifier un rapport hiérarchique ou un rapport écrit.' },
    ],
  },
  conversation: [
    { speaker: 'Cross-cultural Coach Yamada', role: 'A', text: 'Let\'s talk about what happens when high-context and low-context communicators meet in the workplace. Any experiences?', translation: 'Parlons de ce qui se passe quand des communicateurs à contexte fort et à contexte faible se rencontrent au travail. Des expériences ?' },
    { speaker: 'HR Director Mercier', role: 'B', text: 'Absolutely. When our Japanese partners said « we\'ll consider it », our French team assumed they were genuinely considering it. They meant no.', translation: 'Absolument. Quand nos partenaires japonais ont dit « we\'ll consider it », notre équipe française a supposé qu\'ils considéraient réellement. Ils voulaient dire non.' },
    { speaker: 'Cross-cultural Coach Yamada', role: 'A', text: 'Classic high-context communication. The meaning is in what\'s NOT said. In low-context cultures, « we\'ll consider it » genuinely means consideration.', translation: 'Communication classique à contexte fort. Le sens est dans ce qui n\'est PAS dit. Dans les cultures à contexte faible, « we\'ll consider it » signifie réellement une considération.' },
    { speaker: 'HR Director Mercier', role: 'B', text: 'And the small talk issue — our American CEO was offended when a French executive went straight to the agenda without any warm-up.', translation: 'Et le problème du small talk — notre PDG américain a été offensé quand un dirigeant français est passé directement à l\'ordre du jour sans aucun échauffement.' },
    { speaker: 'Cross-cultural Coach Yamada', role: 'A', text: 'That\'s because small talk builds rapport in low-context cultures. It\'s not wasted time — it\'s social glue. The key is to accommodate: match the other person\'s context level.', translation: 'C\'est parce que le small talk crée du rapport dans les cultures à contexte faible. Ce n\'est pas du temps perdu — c\'est de la colle sociale. La clé est de s\'adapter : calquer le niveau de contexte de l\'interlocuteur.' },
    { speaker: 'HR Director Mercier', role: 'B', text: 'So the rule is: when in Rome, do as the Romans do — but also understand why the Romans do it.', translation: 'Donc la règle est : à Rome, fais comme les Romains — mais comprends aussi pourquoi les Romains le font.' },
  ],
  conversationTitle: 'Communication interculturelle : quand les contextes se heurtent',
  pronunciation: [
    { word: 'High-context', phonetic: '/haɪ ˈkɒntekst/', meaning: 'À contexte fort', tip: 'Prononcez « haï KON-tekst ». L\'accent est sur « KON » dans « context ». Ne dites pas « kontest ». Le « x » final est clair.' },
    { word: 'Accommodate', phonetic: '/əˈkɒmədeɪt/', meaning: 'S\'adapter', tip: 'L\'accent est sur « COM » : « uh-KOM-uh-dayt ». Ce mot a des doubles consonnes : « cc » et « mm ». Attention à ne pas omettre un « m » à l\'écrit. Le « a » initial est réduit.' },
    { word: 'Rapport', phonetic: '/ræˈpɔːr/', meaning: 'Relation de confiance', tip: 'L\'accent est sur « POR » : « ra-POR ». Le « t » final est MUET en anglais — ne le prononcez pas ! C\'est un mot d\'origine française mais le « t » a été abandonné en anglais. Ne dites pas « ra-por-t ».' },
    { word: 'Small talk', phonetic: '/smɔːl tɔːk/', meaning: 'Conversation légère', tip: '« Small » = « smol » avec le « aw » ouvert. « Talk » = « tok » avec le même « aw ». Les deux mots ont le même son vocalique. Ne dites pas « smol tok » avec des « o » français.' },
  ],
}

// ─── c1-l44: Cultural Misunderstandings ───────────────────────────────────────────
export const C1_L44: LessonContent = {
  vocab: [
    { english: 'false friend', french: 'faux ami / faux ami lexical', phonetic: '/fɔːls frend/', example: '« Actually » is a false friend — it means « in fact », not « actuellement ».', exampleTranslation: '« Actually » est un faux ami — il signifie « en fait », pas « actuellement ».' },
    { english: 'faux pas', french: 'impair / faux pas', phonetic: '/ˌfəʊ ˈpɑː/', example: 'Commenting on someone\'s weight is a major faux pas in Anglo-Saxon culture.', exampleTranslation: 'Faire des commentaires sur le poids de quelqu\'un est un faux pas majeur dans la culture anglo-saxonne.' },
    { english: 'indirectness', french: 'indirectivité / caractère indirect', phonetic: '/ˌɪndəˈrektnəs/', example: 'British indirectness can be confusing: « I might disagree » often means « I completely disagree ».', exampleTranslation: 'L\'indirectivité britannique peut être déroutante : « I might disagree » signifie souvent « Je suis totalement en désaccord ».' },
    { english: 'face-saving', french: 'sauvegarde de la face', phonetic: '/ˈfeɪs ˌseɪvɪŋ/', example: 'Offering an alternative proposal is a face-saving strategy when rejecting someone\'s idea.', exampleTranslation: 'Proposer une alternative est une stratégie de sauvegarde de la face quand on rejette l\'idée de quelqu\'un.' },
    { english: 'to take for granted', french: 'tenir pour acquis / considérer comme allant de soi', phonetic: '/teɪk fɔːr ˈɡræntɪd/', example: 'Don\'t take for granted that your communication style is universal — it\'s culturally specific.', exampleTranslation: 'Ne tenez pas pour acquis que votre style de communication est universel — il est culturellement spécifique.' },
  ],
  grammar: {
    title: 'Malentendus culturels : faux amis, faux pas et stratégies de sauvegarde de la face',
    explanation: 'Les malentendus culturels en anglais sont souvent invisibles car ils se cachent dans des mots qui semblent familiers ou des comportements qui semblent normaux : (1) Faux amis lexicaux les plus dangereux au niveau C1 : « actually » = en fait (≠ actuellement = currently) ; « eventually » = éventuellement/à la fin (≠ éventuellement = possibly) ; « to assume » = supposer (≠ assumer = to take on/to accept responsibility) ; « sensible » = raisonnable/réfléchi (≠ sensible = sensitive) ; « to demand » = exiger de manière autoritaire (≠ demander = to ask) ; « to ignore » = ignorer volontairement (≠ ignorer = to not know) ; « comprehensive » = exhaustif (≠ compréhensif = understanding) ; « to pretend » = faire semblant (≠ prétendre = to claim). (2) Faux pas culturels fréquents des francophones : demander l\'âge, le salaire ou la situation familiale ; faire des commentaires sur l\'apparence physique ; dire « I want » au lieu de « I\'d like » ; utiliser le prénom trop vite (« first-name basis » se gagne) ; être trop direct dans les feedbacks négatifs. (3) Indirectness vs directness : l\'anglais (surtout britannique) est une langue indirecte. Les Anglo-Saxons utilisent des stratégies d\'atténuation : « I was wondering if... » (au lieu de « Can I... ») ; « Would you mind... » (au lieu de « Please... ») ; « It seems to me that... » (au lieu de « You\'re wrong »). Les francophones, habitués à la directivité, sont souvent perçus comme impolis en anglais. (4) Face-saving strategies : en anglais, préserver la « face » de l\'interlocuteur est crucial. On ne dit JAMAIS « Your idea is bad » — on dit « That\'s an interesting perspective, but have we considered... ». On ne dit JAMAIS « You\'re wrong » — on dit « I see it slightly differently ». Le concept de « face » (Goffman) est central dans la culture anglo-saxonne et explique l\'indirectivité.',
    examples: [
      { sentence: 'She eventually found a solution after weeks of research.', translation: 'Elle a fini par trouver une solution après des semaines de recherche.', isCorrect: true },
      { sentence: 'He demanded me to help him with the project.', translation: '', isCorrect: false },
      { sentence: 'Instead of saying « That\'s wrong », a face-saving approach would be « I wonder if there might be another way to look at this ».', translation: 'Au lieu de dire « C\'est faux », une approche de sauvegarde de la face serait « Je me demande s\'il n\'y aurait pas une autre façon d\'envisager cela ».', isCorrect: true },
      { sentence: 'The word « sensible » in English means practical and reasonable, not sensitive.', translation: 'Le mot « sensible » en anglais signifie pratique et raisonnable, pas sensible.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'He demanded me to help him with the project.', correct: 'He asked me to help him with the project. / He demanded that I help him with the project.', explanation: '« To demand » = exiger de manière autoritaire, pas « demander » en français. Dire « He demanded me to help » sonne comme un ordre agressif. En anglais courant, on « asks » (demande poliment). Si on veut vraiment dire « exiger » : « He demanded that I help him » (structure du subjonctif : demand that + sujet + base verbale).' },
      { wrong: 'She is very sensible — she cries at every sad movie.', correct: 'She is very sensitive — she cries at every sad movie.', explanation: 'Faux ami classique : « sensible » en anglais = raisonnable, réfléchi, pragmatique. Pour dire « qui ressent les émotions fortement », on utilise « sensitive ». Une personne « sensible » en anglais prend des décisions rationnelles ; une personne « sensitive » est émotive. C\'est l\'un des faux amis les plus fréquents entre le français et l\'anglais.' },
    ],
  },
  conversation: [
    { speaker: 'Intercultural Trainer Patel', role: 'A', text: 'Let\'s discuss the most common faux pas francophones make in English-speaking workplaces. Who has an example?', translation: 'Discutons des faux pas les plus courants que les francophones commettent dans les entreprises anglophones. Qui a un exemple ?' },
    { speaker: 'Manager Dubois', role: 'B', text: 'I once told an American colleague « I\'ll demand a meeting with the director ». She looked shocked — I meant « ask for », not « demand »!', translation: 'J\'ai dit un jour à une collègue américaine « I\'ll demand a meeting with the director ». Elle a eu l\'air choquée — je voulais dire « ask for », pas « demand » !' },
    { speaker: 'Intercultural Trainer Patel', role: 'A', text: 'Classic false friend. « Demand » in English sounds aggressive and authoritarian. Another trap: « actually ». French speakers use it to mean « actuellement », but in English it means « in fact ».', translation: 'Faux ami classique. « Demand » en anglais sonne agressif et autoritaire. Autre piège : « actually ». Les francophones l\'utilisent pour dire « actuellement », mais en anglais cela signifie « en fait ».' },
    { speaker: 'Manager Dubois', role: 'B', text: 'What about directness? I once said « Your presentation was confusing » to a British colleague. He was mortified.', translation: 'Et la directivité ? J\'ai dit un jour « Your presentation was confusing » à un collègue britannique. Il était mortifié.' },
    { speaker: 'Intercultural Trainer Patel', role: 'A', text: 'That\'s where face-saving strategies come in. Instead of a direct critique, you might say « I found some parts a bit unclear — could you walk me through the main argument? » Same message, no loss of face.', translation: 'C\'est là qu\'interviennent les stratégies de sauvegarde de la face. Au lieu d\'une critique directe, vous pourriez dire « J\'ai trouvé certaines parties un peu peu claires — pourriez-vous m\'expliquer l\'argument principal ? » Même message, pas de perte de face.' },
    { speaker: 'Manager Dubois', role: 'B', text: 'So in English, how you say something matters as much as what you say. The indirectness isn\'t dishonesty — it\'s respect.', translation: 'Donc en anglais, la façon de dire les choses compte autant que ce qu\'on dit. L\'indirectivité n\'est pas de la malhonnêteté — c\'est du respect.' },
  ],
  conversationTitle: 'Faux pas et faux amis : naviguer les pièges culturels',
  pronunciation: [
    { word: 'Actually', phonetic: '/ˈæktʃuəli/', meaning: 'En fait', tip: 'L\'accent est sur « AC » : « AK-choo-uh-lee ». Le « t » + « u » = « choo ». Ne dites PAS « ak-tyal-lee » à la française. Ce mot est un faux ami : il signifie « en fait », JAMAIS « actuellement ».' },
    { word: 'Eventually', phonetic: '/ɪˈventʃuəli/', meaning: 'Finalement / à la fin', tip: 'L\'accent est sur « VEN » : « ih-VEN-choo-uh-lee ». Le « t » + « u » = « choo ». Ne dites PAS « é-ven-tyal-lee ». Ce mot signifie « à la fin / éventuellement », PAS « peut-être ».' },
    { word: 'Sensible', phonetic: '/ˈsensɪbl/', meaning: 'Raisonnable / réfléchi', tip: 'L\'accent est sur « SEN » : « SEN-suh-bl ». Le « i » est réduit. La terminaison « -ble » = « bl ». Attention : ce mot NE signifie PAS « sensible » en français ! Utilisez « sensitive » pour le sens français.' },
    { word: 'Faux pas', phonetic: '/ˌfəʊ ˈpɑː/', meaning: 'Impair', tip: 'En anglais, prononcez « fo PAH » — le « x » est muet et l\'accent est sur « PAH ». Ne prononcez PAS ce mot à la française « fo-pa ». L\'anglais a emprunté cette expression mais l\'a anglicisée.' },
  ],
}

// ─── c1-l45: Culture Sounds ───────────────────────────────────────────────────────
export const C1_L45: LessonContent = {
  vocab: [
    { english: 'etymology', french: 'étymologie', phonetic: '/ˌetɪˈmɒlədʒi/', example: 'The etymology of « salary » reveals it comes from Latin « sal » — salt, once used as payment.', exampleTranslation: 'L\'étymologie de « salary » révèle qu\'il vient du latin « sal » — le sel, autrefois utilisé comme paiement.' },
    { english: 'morphology', french: 'morphologie (linguistique)', phonetic: '/mɔːrˈfɒlədʒi/', example: 'English morphology is simpler than French — most plurals just add « -s ».', exampleTranslation: 'La morphologie anglaise est plus simple que la française — la plupart des pluriels ajoutent simplement « -s ».' },
    { english: 'semantics', french: 'sémantique', phonetic: '/sɪˈmæntɪks/', example: 'Semantics examines how meaning is constructed in language and how words relate to concepts.', exampleTranslation: 'La sémantique examine comment le sens se construit dans le langage et comment les mots se rapportent aux concepts.' },
    { english: 'phonology', french: 'phonologie', phonetic: '/fəˈnɒlədʒi/', example: 'French and English phonology differ significantly — French has nasal vowels that English lacks.', exampleTranslation: 'La phonologie française et anglaise diffèrent considérablement — le français a des voyelles nasales que l\'anglais n\'a pas.' },
    { english: 'sociolinguistics', french: 'sociolinguistique', phonetic: '/ˌsəʊsiəʊlɪŋˈɡwɪstɪks/', example: 'Sociolinguistics studies how social factors like class and region influence language use.', exampleTranslation: 'La sociolinguistique étudie comment les facteurs sociaux comme la classe et la région influencent l\'usage de la langue.' },
  ],
  grammar: {
    title: 'Termes culturels et linguistiques : prononciation et pièges pour francophones',
    explanation: 'Les termes linguistiques et culturels posent des problèmes spécifiques aux francophones car beaucoup viennent du grec ou du latin et existent aussi en français, mais avec une prononciation différente : (1) « Etymology » : /ˌetɪˈmɒlədʒi/ — l\'accent est sur « MOL », pas sur « e » comme en français « éty-mo-lo-gie ». Le « y » se prononce « i » bref, pas « u ». Ne dites PAS « é-ti-mo-lo-jie ». (2) « Morphology » : /mɔːrˈfɒlədʒi/ — l\'accent est sur « FOL », le « ph » = « f ». En français, on dit « mor-fo-lo-jie » avec l\'accent sur « fo » — en anglais, c\'est sur « FOL » aussi mais la syllabe est plus longue et le « r » après « mo » est prononcé. (3) « Semantics » : /sɪˈmæntɪks/ — l\'accent est sur « MAN ». Le « e » initial est un « i » bref (comme dans « sit »), pas un « é ». Ne dites PAS « sé-man-tiks ». (4) « Phonology » : /fəˈnɒlədʒi/ — l\'accent est sur « NOL ». Le « ph » = « f ». Le « o » initial est réduit en schwa. (5) « Sociolinguistics » : /ˌsəʊsiəʊlɪŋˈɡwɪstɪks/ — l\'accent principal est sur « GWIS ». C\'est un mot très long (6 syllabes). Le « cio » = « shio » ou « sio ». Les francophones ont tendance à franciser ces mots, ce qui en contexte académique anglophone peut nuire à la crédibilité. Règle générale : tout terme en « -ology » ou « -istics » a l\'accent sur l\'antépénultième syllabe (la troisième en partant de la fin) : ety-MOL-ogy, mor-PHOL-ogy, pho-NOL-ogy, socio-ling-WIS-tics.',
    examples: [
      { sentence: 'The etymology of the word reveals its Arabic origins.', translation: 'L\'étymologie du mot révèle ses origines arabes.', isCorrect: true },
      { sentence: 'Semantics deals with meaning, while syntax deals with sentence structure.', translation: 'La sémantique traite du sens, tandis que la syntaxe traite de la structure des phrases.', isCorrect: true },
      { sentence: 'The sé-mantics of this phrase are ambiguous.', translation: '', isCorrect: false },
      { sentence: 'Sociolinguistics examines how social class affects pronunciation and vocabulary choices.', translation: 'La sociolinguistique examine comment la classe sociale affecte la prononciation et les choix lexicaux.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'The sé-mantics of this phrase are ambiguous.', correct: 'The semantics of this phrase are ambiguous.', explanation: '« Semantics » se prononce /sɪˈmæntɪks/ — l\'accent est sur « MAN » et le « e » initial est un « i » bref (schwa), pas un « é » français. Dire « sé-man-tiks » identifie immédiatement le locuteur comme francophone. Dans un contexte académique, cette erreur peut nuire à la crédibilité.' },
      { wrong: 'The ety-mology of the word shows its French origin.', correct: 'The etymology of the word shows its French origin.', explanation: '« Etymology » se prononce /ˌetɪˈmɒlədʒi/ — l\'accent est sur « MOL » (troisième syllabe en partant de la fin), pas sur « e » comme en français. La règle pour tous les mots en « -ology » : l\'accent est sur l\'antépénultième syllabe. Ne dites pas « é-ti-mo-lo-jie ».' },
    ],
  },
  conversation: [
    { speaker: 'Linguistics Professor Adams', role: 'A', text: 'One of the biggest telltale signs of a French speaker in an English academic setting is the pronunciation of linguistic terminology. Who can give me an example?', translation: 'L\'un des signes les plus révélateurs d\'un locuteur français dans un contexte académique anglais est la prononciation de la terminologie linguistique. Qui peut me donner un exemple ?' },
    { speaker: 'PhD Candidate Renard', role: 'B', text: 'I used to say « sé-man-tiks » until my supervisor corrected me — it\'s /sɪˈmæntɪks/ with the stress on « MAN ».', translation: 'Je disais « sé-man-tiks » jusqu\'à ce que mon directeur de thèse me corrige — c\'est /sɪˈmæntɪks/ avec l\'accent sur « MAN ».' },
    { speaker: 'Linguistics Professor Adams', role: 'A', text: 'Exactly. And « etymology »? The stress pattern follows the same rule as all « -ology » words — stress the antepenultimate syllable.', translation: 'Exactement. Et « etymology » ? Le schéma d\'accentuation suit la même règle que tous les mots en « -ology » — accentuez l\'antépénultième syllabe.' },
    { speaker: 'PhD Candidate Renard', role: 'B', text: 'So it\'s /ˌetɪˈmɒlədʒi/ — stress on « MOL ». In French, we stress « é » at the beginning, which sounds completely wrong in English.', translation: 'Donc c\'est /ˌetɪˈmɒlədʒi/ — accent sur « MOL ». En français, on accentue « é » au début, ce qui sonne complètement faux en anglais.' },
    { speaker: 'Linguistics Professor Adams', role: 'A', text: 'Precisely. And « sociolinguistics » — the primary stress is on « GWIS »: /ˌsəʊsiəʊlɪŋˈɡwɪstɪks/. It\'s a long word, but the stress pattern is predictable once you know the rule.', translation: 'Précisément. Et « sociolinguistics » — l\'accent principal est sur « GWIS » : /ˌsəʊsiəʊlɪŋˈɡwɪstɪks/. C\'est un mot long, mais le schéma d\'accentuation est prévisible une fois que vous connaissez la règle.' },
    { speaker: 'PhD Candidate Renard', role: 'B', text: 'The pattern is clear: in English, these academic terms follow consistent stress rules. It\'s not arbitrary — it\'s phonology at work.', translation: 'Le schéma est clair : en anglais, ces termes académiques suivent des règles d\'accentuation cohérentes. Ce n\'est pas arbitraire — c\'est la phonologie à l\'œuvre.' },
  ],
  conversationTitle: 'Prononciation académique : termes linguistiques et crédibilité',
  pronunciation: [
    { word: 'Etymology', phonetic: '/ˌetɪˈmɒlədʒi/', meaning: 'Étymologie', tip: 'L\'accent est sur « MOL » : « et-ih-MOL-uh-jee ». C\'est un mot de 5 syllabes. La règle des mots en « -ology » : accent sur l\'antépénultième syllabe. Ne dites PAS « é-ti-mo-lo-jie ».' },
    { word: 'Semantics', phonetic: '/sɪˈmæntɪks/', meaning: 'Sémantique', tip: 'L\'accent est sur « MAN » : « sih-MAN-tiks ». Le « e » initial = « i » bref (schwa), PAS « é ». Le « a » de « man » est ouvert comme dans « cat ». Ne dites PAS « sé-man-tiks ».' },
    { word: 'Phonology', phonetic: '/fəˈnɒlədʒi/', meaning: 'Phonologie', tip: 'L\'accent est sur « NOL » : « fuh-NOL-uh-jee ». Le « ph » = « f ». Le « o » initial est réduit en schwa. La terminaison « -ology » = « ol-uh-jee ». Ne dites PAS « fo-no-lo-jie ».' },
    { word: 'Sociolinguistics', phonetic: '/ˌsəʊsiəʊlɪŋˈɡwɪstɪks/', meaning: 'Sociolinguistique', tip: 'L\'accent principal est sur « GWIS » : « SO-shee-oh-ling-GWIS-tiks ». C\'est un mot de 6 syllabes. L\'accent secondaire est sur « SO ». Le « cio » = « shio ». Ne dites PAS « so-syo-lin-gwis-tiks ».' },
  ],
}
