import type { LessonContent } from './lesson-content'

// ════════════════════════════════════════════════════════════════════════════════
// C2 MASTERY — UNIT 14: NEAR-NATIVE PERFECTION (c2-u14)
// Lessons c2-l66 through c2-l70
// YOELANG English Learning App for Francophone Users
// Near-native mastery: nuance, subtlety, finesse, and ultimate fluency
// ════════════════════════════════════════════════════════════════════════════════

// ─── c2-l66: Mastery Vocabulary — Nuance, subtlety, finesse ───────────────────
export const C2_L66: LessonContent = {
  vocab: [
    { english: 'Nuance', french: 'Nuance', phonetic: '/ˈnjuːɑːns/', example: 'The nuance of her argument eluded most of the audience, who grasped only the broad strokes.', exampleTranslation: 'La nuance de son argument a échappé à la plupart du public, qui n\'a saisi que les grandes lignes.' },
    { english: 'Finesse', french: 'Finesse', phonetic: '/fɪˈnɛs/', example: 'He handled the diplomatic crisis with such finesse that both parties felt they had been heard.', exampleTranslation: 'Il a géré la crise diplomatique avec une telle finesse que les deux parties ont senti qu\'elles avaient été entendues.' },
    { english: 'Subtext', french: 'Sous-entendu', phonetic: '/ˈsʌbtɛkst/', example: 'What went unspoken carried far more weight than the subtext she carefully wove into her speech.', exampleTranslation: 'Ce qui est resté non dit portait bien plus de poids que le sous-entendu qu\'elle a tissé dans son discours.' },
    { english: 'Derivation', french: 'Dérivation lexicale', phonetic: '/ˌdɛrɪˈveɪʃən/', example: 'The derivation of "understand" from "under" + "stand" illustrates how compound metaphors shape lexical meaning.', exampleTranslation: 'La dérivation de « understand » à partir de « under » + « stand » illustre comment les métaphores composées façonnent le sens lexical.' },
    { english: 'Equivocate', french: 'Équivoquer', phonetic: '/ɪˈkwɪvəkeɪt/', example: 'Pressed for a straight answer, the minister continued to equivocate, leaving the committee none the wiser.', exampleTranslation: 'Pressé de répondre franchement, le ministre a continué à équivoquer, laissant le comité dans l\'ignorance.' },
  ],
  grammar: {
    title: 'Free Indirect Speech and Implied Meaning',
    explanation: 'Le discours indirect libre (free indirect speech) est une technique narrative qui fusionne la voix du narrateur et celle du personnage sans verbe introducteur. En anglais, elle se manifeste par l\'utilisation du temps du récit (past tense) combiné à des marqueurs déictiques du discours direct : "She would not be spoken to like that. How dare he?" — la première phrase est du narrateur, la deuxième est la pensée du personnage, sans "she thought". À C2, cette technique est essentielle pour saisir les sous-entendus (implied meaning) dans la littérature et la presse anglophone. Les locuteurs natifs emploient aussi des structures impliquant sans dire : "It\'s not as if I minded" (sous-entendu : je le fais remarquer, donc je le fais un peu), "One might have expected better" (sous-entendu : c\'est décevant), "Not that it matters" (sous-entendu : ça importe, mais je feins le détachement). La maîtrise de ces structures permet de naviguer les sous-entendus avec la subtilité d\'un locuteur natif.',
    examples: [
      { sentence: 'She would not be treated this way. Not after everything she had done.', translation: 'On ne la traiterait pas ainsi. Pas après tout ce qu\'elle avait fait.', isCorrect: true },
      { sentence: 'It\'s not as if he hadn\'t been warned, though one might have expected a touch more tact.', translation: 'Ce n\'est pas comme s\'il n\'avait pas été averti, bien qu\'on aurait pu s\'attendre à un peu plus de tact.', isCorrect: true },
      { sentence: 'She said that she would not be treated this way, and she thought that how dare he.', translation: '', isCorrect: false },
      { sentence: 'Not that it matters, of course — but she did happen to mention it twice.', translation: 'Non que ça compte, bien sûr — mais elle a quand même pris la peine de le mentionner deux fois.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'She said that she would not be treated this way, and she thought that how dare he.', correct: 'She would not be treated this way. How dare he?', explanation: 'Le discours indirect libre supprime les verbes introducteurs ("she thought", "she said"). Si vous les réintroduisez, vous perdez précisément l\'effet de fusion narrative entre narrateur et personnage. La marque du C2 est de reconnaître et produire cette fusion.' },
      { wrong: 'Not that it matters, of course. But she mentioned it twice.', correct: 'Not that it matters, of course — but she did happen to mention it twice.', explanation: 'Le "but" après "not that it matters" doit être lié par un tiret ou une virgule, pas un point, car la phrase est une seule unité rhétorique : la concession et la rétractation forment un geste communicatif unique. Le "did happen" renforce l\'ironie de la concession.' },
    ],
  },
  conversation: [
    { speaker: 'Eleanor', role: 'A', text: 'You know, it\'s not as if I\'m ungrateful. Far from it. It\'s just that the gesture, however well-intentioned, rather missed the point of what I was actually saying.', translation: 'Tu sais, ce n\'est pas comme si j\'étais ingrate. Loin de là. C\'est juste que le geste, aussi bien intentionné fût-il, a plutôt manqué le fond de ce que je disais réellement.' },
    { speaker: 'Marcus', role: 'B', text: 'Right. So when he offered to "simplify" your proposal, you heard something rather different from helpfulness.', translation: 'Exact. Donc quand il a proposé de « simplifier » ta proposition, tu as entendu quelque chose de plutôt différent de l\'aide.' },
    { speaker: 'Eleanor', role: 'A', text: 'Precisely. The subtext was unmistakable — that my ideas needed rendering into plainer terms, presumably for plainer minds. One might have expected a touch more finesse.', translation: 'Précisément. Le sous-entendu était unmistakable — que mes idées avaient besoin d\'être traduites en termes plus simples, vraisemblablement pour des esprits plus simples. On aurait pu s\'attendre à un peu plus de finesse.' },
    { speaker: 'Marcus', role: 'B', text: 'Not that subtlety has ever been his forte. He equivocates so smoothly you almost believe he\'s being straightforward.', translation: 'Non que la subtilité ait jamais été son fort. Il équivoque si habilement qu\'on croirait presque qu\'il est direct.' },
    { speaker: 'Eleanor', role: 'A', text: 'And that, I suppose, is the real art of it. The nuance isn\'t in what he says — it\'s in the derivation of meaning from context. You catch it only if you\'re listening for the gap between the words and the tone.', translation: 'Et c\'est, je suppose, le véritable art de la chose. La nuance n\'est pas dans ce qu\'il dit — elle est dans la dérivation du sens à partir du contexte. On ne la perçoit que si l\'on écoute l\'écart entre les mots et le ton.' },
    { speaker: 'Marcus', role: 'B', text: 'Well, you\'ve certainly mastered that particular art. I doubt even he realises just how much you\'ve noticed.', translation: 'Eh bien, tu as certainement maîtrisé cet art en particulier. Je doute même qu\'il réalise à quel point tu as remarqué de choses.' },
    { speaker: 'Eleanor', role: 'A', text: 'Which is, of course, precisely the point. The most effective equivocation is the kind that leaves no fingerprints.', translation: 'Ce qui est, bien sûr, précisément le but. L\'équivoque la plus efficace est celle qui ne laisse pas d\'empreintes.' },
  ],
  conversationTitle: 'L\'art du sous-entendu',
  pronunciation: [
    { word: 'Nuance', phonetic: '/ˈnjuːɑːns/', meaning: 'Nuance', tip: 'En anglais, l\'accent est sur la PREMIÈRE syllabe : NYOO-ahns. En français, on dit "nü-ahs" avec l\'accent à la fin — attention à ne pas transférer ce schéma. Le "u" anglais = "yoo" comme dans "new".' },
    { word: 'Finesse', phonetic: '/fɪˈnɛs/', meaning: 'Finesse', tip: 'Accent sur la deuxième syllabe : fin-ESS. Le "i" de la première syllabe est réduit comme dans "fit". Ne prononcez pas "fee-ness" à la française.' },
    { word: 'Subtext', phonetic: '/ˈsʌbtɛkst/', meaning: 'Sous-entendu', tip: 'Accent sur "sub" : SUB-tekst. Les deux consonnes finales "kst" doivent être audibles mais rapides. Ne glissez pas sur le "t" final — il distingue "subtext" de "subtlex" (inexistant).' },
    { word: 'Equivocate', phonetic: '/ɪˈkwɪvəkeɪt/', meaning: 'Équivoquer', tip: 'Accent sur "kwiv" : ih-KWIV-uh-kayt. Le "e" initial est réduit. Le suffixe "-ate" se prononce "ayt" (pas "at"). L\'ensemble fait 4 syllabes, pas 5.' },
  ],
}

// ─── c2-l67: Nuanced Expression — Free indirect speech, implied meaning ──────
export const C2_L67: LessonContent = {
  vocab: [
    { english: 'Insinuate', french: 'Insinuer', phonetic: '/ɪnˈsɪnjueɪt/', example: 'Rather than accuse her directly, he insinuated that her credentials might not withstand scrutiny.', exampleTranslation: 'Plutôt que de l\'accuser directement, il a insinué que ses qualifications pourraient ne pas résister à un examen approfondi.' },
    { english: 'Euphemism', french: 'Euphémisme', phonetic: '/ˈjuːfəmɪzəm/', example: '"Downsizing" is the corporate euphemism for sacking hundreds of loyal employees.', exampleTranslation: '« Downsizing » est l\'euphémisme corporate pour renvoyer des centaines d\'employés loyaux.' },
    { english: 'Presuppose', french: 'Présupposer', phonetic: '/ˌpriːsəˈpoʊz/', example: 'The question itself presupposes guilt, which is precisely why the defence objected.', exampleTranslation: 'La question elle-même présuppose la culpabilité, ce est précisément pourquoi la défense a objecté.' },
    { english: 'Preclude', french: 'Prévenir / Empêcher', phonetic: '/prɪˈkluːd/', example: 'A thorough proofreading would preclude the need for embarrassing corrections after publication.', exampleTranslation: 'Une relecture approfondie préviendrait la nécessité de corrections embarrassantes après publication.' },
    { english: 'Prevaricate', french: 'Tergiverser', phonetic: '/prɪˈværɪkeɪt/', example: 'When asked about the timeline, the CEO prevaricated, offering vague promises instead of concrete dates.', exampleTranslation: 'Quand on lui a demandé du calendrier, le PDG a tergiversé, offrant de vagues promesses au lieu de dates concrètes.' },
  ],
  grammar: {
    title: 'Presupposition Triggers and Implicature in English',
    explanation: 'En pragmatique linguistique anglaise, les présuppositions (presuppositions) et les implicatures (implicatures) sont des mécanismes par lesquels le sens va au-delà de ce qui est explicitement énoncé. Les déclencheurs de présupposition (presupposition triggers) les plus courants en anglais sont : les verbes factifs ("She realised that..." présuppose que c\'est vrai), les verbes itératifs ("He returned" présuppose qu\'il était déjà venu), les déterminants définis ("the culprit" présuppose l\'existence d\'un coupable), et les constructions clivées ("It was John who..." présuppose que quelqu\'un l\'a fait). L\'implicature de Grice, quant à elle, repose sur le principe de coopération : ce que le locuteur veut dire sans le dire, en exploitant les maximes conversationnelles. "Some students passed" implique (mais ne dit pas) que tous ne l\'ont pas fait. "He\'s not exactly a genius" implique qu\'il est plutôt le contraire. À C2, on maîtrise la production et la détection de ces couches de sens implicites, et on comprend que la négation d\'une présupposition ("I didn\'t know she had resigned") ne supprime pas la présupposition elle-même (elle a démissionné).',
    examples: [
      { sentence: 'She barely managed to conceal her disappointment, presupposing, of course, that there was disappointment to conceal.', translation: 'Elle a à peine réussi à dissimuler sa déception, ce qui présuppose, bien sûr, qu\'il y avait une déception à dissimuler.', isCorrect: true },
      { sentence: 'It was the junior minister who leaked the story, though the fact that there was a leak at all is the more troubling revelation.', translation: 'C\'est le ministre junior qui a fuité l\'information, bien que le fait qu\'il y ait eu une fuite en soi soit la révélation la plus troublante.', isCorrect: true },
      { sentence: 'He stopped smoking, but he never smoked.', translation: '', isCorrect: false },
      { sentence: 'Some people might consider that a rather euphemistic way of describing a disaster.', translation: 'Certains pourraient considérer cela comme une manière plutôt euphémistique de décrire un désastre.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'He stopped smoking, but he never smoked.', correct: 'He stopped smoking (presupposing he had smoked before). / He never smoked, so he couldn\'t have stopped.', explanation: '"Stopped smoking" présuppose qu\'il fumait auparavant. Dire "but he never smoked" crée une contradiction présuppositionnelle. En C2, il faut savoir que les présuppositions résistent à la négation : "He didn\'t stop smoking" présuppose toujours qu\'il fumait.' },
      { wrong: 'She insinuated that the project is a failure, so she said directly it failed.', correct: 'She insinuated that the project was a failure, which means she implied it without stating it outright.', explanation: '"Insinuate" signifie suggérer sans dire explicitement — c\'est le contraire de "say directly". Confondre insinuation et affirmation directe est une erreur de niveau pragmatique grave à C2. L\'insinuation repose précisément sur ce qui n\'est pas dit.' },
    ],
  },
  conversation: [
    { speaker: 'Dr. Lambert', role: 'A', text: 'I couldn\'t help noticing that the report rather carefully avoids mentioning the budget overrun. Not that I\'m suggesting anything, of course.', translation: 'Je n\'ai pu m\'empêcher de remarquer que le rapport évite plutôt soigneusement de mentionner le dépassement de budget. Non que je suggère quoi que ce soit, bien sûr.' },
    { speaker: 'Prof. Okafor', role: 'B', text: 'Naturally. One might almost say the omission was deliberate — except that would presuppose intent, and we wouldn\'t want to insinuate anything of the sort.', translation: 'Naturellement. On pourrait presque dire que l\'omission était délibérée — sauf que cela présupposerait une intention, et nous ne voudrions pas insinuer quoi que ce soit de ce genre.' },
    { speaker: 'Dr. Lambert', role: 'A', text: 'Precisely. Though it does rather preclude the possibility of transparency when key figures are simply left unmentioned, wouldn\'t you say?', translation: 'Précisément. Bien que cela préclude plutôt la possibilité de transparence quand les chiffres clés sont simplement laissés sans mention, ne diriez-vous pas ?' },
    { speaker: 'Prof. Okafor', role: 'B', text: 'The euphemism is itself instructive. "Budget realignment" — as if the numbers had simply wandered off and needed guiding back.', translation: 'L\'euphémisme est en soi instructif. « Réalignement budgétaire » — comme si les chiffres s\'étaient simplement égarés et avaient besoin d\'être guidés.' },
    { speaker: 'Dr. Lambert', role: 'A', text: 'And the prevarication when pressed for specifics! It was as though answering directly would have constituted some sort of breach of etiquette.', translation: 'Et la tergiversation quand on a insisté pour des précisions ! C\'était comme si répondre directement aurait constitué une sorte de violation de l\'étiquette.' },
    { speaker: 'Prof. Okafor', role: 'B', text: 'Well, one mustn\'t presuppose malice when incompetence will suffice. Still, the pattern of strategic silences does rather invite interpretation.', translation: 'Eh bien, il ne faut pas présupposer la malveillance quand l\'incompétence suffit. Cependant, le schéma de silences stratégiques invite plutôt à l\'interprétation.' },
    { speaker: 'Dr. Lambert', role: 'A', text: 'An interpretation that, I note, we are both too circumspect to articulate. How very English of us.', translation: 'Une interprétation que, je le note, nous sommes tous les deux trop circonspects pour articuler. Comme c\'est très anglais de notre part.' },
  ],
  conversationTitle: 'Présuppositions et euphémismes',
  pronunciation: [
    { word: 'Insinuate', phonetic: '/ɪnˈsɪnjueɪt/', meaning: 'Insinuer', tip: 'Accent sur "sin" : in-SIN-yoo-ayt. Le "u" après le "y" est réduit. Ne dites pas "in-sin-oo-ate" — le "yoo" fusionne avec le "a" suivant en un flux continu.' },
    { word: 'Euphemism', phonetic: '/ˈjuːfəmɪzəm/', meaning: 'Euphémisme', tip: 'Accent sur la première syllabe : YOO-fuh-miz-um. Le "eu" initial = "yoo" comme dans "euphoria". Le "ph" = "f". Le suffixe "-ism" se prononce "iz-um".' },
    { word: 'Presuppose', phonetic: '/ˌpriːsəˈpoʊz/', meaning: 'Présupposer', tip: 'Accent secondaire sur "pre", accent principal sur "pose" : pree-suh-POHZ. Le "pre" a un "ee" long. Le "ose" final = "ohz" avec un "z" sonore.' },
    { word: 'Prevaricate', phonetic: '/prɪˈværɪkeɪt/', meaning: 'Tergiverser', tip: 'Accent sur "var" : pri-VAIR-ih-kayt. Le "a" de "var" est long et ouvert comme dans "air". Ne confondez pas avec "provoke" — les syllabes sont différentes.' },
  ],
}

// ─── c2-l68: Native-level Talk — Effortless, nuanced native conversation ─────
export const C2_L68: LessonContent = {
  vocab: [
    { english: 'By the by', french: 'Au passage / Soit dit en passant', phonetic: '/baɪ ðə baɪ/', example: 'By the by, have you heard whether the funding came through?', exampleTranslation: 'Au passage, as-tu entendu si le financement est arrivé ?' },
    { english: 'If you must know', french: 'Si tu veux vraiment savoir', phonetic: '/ɪf juː mʌst noʊ/', example: 'If you must know, I turned it down — not that it\'s any of your business.', exampleTranslation: 'Si tu veux vraiment savoir, j\'ai refusé — non que ça te regarde.' },
    { english: 'Now then', french: 'Bon alors / Voyons', phonetic: '/naʊ ðɛn/', example: 'Now then, shall we get down to brass tacks or continue dancing around the issue?', exampleTranslation: 'Bon alors, allons-nous en venir au fait ou continuons-nous à tourner autour du pot ?' },
    { english: 'Fair enough', french: 'Soit / C\'est entendu', phonetic: '/fɛər ɪˈnʌf/', example: 'Fair enough, I can see why you\'d take that view, though I\'m not sure I share it.', exampleTranslation: 'Soit, je comprends pourquoi tu aurais cette opinion, bien que je ne sois pas sûr de la partager.' },
    { english: 'For what it\'s worth', french: 'Pour ce que ça vaut', phonetic: '/fɔːr wɒt ɪts wɜːrθ/', example: 'For what it\'s worth, I thought your presentation was the strongest of the lot.', exampleTranslation: 'Pour ce que ça vaut, j\'ai trouvé que ta présentation était la plus forte de toutes.' },
  ],
  grammar: {
    title: 'Discourse Markers, Hedges, and Native Pragmatic Particles',
    explanation: 'Les marqueurs discursifs (discourse markers) et les particules pragmatiques (pragmatic particles) sont les outils invisibles de la conversation native. Ils ne contribuent pas au contenu propositionnel mais orchestrent l\'interaction : "well" marque une reformulation ou une hésitation polie, "I mean" introduit une clarification, "you see" sollicite la compréhension de l\'interlocuteur, "right" vérifie l\'alignement, "anyway" referme un digression, et "then" conclut un raisonnement. Les hedges (atténuateurs) sont tout aussi cruciaux : "sort of", "kind of", "arguably", "in a sense", "if you like" adoucissent les assertions et laissent une porte de sortie. "Quite" est particulièrement délicat : "quite good" en anglais britannique signifie "plutôt bien" (modéré), tandis qu\'en américain il peut signifier "très bien". "Rather" sert d\'atténuateur understated : "rather good" = "plutôt bon" avec une nuance de litote britannique. La maîtrise de ces particules est ce qui distingue un locuteur C2 d\'un locuteur simplement avancé — elles sont le "vibre" de la langue, invisibles mais indispensables au naturel.',
    examples: [
      { sentence: 'Well, I mean, it\'s not exactly a disaster, is it? More of a, sort of, learning opportunity, if you like.', translation: 'Eh bien, je veux dire, ce n\'est pas exactement un désastre, n\'est-ce pas ? Plutôt une, en quelque sorte, occasion d\'apprendre, si vous voulez.', isCorrect: true },
      { sentence: 'You see, the problem, such as it is, boils down to a question of timing — or rather, the lack thereof.', translation: 'Voyez-vous, le problème, tel qu\'il est, se résume à une question de timing — ou plutôt, l\'absence de celui-ci.', isCorrect: true },
      { sentence: 'Sort of, I think that maybe the plan could arguably work, kind of.', translation: '', isCorrect: false },
      { sentence: 'For what it\'s worth, I rather think she has a point — though I grant you the evidence is thin.', translation: 'Pour ce que ça vaut, je pense plutôt qu\'elle a raison — bien que j\'accorde que les preuves sont minces.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'Sort of, I think that maybe the plan could arguably work, kind of.', correct: 'I think the plan could work, sort of — or arguably, at any rate.', explanation: 'Empiler les hedges ("sort of" + "maybe" + "arguably" + "kind of") non seulement crée une phrase agrammaticale en position initiale ("Sort of, I think") mais étouffe le contenu propositionnel sous les atténuations. À C2, on place les hedges stratégiquement — un ou deux suffisent — pas en accumulation désordonnée.' },
      { wrong: 'He is quite brilliant — he is only moderately intelligent.', correct: 'He is quite brilliant. (British: moderately brilliant / American: very brilliant)', explanation: '"Quite" en anglais britannique est un hedge signifiant "plutôt / passablement", donc "quite brilliant" = "assez brillant". En américain, "quite" renforce : "quite brilliant" = "très brillant". Ne confondez pas ces deux valeurs. Si vous voulez dire "très brillant" en britannique, dites "absolutely brilliant" ou "rather brilliant".' },
    ],
  },
  conversation: [
    { speaker: 'Catherine', role: 'A', text: 'Well, I mean, if you must know, I wasn\'t exactly thrilled with how things panned out. Fair enough, the outcome was acceptable — just not quite what I\'d had in mind.', translation: 'Eh bien, je veux dire, si tu veux vraiment savoir, je n\'étais pas exactement ravie de la façon dont les choses se sont passées. Soit, le résultat était acceptable — juste pas tout à fait ce que j\'avais en tête.' },
    { speaker: 'James', role: 'B', text: 'Right. So when he said "we\'ll revisit this," what you heard was "this conversation is over and I\'ve won."', translation: 'C\'est ça. Donc quand il a dit « on y reviendra », ce que tu as entendu, c\'est « cette conversation est terminée et j\'ai gagné ».' },
    { speaker: 'Catherine', role: 'A', text: 'By the by, that phrase of his — "let\'s take this offline" — I rather think it\'s the single most passive-aggressive construction in the corporate lexicon.', translation: 'Au passage, cette phrase de lui — « prenons ça hors ligne » — je pense plutôt que c\'est la construction la plus passivo-agressive de tout le lexique corporate.' },
    { speaker: 'James', role: 'B', text: 'For what it\'s worth, you\'re not alone in thinking that. Anyway, the question is whether to push back now or bide our time.', translation: 'Pour ce que ça vaut, tu n\'es pas seul à penser ça. Bref, la question est de savoir s\'il faut répliquer maintenant ou prendre notre temps.' },
    { speaker: 'Catherine', role: 'A', text: 'Now then, that\'s the real dilemma, isn\'t it? Push too hard and we\'re seen as difficult. Say nothing and we\'re complicit in our own marginalisation.', translation: 'Bon alors, c\'est le vrai dilemme, n\'est-ce pas ? Pousser trop fort et on nous trouve difficiles. Ne rien dire et nous sommes complices de notre propre marginalisation.' },
    { speaker: 'James', role: 'B', text: 'Sort of a lose-lose, if you like. Though I dare say there\'s a third way — the art of the strategic silence followed by a well-timed "I rather think we\'re missing something."', translation: 'En quelque sorte, une situation perdant-perdant, si vous voulez. Bien que j\'ose dire qu\'il y a une troisième voie — l\'art du silence stratégique suivi d\'un « je pense plutôt qu\'on nous échappe quelque chose » bien calé.' },
    { speaker: 'Catherine', role: 'A', text: 'You know, for a man who claims not to do office politics, you\'re rather good at them. Not that I\'m insinuating anything, of course.', translation: 'Tu sais, pour un homme qui prétend ne pas faire de politique de bureau, tu es plutôt doué. Non que j\'insinue quoi que ce soit, bien sûr.' },
  ],
  conversationTitle: 'L\'art de la conversation native',
  pronunciation: [
    { word: 'By the by', phonetic: '/baɪ ðə baɪ/', meaning: 'Au passage', tip: 'Expression idiomatique liée : "baï-thuh-baï". Le "the" est réduit à "thuh". Ne faites pas de pause entre les mots — c\'est une unité prosodique unique. Plus naturel que "incidentally" en conversation.' },
    { word: 'Fair enough', phonetic: '/fɛər ɪˈnʌf/', meaning: 'Soit / C\'est entendu', tip: 'Liaison naturelle : "fair-ih-nuf". Le "e" de "enough" se prononce "ih". Le "ough" = "uf" comme dans "rough". L\'ensemble se dit d\'un ton concessif, avec une légère chute de la voix.' },
    { word: 'Now then', phonetic: '/naʊ ðɛn/', meaning: 'Bon alors', tip: 'Ne dites PAS "now" puis "then" séparément. C\'est une seule unité intonative : "NAU-dhen". Le "th" est doux (voisé). La voyelle de "then" est brève. Utilisé pour ouvrir un nouveau sujet ou recentrer la conversation.' },
    { word: 'Rather', phonetic: '/ˈrɑːðər/', meaning: 'Plutôt', tip: 'En britannique : "RAH-ther" avec le "th" doux et le "er" final allongé. En américain : "rath-er" plus bref. Le sens litotique britannique exige une intonation descendante savoureuse : "That\'s ↘rather good" = c\'est en fait excellent.' },
  ],
}

// ─── c2-l69: Complete Fluency — Perfecting subtle sound distinctions ──────────
export const C2_L69: LessonContent = {
  vocab: [
    { english: 'Intrusion', french: 'Intrusion phonologique', phonetic: '/ɪnˈtruːʒən/', example: 'The intrusion of an "r" sound in "law(r) and order" is a feature of non-rhotic connected speech.', exampleTranslation: 'L\'intrusion d\'un son « r » dans « law(r) and order » est une caractéristique de la parole connectée non rhotique.' },
    { english: 'Assimilation', french: 'Assimilation', phonetic: '/əˌsɪmɪˈleɪʃən/', example: 'Assimilation turns "ten boys" into "tem boys" as the tongue anticipates the following bilabial consonant.', exampleTranslation: 'L\'assimilation transforme « ten boys » en « tem boys » alors que la langue anticipe la consonne bilabiale suivante.' },
    { english: 'Catenation', french: 'Enchaînement', phonetic: '/ˌkætɪˈneɪʃən/', example: 'Catenation links the final consonant of one word to the initial vowel of the next: "get up" becomes "ge-tup."', exampleTranslation: 'L\'enchaînement lie la consonne finale d\'un mot à la voyelle initiale du suivant : « get up » devient « ge-tup ».' },
    { english: 'Juncture', french: 'Joncture phonologique', phonetic: '/ˈdʒʌŋktʃər/', example: 'Juncture — the phonetic cues that signal word boundaries — distinguishes "nitrate" from "night rate" in connected speech.', exampleTranslation: 'La joncture — les indices phonétiques qui signalent les frontières des mots — distingue « nitrate » de « night rate » dans la parole connectée.' },
    { english: 'Liaison', french: 'Liaison', phonetic: '/liˈeɪzɒn/', example: 'In fluent English, liaison between words creates a seamless flow that masks word boundaries entirely.', exampleTranslation: 'En anglais courant, la liaison entre les mots crée un flux continu qui masque entièrement les frontières des mots.' },
  ],
  grammar: {
    title: 'Connected Speech: Elision, Assimilation, and Weak Forms at Mastery Level',
    explanation: 'La parole connectée (connected speech) en anglais est un phénomène phonologique de niveau supérieur qui transforme radicalement la réalisation des mots en contexte. Trois processus dominent : (1) L\'élision — suppression de phonèmes : "next day" → "neks day", "give me" → "gimme", "going to" → "gonna". (2) L\'assimilation — modification d\'un son sous l\'influence du son voisin : "don\'t you" → "donchoo", "would you" → "woujoo", "in bed" → "im bed" (assimilation régressive). (3) Les formes faibles (weak forms) — réduction des voyelles inaccentuées en schwa /ə/ : "I was going to" → "I wuz gunnuh", "cup of tea" → "cuppa tea", "fish and chips" → "fish\'n\'chips". À C2, il ne s\'agit plus simplement de comprendre ces phénomènes mais de les produire spontanément. La distinction subtile entre "can" /kən/ (forme faible) et "can\'t" /kɑːnt/ repose souvent uniquement sur la longueur vocalique et la présence du "t" final. De même, "have" /həv/ en forme faible versus "have" /hæv/ en forme forte change le rythme entier de l\'énoncé. La maîtrise de ces distinctions est ce qui confère une fluidité quasi-native.',
    examples: [
      { sentence: 'I\'m going to have to ask you to leave. → "Ahm gonna hafta ask yuh tuh leave."', translation: 'Je vais devoir vous demander de partir.', isCorrect: true },
      { sentence: 'Don\'t you think it would be better? → "Donchoo think it wou\'be better?"', translation: 'Ne penses-tu pas que ce serait mieux ?', isCorrect: true },
      { sentence: 'I can do it /kæn duː ɪt/ in formal speech.', translation: '', isCorrect: false },
      { sentence: 'She could have told us, but she didn\'t. → "She coudda told us, but she didn\'t."', translation: 'Elle aurait pu nous le dire, mais elle ne l\'a pas fait.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'I can do it /kæn duː ɪt/ in formal speech.', correct: 'I can do it /kən duː ɪt/ — the weak form of "can" is /kən/, and the strong form /kæn/ is used only for emphasis or contrast.', explanation: 'En parole naturelle, "can" se réalise presque toujours en forme faible /kən/. N\'utiliser QUE la forme forte /kæn/ sonne artificiel et non-natif. La forme forte ne s\'emploie que pour l\'emphase : "I CAN do it (contraste avec l\'idée que je ne le peux pas)". La distinction entre "can" /kən/ et "can\'t" /kɑːnt/ repose sur la voyelle ET le "t" final.' },
      { wrong: 'She could of told us.', correct: 'She could have told us. (Pronounced: "She coudda told us")', explanation: 'La forme faible de "have" /həv/ ou /əv/ après un modal est phonétiquement proche de "of" /əv/, d\'où l\'erreur orthographique fréquente "could of". À l\'écrit, c\'est TOUJOURS "could have" (ou "could\'ve"). Mais à l\'oral, la réalisation "coudda" est parfaitement naturelle et attendue à C2.' },
    ],
  },
  conversation: [
    { speaker: 'Rhiannon', role: 'A', text: 'You\'ve gotta hand it to her — she could\'ve just phoned it in, but instead she went and delivered the whole thing from memory. Not a single note.', translation: 'Il faut lui reconnaître ça — elle aurait pu faire le minimum, mais à la place elle a livré tout ça de mémoire. Pas une seule note.' },
    { speaker: 'Tomás', role: 'B', text: 'Could\'a fooled me. I mean, I would\'ve sworn she was reading — the delivery was that smooth. Sort of makes you wonder why the rest of us bother with notes at all.', translation: 'Elle m\'aurait eu. Je veux dire, j\'aurais juré qu\'elle lisait — la livraison était tellement fluide. Ça te fait un peu te demander pourquoi le reste d\'entre nous s\'embête avec des notes.' },
    { speaker: 'Rhiannon', role: 'A', text: 'Right? Anyway, d\'you reckon she\'s gonna go for the senior role? Seems like a bit of a no-brainer, if you ask me.', translation: 'Non ? Bref, tu penses qu\'elle va viser le poste senior ? Ça semble être une évidence, si tu me demandes.' },
    { speaker: 'Tomás', role: 'B', text: 'Dunno. She might\'a been put off by all the, y\'know, office politics. Fair enough if she has, mind you — not everyone\'s cut out for that sort of thing.', translation: 'Sais pas. Elle a peut-être été refroidie par toute la, tu sais, politique de bureau. C\'est compréhensible si c\'est le cas, note bien — tout le monde n\'est pas fait pour ce genre de chose.' },
    { speaker: 'Rhiannon', role: 'A', text: 'True enough. But then again, if you don\'t put yourself forward, you can\'t exactly complain about being overlooked, can you?', translation: 'C\'est vrai. Mais d\'un autre côté, si tu ne te proposes pas, tu ne peux pas vraiment te plaindre d\'être ignorée, si ?' },
    { speaker: 'Tomás', role: 'B', text: 'Sort of a catch-22, isn\'t it? You\'re damned if you do and overlooked if you don\'t. For what it\'s worth, I think she should go for it — she\'s more than up to the job.', translation: 'En quelque sorte un cercle vicieux, non ? Tu es damné si tu le fais et ignoré si tu ne le fais pas. Pour ce que ça vaut, je pense qu\'elle devrait y aller — elle est plus qu\'à la hauteur du poste.' },
    { speaker: 'Rhiannon', role: 'A', text: 'Well, I\'ll hafta mention that next time I see her. Not that she needs my permission, but a word in the right direction never hurt anyone.', translation: 'Eh bien, je devrai en parler la prochaine fois que je la vois. Non qu\'elle ait besoin de ma permission, mais un mot dans la bonne direction n\'a jamais fait de mal à personne.' },
  ],
  conversationTitle: 'Parole connectée et fluidité native',
  pronunciation: [
    { word: 'Intrusion', phonetic: '/ɪnˈtruːʒən/', meaning: 'Intrusion phonologique', tip: 'Accent sur "TRU" : in-TROO-zhun. Le "u" accentué est long comme dans "blue". Le "sion" final = "zhun" comme dans "vision". Ne dites pas "in-tru-zee-on" à la française.' },
    { word: 'Juncture', phonetic: '/ˈdʒʌŋktʃər/', meaning: 'Joncture phonologique', tip: 'Accent sur "JUNC" : JUNK-chur. Le "u" est ouvert comme dans "cup". Le "ture" = "chur" comme dans "nature". La joncture désigne les indices phonétiques aux frontières des mots.' },
    { word: 'Catenation', phonetic: '/ˌkætɪˈneɪʃən/', meaning: 'Enchaînement', tip: 'Accent sur "nay" : kat-ih-NAY-shun. Le "tion" = "shun". Le "cat" se prononce comme dans "cat" (animal). L\'accent principal est sur l\'avant-dernière syllabe.' },
    { word: 'Assimilation', phonetic: '/əˌsɪmɪˈleɪʃən/', meaning: 'Assimilation', tip: 'Accent sur "lay" : uh-sim-ih-LAY-shun. Le "a" initial est réduit en schwa. Les 5 syllabes se déroulent rapidement — ne ralentissez pas sur les syllabes secondaires. Le "tion" = "shun".' },
  ],
}

// ─── c2-l70: Mastery Sounds — Ultimate fluency, natural rhythm and flow ──────
export const C2_L70: LessonContent = {
  vocab: [
    { english: 'Intonation contour', french: 'Contour intonatif', phonetic: '/ˌɪntəˈneɪʃən ˈkɒntʊr/', example: 'The intonation contour of a sentence — its rising and falling pitch pattern — conveys meaning that no dictionary can capture.', exampleTranslation: 'Le contour intonatif d\'une phrase — son schéma de hauteur montante et descendante — transmet un sens qu\'aucun dictionnaire ne peut saisir.' },
    { english: 'Rhythmic pattern', french: 'Motif rythmique', phonetic: '/ˈrɪðmɪk ˈpætərn/', example: 'The rhythmic pattern of his closing argument — measured, deliberate, unyielding — left the jury in no doubt about his conviction.', exampleTranslation: 'Le motif rythmique de sa plaidoirie finale — mesuré, délibéré, inébranlable — n\'a laissé aucun doute au jury sur sa conviction.' },
    { english: 'Pitch contour', french: 'Contour mélodique', phonetic: '/ˈpɪtʃ ˈkɒntʊr/', example: 'A rising pitch contour on "really?" can signal anything from genuine surprise to barely concealed scepticism.', exampleTranslation: 'Un contour mélodique montant sur « really ? » peut signaler n\'importe quoi, de la surprise sincère au scepticisme à peine dissimulé.' },
    { english: 'Phrasing', french: 'Phrasé', phonetic: '/ˈfreɪzɪŋ/', example: 'Her phrasing — the way she grouped certain words together and let others hang — revealed more than the words themselves.', exampleTranslation: 'Son phrasé — la façon dont elle regroupait certains mots et laissait les autres en suspens — a révélé plus que les mots eux-mêmes.' },
    { english: 'Tempo', french: 'Tempo', phonetic: '/ˈtɛmpoʊ/', example: 'A sudden shift in tempo — accelerating through the familiar, slowing for the unexpected — can transform a mundane anecdote into gripping narrative.', exampleTranslation: 'Un changement soudain de tempo — accélérant dans le familier, ralentissant pour l\'inattendu — peut transformer une anecdote banale en un récit captivant.' },
  ],
  grammar: {
    title: 'Prosodic Mastery: Rhythm, Intonation, and the Music of Native English',
    explanation: 'La prosodie — l\'étude du rythme, de l\'intonation, du tempo et de l\'accentuation dans la parole — est l\'ultime frontière entre un locuteur avancé et un locuteur quasi-natif. L\'anglais est une langue stress-timed (à rythme accentuel) : les syllabes accentuées arrivent à intervalles réguliers, et les syllabes inaccentuées sont compressées pour maintenir ce rythme. Comparez : "The MAN at the BUS stop was READing a NEWS-pa-per" — chaque syllabe capitale tombe sur le beat, les autres se contractent. L\'intonation anglaise suit des contours précis : le "high-rise terminal" (montée finale) signale un doute ou une question ; le "low-fall" (chute basse) affirme avec finalité ; le "fall-rise" (chute puis remontée) implique un sous-entendu ("I wouldn\'t say ↘no↗" = je suis plutôt d\'accord) ; le "rise-fall" (montée puis chute) exprime la surprise ou l\'intensité ("You\'re ↗kidding↘!" = incroyable !). Le tempo est un outil rhétorique : ralentir signale l\'importance ou l\'hésitation ; accélérer crée l\'urgence ou l\'enchaînement. Enfin, le groupement intonatif (phrasing) — la façon dont on regroupe les mots en unités de sens à travers des pauses et des contours mélodiques — est ce qui rend la parole fluide et compréhensible. Un locuteur C2 ne lit pas les mots un par un : il les organise en vagues prosodiques qui guident l\'écoute du destinataire.',
    examples: [
      { sentence: 'She said she was ↘fine↗. (fall-rise = she probably wasn\'t fine)', translation: 'Elle a dit qu\'elle allait bien. (chute-remontée = elle n\'allait probablement pas bien)', isCorrect: true },
      { sentence: 'It\'s not that I ↘mind↗ — I just think there might be a better way. (fall-rise = polite disagreement)', translation: 'Ce n\'est pas que ça me dérange — je pense juste qu\'il pourrait y avoir une meilleure façon.', isCorrect: true },
      { sentence: 'She said she was ↗fine↘. (rise-fall = she was genuinely fine, no doubt about it)', translation: 'Elle a dit qu\'elle allait très bien. (montée-chute = elle allait vraiment bien, sans aucun doute)', isCorrect: true },
      { sentence: 'He speaks English good.', translation: '', isCorrect: false },
    ],
    commonMistakes: [
      { wrong: 'He speaks English good.', correct: 'He speaks English well.', explanation: 'Cette erreur est apparemment simple mais révélatrice : "good" est un adjectif, "well" est l\'adverbe nécessaire pour modifier un verbe. À C2, ce genre d\'erreur n\'est plus grammatical mais prosodique : un locuteur natif dirait "well" avec une intonation descendante conclusive, alors qu\'un francophone pourrait dire "good" avec une intonation plate. La prosodie révèle la compétence réelle même quand la grammaire est correcte.' },
      { wrong: 'Using flat intonation throughout a sentence: "I was going to the store and I bought some milk."', correct: 'Using varied intonation: "I was going to the ↘STORE↗ — and I bought some ↘MILK↘."', explanation: 'L\'intonation plate (monotone) est le marqueur le plus révélateur d\'un locuteur non-natif, même avancé. L\'anglais natif utilise des contours mélodiques variés : la chute sur "STORE" marque une pause, la remontée signale que la phrase continue, et la chute finale sur "MILK" clôt l\'énoncé. Sans ces contours, même une phrase grammaticalement parfaite sonne « étrangère ».' },
    ],
  },
  conversation: [
    { speaker: 'Dr. Whitfield', role: 'A', text: 'You know what I find fascinating? The way a perfectly grammatical sentence can sound entirely wrong — not because of the words, but because of the music behind them.', translation: 'Tu sais ce que je trouve fascinant ? La façon dont une phrase parfaitement grammaticale peut sonner entièrement fausse — pas à cause des mots, mais à cause de la musique derrière eux.' },
    { speaker: 'Amara', role: 'B', text: 'Prosody. It\'s everything, isn\'t it? I mean, you can take "I wouldn\'t know" and make it sound anywhere from genuinely humble to barely concealed disdain — purely through intonation.', translation: 'La prosodie. C\'est tout, non ? Je veux dire, tu peux prendre « I wouldn\'t know » et le faire sonner de la véritable humilité au mépris à peine dissimulé — purement par l\'intonation.' },
    { speaker: 'Dr. Whitfield', role: 'A', text: 'Exactly. The fall-rise on "wouldn\'t" — ↘wouldn\'t↗ — tells the whole story. It\'s the English way of disagreeing without appearing to disagree. A kind of verbal aikido.', translation: 'Exactement. La chute-remontée sur « wouldn\'t » — ↘wouldn\'t↗ — raconte toute l\'histoire. C\'est la façon anglaise de ne pas être d\'accord sans paraître ne pas être d\'accord. Une sorte d\'aïkido verbal.' },
    { speaker: 'Amara', role: 'B', text: 'And tempo, too. I\'ve noticed that when native speakers want to sound authoritative, they slow right down. It\'s almost — not a pause, but a, what would you call it, a deliberate weighting of each syllable.', translation: 'Et le tempo aussi. J\'ai remarqué que quand les locuteurs natifs veulent paraître autoritaires, ils ralentissent beaucoup. C\'est presque — pas une pause, mais un, comment diriez-vous, un lancement délibéré de chaque syllabe.' },
    { speaker: 'Dr. Whitfield', role: 'A', text: 'Phrasing, I think, is the word you\'re reaching for. The way you group words into prosodic phrases — that\'s what creates the sense of flow. Without it, you get that staccato effect that marks even very fluent non-native speakers.', translation: 'Le phrasé, je pense, est le mot que vous cherchez. La façon dont on regroupe les mots en phrases prosodiques — c\'est ce qui crée le sentiment de fluidité. Sans ça, on obtient cet effet staccato qui marque même les locuteurs non-natifs très fluides.' },
    { speaker: 'Amara', role: 'B', text: 'That\'s it exactly — staccato. Each word standing alone rather than flowing into the next. It\'s like the difference between reading music note by note and playing a phrase with genuine legato.', translation: 'C\'est exactement ça — staccato. Chaque mot se tenant seul plutôt que de couler dans le suivant. C\'est comme la différence entre lire la musique note par note et jouer une phrase avec un véritable legato.' },
    { speaker: 'Dr. Whitfield', role: 'A', text: 'And that, I rather think, is the final frontier. Grammar can be taught, vocabulary can be memorised — but cadence, phrasing, the music of the thing? That requires not just study, but immersion in the very rhythm of a culture.', translation: 'Et ça, je pense plutôt, est la frontière finale. La grammaire peut être enseignée, le vocabulaire peut être mémorisé — mais la cadence, le phrasé, la musique de la chose ? Cela exige non seulement de l\'étude, mais une immersion dans le rythme même d\'une culture.' },
    { speaker: 'Amara', role: 'B', text: 'Well said. And if that\'s the case, then true near-native fluency isn\'t a destination — it\'s a lifelong practice. Rather like music itself.', translation: 'Bien dit. Et si c\'est le cas, alors la véritable fluidité quasi-native n\'est pas une destination — c\'est une pratique lifelong. Plutôt comme la musique elle-même.' },
  ],
  conversationTitle: 'La musique de l\'anglais natif',
  pronunciation: [
    { word: 'Intonation contour', phonetic: '/ˌɪntəˈneɪʃən ˈkɒntʊr/', meaning: 'Contour intonatif', tip: 'Accent sur "nay" dans "intonation" et sur "CON" dans "contour" : in-tuh-NAY-shun KON-tour. Le "tion" = "shun". Le "ou" dans "contour" est ouvert comme dans "four". L\'ensemble désigne le schéma de hauteur montante et descendante d\'une phrase.' },
    { word: 'Rhythmic pattern', phonetic: '/ˈrɪðmɪk ˈpætərn/', meaning: 'Motif rythmique', tip: 'Accent sur "RITH" dans "rhythmic" et sur "PAT" dans "pattern" : RITH-mik PAT-ern. Le "y" de "rhythm" ne se prononce pas comme une voyelle séparée. Le "er" dans "pattern" est réduit. Désigne la structure rythmique récurrente de la parole.' },
    { word: 'Pitch contour', phonetic: '/ˈpɪtʃ ˈkɒntʊr/', meaning: 'Contour mélodique', tip: 'Accent sur "PITCH" et sur "CON" dans "contour" : PITCH KON-tour. Le "i" dans "pitch" est bref comme dans "bit". Le "ou" dans "contour" est ouvert. Désigne le parcours mélodique de la voix à travers une phrase.' },
    { word: 'Tempo', phonetic: '/ˈtɛmpoʊ/', meaning: 'Tempo', tip: 'Accent sur la première syllabe : TEM-poh. Le "e" est ouvert comme dans "pet". Le "o" final est long. Ce mot italien est anglicisé : ne dites pas "tem-po" à l\'italienne avec un "o" bref. L\'anglais l\'allonge.' },
  ],
}
