import type { LessonContent } from './lesson-content'

// ════════════════════════════════════════════════════════════════════════════════
// C2 MASTERY — UNIT 3: PHILOSOPHICAL DISCOURSE (c2-u3)
// Lessons c2-l11 through c2-l15
// YOELANG English Learning App for Francophone Users
// Near-native mastery: existentialism, phenomenology, determinism
// ════════════════════════════════════════════════════════════════════════════════

// ─── c2-l11: Philosophy Vocabulary — Existentialism, phenomenology, determinism ──
export const C2_L11: LessonContent = {
  vocab: [
    { english: 'Determinism', french: 'Déterminisme', phonetic: '/dɪˈtɜːrmɪnɪzəm/', example: 'Determinism posits that all events are predetermined by prior causes.', exampleTranslation: 'Le déterminisme pose que tous les événements sont prédéterminés par des causes antérieures.' },
    { english: 'Existentialism', french: 'Existentialisme', phonetic: '/ˌɛɡzɪˈstɛnʃəlɪzəm/', example: 'Existentialism emphasizes individual freedom and choice as the source of meaning.', exampleTranslation: 'L\'existentialisme souligne la liberté et le choix individuels comme source de sens.' },
    { english: 'Dualism', french: 'Dualisme', phonetic: '/ˈdjuːəlɪzəm/', example: 'Dualism posits a fundamental distinction between mind and body.', exampleTranslation: 'Le dualisme pose une distinction fondamentale entre l\'esprit et le corps.' },
    { english: 'Solipsism', french: 'Solipsisme', phonetic: '/ˈsɒlɪpsɪzəm/', example: 'Solipsism presents a radical challenge to any claim of shared reality.', exampleTranslation: 'Le solipsisme présente un défi radical à toute affirmation d\'une réalité partagée.' },
    { english: 'Nihilism', french: 'Nihilisme', phonetic: '/ˈnaɪɪlɪzəm/', example: 'Nihilism rejects the notion that life has inherent meaning or moral principles.', exampleTranslation: 'Le nihilisme rejette l\'idée que la vie a un sens inhérent ou des principes moraux.' },
  ],
  grammar: {
    title: 'Modal Verbs of Speculation and Philosophical Hedging',
    explanation: 'En philosophie académique, on utilise les modaux de spéculation pour nuancer les affirmations sans les présenter comme des vérités absolues. "Must" exprime une déduction logique forte (il faut nécessairement que), "might" et "could" indiquent une possibilité (il se pourrait que), "should" suggère une probabilité raisonnable (il devrait logiquement), et "would" exprime une conséquence hypothétique (il s\'ensuivrait que). À niveau C2, on combine ces modaux avec des constructions parfaites : "must have been", "could conceivably have", "might well prove to be". Ce hedge linguistique est essentiel dans le discours philosophique anglo-saxon, où l\'on évite systématiquement les assertions non qualifiées.',
    examples: [
      { sentence: 'The argument must presuppose an ontological commitment to realism.', translation: 'L\'argument doit nécessairement présupposer un engagement ontologique envers le réalisme.', isCorrect: true },
      { sentence: 'One might reasonably contend that consciousness could be irreducible.', translation: 'On pourrait raisonnablement soutenir que la conscience pourrait être irréductible.', isCorrect: true },
      { sentence: 'The theory must to imply a solipsistic conclusion.', translation: '', isCorrect: false },
      { sentence: 'Such a position would seem to undermine the very foundations of determinism.', translation: 'Une telle position semblerait saper les fondements mêmes du déterminisme.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'The theory must to imply a solipsistic conclusion.', correct: 'The theory must imply a solipsistic conclusion.', explanation: 'Après un modal (must, might, could, should, would), on utilise la base verbale sans "to" : "must imply", pas "must to imply". C\'est une erreur fréquente même à niveau avancé, surtout sous la pression de l\'expression académique.' },
      { wrong: 'It could has been the case that phenomenology preceded existentialism.', correct: 'It could have been the case that phenomenology preceded existentialism.', explanation: 'Le modal parfait se construit avec "have" + participe passé, jamais "has" : "could have been", pas "could has been". Cette erreur survient souvent quand on veut accorder "have" avec le sujet.' },
    ],
  },
  conversation: [
    { speaker: 'Dr. Ashworth', role: 'A', text: 'One might argue that determinism, as traditionally conceived, presupposes a causal necessity that free will ultimately calls into question.', translation: 'On pourrait soutenir que le déterminisme, tel qu\'il est traditionnellement conçu, présuppose une nécessité causale que le libre arbitre remet finalement en question.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'That is a fair observation, though I would contend that Husserl\'s bracketing of the natural attitude doesn\'t so much dissolve the dichotomy as suspend its presuppositions.', translation: 'C\'est une observation juste, bien que je soutiendrais que la mise entre parenthèses hussérienne de l\'attitude naturelle ne dissout pas tant la dichotomie qu\'elle n\'en suspend les présupposés.' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'Granted. Yet must we not acknowledge that the very act of epoché implicitly affirms a transcendental subject whose existence ontological inquiry cannot bypass?', translation: 'Accordé. Cependant, ne devons-nous pas reconnaître que l\'acte même de l\'epoché affirme implicitement un sujet transcendantal dont l\'existence l\'inquiry ontologique ne peut contourner ?' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'That is precisely where Heidegger\'s critique gains traction. He might well argue that Husserl remains trapped within a Cartesian framework, however subtly reconfigured.', translation: 'C\'est précisément là que la critique de Heidegger gagne en pertinence. Il pourrait bien soutenir que Husserl reste piégé dans un cadre cartésien, aussi subtilement reconfiguré soit-il.' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'Which would bring us back to the teleological question: is the project of grounding knowledge itself a species of philosophical overreach?', translation: 'Ce qui nous ramènerait à la question téléologique : le projet de fonder la connaissance est-il lui-même une forme d\'outrecuidance philosophique ?' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'Now you are edging toward a Rortyan ironic stance. And perhaps that is where the debate must ultimately reside — in the recognition that our epistemic frameworks are, at best, contingent vocabularies.', translation: 'Vous vous approchez maintenant d\'une posture rortyenne ironique. Et c\'est peut-être là que le débat doit en fin de compte résider — dans la reconnaissance que nos cadres épistémiques ne sont, au mieux, que des vocabulaires contingents.' },
  ],
  conversationTitle: 'Le déterminisme et ses présupposés',
  pronunciation: [
    { word: 'Determinism', phonetic: '/dɪˈtɜːrmɪnɪzəm/', meaning: 'Déterminisme', tip: 'Accent principal sur "TER" : dih-TER-min-iz-um. Le "e" initial est réduit. Le "i" de "min" est bref. Le suffixe "-ism" se prononce "iz-um". Ne dites pas "deh-ter-mee-niz-em".' },
    { word: 'Phenomenology', phonetic: '/fɪˌnɒmɪˈnɒlədʒi/', meaning: 'Phénoménologie', tip: 'Accent sur "nol" : fi-nom-i-NOL-uh-jee. Le "ph" initial = "f". Attention : en français on dit "fé-no-mé-no-lo-jie", mais l\'anglais place l\'accent tonique différemment.' },
    { word: 'Ontological', phonetic: '/ˌɒntəˈlɒdʒɪkəl/', meaning: 'Ontologique', tip: 'Accent sur "loj" : on-tuh-LOJ-ik-ul. Le premier "o" est ouvert comme dans "on". Le suffixe "-ical" se prononce "ik-ul" avec l\'accent sur l\'avant-dernière syllabe.' },
    { word: 'Solipsism', phonetic: '/ˈsɒlɪpsɪzəm/', meaning: 'Solipsisme', tip: 'Accent sur la première syllabe : SOL-ip-siz-um. Le "psi" se prononce "psi" comme dans "psychology". Ne dites pas "so-lip-sizm" — l\'accent est sur "SOL".' },
  ],
}

// ─── c2-l12: Abstract Argumentation — Modal verbs of speculation, conditional perfection ──
export const C2_L12: LessonContent = {
  vocab: [
    { english: 'Dialectical', french: 'Dialectique', phonetic: '/ˌdaɪəˈlektɪkəl/', example: 'A dialectical approach reveals the internal contradictions within the thesis.', exampleTranslation: 'Une approche dialectique révèle les contradictions internes au sein de la thèse.' },
    { english: 'Conundrum', french: 'Énigme', phonetic: '/kəˈnʌndrəm/', example: 'The mind-body problem remains a philosophical conundrum that defies simple resolution.', exampleTranslation: 'Le problème corps-esprit reste une énigme philosophique qui défie toute résolution simple.' },
    { english: 'Presupposition', french: 'Présupposition', phonetic: '/ˌpriːsʌpəˈzɪʃən/', example: 'Every argument carries implicit presuppositions about the nature of truth.', exampleTranslation: 'Chaque argument porte des présuppositions implicites sur la nature de la vérité.' },
    { english: 'Tautology', french: 'Tautologie', phonetic: '/tɔːˈtɒlədʒi/', example: 'To define consciousness as conscious experience is to commit a tautology.', exampleTranslation: 'Définir la conscience comme expérience consciente, c\'est commettre une tautologie.' },
    { english: 'Corollary', french: 'Corollaire', phonetic: '/ˈkɒrələri/', example: 'A necessary corollary of this position is the denial of free will.', exampleTranslation: 'Un corollaire nécessaire de cette position est la négation du libre arbitre.' },
  ],
  grammar: {
    title: 'Conditional Perfection and Counterfactual Reasoning',
    explanation: 'La "conditional perfection" est un phénomène linguistique par lequel un énoncé conditionnel est interprété comme une implication bidirectionnelle (biconditionnelle). Par exemple, "If P then Q" est logiquement unidirectionnel, mais on le comprend souvent comme "If and only if P, then Q". En philosophie analytique, cette distinction est cruciale. Les conditionnels contrefactuels ("If it had been the case that P, then Q would have been the case") permettent de raisonner sur des états de choses non réalisés. À niveau C2, on maîtrise les constructions : "Were it the case that...", "Should one concede that...", "Had it not been for..." (inversion conditionnelle formelle), ainsi que les nuances entre "would", "could" et "might" dans les subordonnées contrefactuelles. L\'inversion du sujet et de l\'auxiliaire sans "if" est un marqueur de registre académique élevé.',
    examples: [
      { sentence: 'Were one to accept the premise, the conclusion would inexorably follow.', translation: 'Si l\'on acceptait la prémisse, la conclusion suivrait inexorablement.', isCorrect: true },
      { sentence: 'Had the phenomenologists not bracketed the natural attitude, their project would have remained indistinguishable from empirical psychology.', translation: 'Si les phénoménologues n\'avaient pas mis entre parenthèses l\'attitude naturelle, leur projet serait resté indiscernable de la psychologie empirique.', isCorrect: true },
      { sentence: 'If it would have been the case that knowledge is impossible, all inquiry would be futile.', translation: '', isCorrect: false },
      { sentence: 'Should this argument prove sound, its corollary would undermine the very possibility of moral realism.', translation: 'Si cet argument s\'avérait valide, son corollaire saperait la possibilité même du réalisme moral.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'If it would have been the case that knowledge is impossible, all inquiry would be futile.', correct: 'If it had been the case that knowledge is impossible, all inquiry would be futile.', explanation: 'Dans la protase (subordonnée conditionnelle) d\'un contrefactuel passé, on utilise le past perfect ("had been"), jamais "would have". "Would" apparaît uniquement dans l\'apodose (principale). C\'est l\'erreur classique du "would-would" que même les locuteurs natifs commettent parfois.' },
      { wrong: 'Were one to accept the premise, the conclusion will inexorably follow.', correct: 'Were one to accept the premise, the conclusion would inexorably follow.', explanation: 'Après une protase hypothétique au subjonctif ("Were one to..."), la principale doit utiliser un conditionnel ("would follow"), pas un futur ("will follow"). L\'hypothétique exige la concordance des temps : subjonctif → conditionnel.' },
    ],
  },
  conversation: [
    { speaker: 'Dr. Ashworth', role: 'A', text: 'Were we to accept the dialectical method as the sole arbiter of truth, we should find ourselves in a peculiar form of conundrum — for dialectics itself rests on presuppositions it cannot dialectically vindicate.', translation: 'Si nous acceptions la méthode dialectique comme seul arbitre de la vérité, nous nous trouverions dans une forme particulière d\'énigme — car la dialectique elle-même repose sur des présuppositions qu\'elle ne peut dialectiquement justifier.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'A compelling point, though one might counter that the very act of raising such an objection constitutes a dialectical move, thereby demonstrating the inescapability of the method.', translation: 'Un point convaincant, bien qu\'on puisse rétorquer que le fait même de soulever une telle objection constitue un geste dialectique, démontrant ainsi l\'inescapabilité de la méthode.' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'That, however, would be a tautology masquerading as a defence. To say that dialectics validates itself dialectically is no argument at all.', translation: 'Cela, cependant, serait une tautologie déguisée en défense. Dire que la dialectique se valide dialectiquement n\'est aucunement un argument.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'Had I not anticipated that rebuttal, I might have been disarmed. But consider the corollary: any alternative to dialectics must itself be argued for — and what is argument if not dialectical?', translation: 'Si je n\'avais pas anticipé cette réplique, j\'aurais pu être désarmé. Mais considérez le corollaire : toute alternative à la dialectique doit elle-même être argumentée — et qu\'est-ce que l\'argumentation sinon dialectique ?' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'You are invoking a performative criterion of rationality. Should that suffice, then the question becomes whether performativity itself presupposes a prior metaphysical commitment.', translation: 'Vous invoquez un critère performatif de rationalité. Si cela suffit, la question devient alors de savoir si la performativité elle-même présuppose un engagement métaphysique antérieur.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'And there we arrive at the properly philosophical question — one that neither dialectics nor its repudiation can settle in isolation. It demands, I think, a mode of inquiry that is itself self-reflexively transparent.', translation: 'Et c\'est là que nous arrivons à la question proprement philosophique — une question que ni la dialectique ni sa répudiation ne peuvent régler isolément. Elle exige, je pense, un mode d\'investigation qui soit lui-même réflexivement transparent.' },
  ],
  conversationTitle: 'Dialectique et présuppositions',
  pronunciation: [
    { word: 'Dialectical', phonetic: '/ˌdaɪəˈlektɪkəl/', meaning: 'Dialectique', tip: 'Accent sur "lek" : dy-uh-LEK-tik-ul. Le "di" se prononce "dy" comme dans "diameter". Ne dites pas "dee-uh-lek-tik-al".' },
    { word: 'Conundrum', phonetic: '/kəˈnʌndrəm/', meaning: 'Énigme', tip: 'Accent sur « NUN » : kuh-NUN-drum. Le « o » initial est réduit en schwa. Le « u » accentué est très ouvert comme dans « cup ». Le « um » final est bref.' },
    { word: 'Presupposition', phonetic: '/ˌpriːsʌpəˈzɪʃən/', meaning: 'Présupposition', tip: 'Accent secondaire sur "pre", accent principal sur "zi" : pree-sup-uh-ZISH-un. Le suffixe "-tion" se prononce "shun", jamais "tee-on" à la française.' },
    { word: 'Corollary', phonetic: '/ˈkɒrələri/', meaning: 'Corollaire', tip: 'Accent sur "cor" : KOR-uh-ler-ee. En anglais américain, on dit souvent "KOR-uh-lair-ee". Ne prononcez pas à la française "ko-ro-laire".' },
  ],
}

// ─── c2-l13: Philosophical Debate — High-level philosophical discussion ────────────
export const C2_L13: LessonContent = {
  vocab: [
    { english: 'Dialectics', french: 'Dialectique', phonetic: '/ˌdaɪəˈlɛktɪks/', example: 'Hegelian dialectics involves thesis, antithesis, and synthesis in the progression of ideas.', exampleTranslation: 'La dialectique hégélienne implique thèse, antithèse et synthèse dans la progression des idées.' },
    { english: 'Immanent', french: 'Immanent', phonetic: '/ˈɪmənənt/', example: 'Spinoza\'s God is wholly immanent within nature, not transcendent to it.', exampleTranslation: 'Le Dieu de Spinoza est totalement immanent à la nature, non transcendant à celle-ci.' },
    { english: 'Reductionism', french: 'Réductionnisme', phonetic: '/rɪˈdʌkʃənɪzəm/', example: 'Reductionism fails to account for emergent properties that arise at higher levels of complexity.', exampleTranslation: 'Le réductionnisme ne parvient pas à rendre compte des propriétés émergentes qui surviennent à des niveaux supérieurs de complexité.' },
    { english: 'Antinomy', french: 'Antinomie', phonetic: '/ænˈtɪnəmi/', example: 'Kant\'s antinomies reveal the paradoxes that arise when reason exceeds its legitimate bounds.', exampleTranslation: 'Les antinomies kantiennes révèlent les paradoxes qui surgissent quand la raison dépasse ses limites légitimes.' },
    { english: 'Verisimilitude', french: 'Vraisemblance', phonetic: '/ˌvɛrɪsɪˈmjuːlɪtjuːd/', example: 'Popper argued that scientific progress consists in increasing the verisimilitude of our theories.', exampleTranslation: 'Popper soutenait que le progrès scientifique consiste à accroître la vraisemblance de nos théories.' },
  ],
  grammar: {
    title: 'Discourse Markers of Philosophical Concession and Reformulation',
    explanation: 'Dans le débat philosophique de haut niveau, les marqueurs discursifs de concession et de reformulation sont essentiels pour construire une argumentation nuancée. "Admittedly" et "granted" concèdent un point (j\'admets que / accordé que), tandis que "nevertheless" et "be that as it may" rétablissent la thèse (néanmoins / quoi qu\'il en soit). "Insofar as" limite la portée d\'une affirmation (dans la mesure où), "mutatis mutandis" indique que les changements nécessaires ont été effectués (toutes choses égales par ailleurs), et "pace" introduit un désaccord respectueux (avec tout le respect que je dois à). À niveau C2, on emploie aussi "granted that...", "for all that...", et "be it said that..." comme constructions concessives inversées. Ces marqueurs permettent de naviguer entre thèse, antithèse et synthèse sans réduire la complexité de la pensée.',
    examples: [
      { sentence: 'Admittedly, structuralism offers a richer account of interpretation; nevertheless, it remains vulnerable to the charge of reductionism.', translation: 'J\'admets que le structuralisme offre un compte rendu plus riche de l\'interprétation ; néanmoins, il reste vulnérable à l\'accusation de réductionnisme.', isCorrect: true },
      { sentence: 'Pace the reductionist, consciousness cannot be explained away solely in terms of neural correlates.', translation: 'Avec tout le respect que je dois au réductionniste, la conscience ne peut être liquidée uniquement en termes de corrélats neuronaux.', isCorrect: true },
      { sentence: 'Granted the antinomy is irresoluble, so we must abandon the project entirely.', translation: '', isCorrect: false },
      { sentence: 'Insofar as verisimilitude is an intelligible goal, realism would appear to be the more rational commitment.', translation: 'Dans la mesure où la vraisemblance est un but intelligible, le réalisme semblerait être l\'engagement le plus rationnel.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'Granted the antinomy is irresoluble, so we must abandon the project entirely.', correct: 'Granted that the antinomy is irresoluble, we must abandon the project entirely.', explanation: '"Granted that..." introduit déjà une concession. Ajouter "so" crée une redondance car "granted that" établit une relation logique entre les deux propositions. On écrit "Granted that P, Q" sans connecteur supplémentaire.' },
      { wrong: 'Pace to the reductionist, consciousness cannot be explained away.', correct: 'Pace the reductionist, consciousness cannot be explained away.', explanation: '"Pace" est une préposition latine qui signifie "avec le respect dû à". On l\'utilise directement devant le nom sans "to" : "Pace X" (et non "Pace to X"). C\'est un usage académique calqué sur le latin ablative.' },
    ],
  },
  conversation: [
    { speaker: 'Dr. Ashworth', role: 'A', text: 'Admittedly, the structuralist framework is not without its insights — Lévi-Strauss has persuasively argued as much. Be that as it may, one must wonder whether the immanent standards of interpretation can ever secure an external warrant.', translation: 'J\'admets que le cadre structuraliste n\'est pas sans éclairages — Lévi-Strauss l\'a persuasivement soutenu. Quoi qu\'il en soit, on doit se demander si les standards immanents de l\'interprétation peuvent jamais garantir un fondement externe.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'That presupposes that an external warrant is requisite — which, pace your Cartesian instincts, need not be the case. Mutatis mutandis, the standards internal to a tradition may suffice.', translation: 'Cela présuppose qu\'un fondement externe est requis — ce qui, avec tout le respect que je dois à vos instincts cartésiens, n\'est pas nécessairement le cas. Toutes choses égales par ailleurs, les standards internes à une tradition peuvent suffire.' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'For all that, does such a position not collapse into a form of epistemic relativism? If there is no standpoint external to the tradition, how are we to adjudicate between competing interpretations?', translation: 'Malgré tout, une telle position ne s\'effondre-t-elle pas en une forme de relativisme épistémique ? S\'il n\'y a pas de point de vue externe à la tradition, comment devons-nous trancher entre des interprétations concurrentes ?' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'The antinomy you pose — relativism versus absolutism — may itself be a false dichotomy. Insofar as traditions overlap, they provide mutual intelligibility without requiring a God\'s-eye view.', translation: 'L\'antinomie que vous posez — relativisme versus absolutisme — peut être elle-même une fausse dichotomie. Dans la mesure où les traditions se chevauchent, elles fournissent une intelligibilité mutuelle sans exiger un point de vue de Dieu.' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'Granted that mutual intelligibility obtains in practice, the philosophical question remains: is verisimilitude a coherent notion on such a view, or does it dissolve into mere pragmatic utility?', translation: 'J\'admets que l\'intelligibilité mutuelle existe en pratique, la question philosophique demeure : la vraisemblance est-elle une notion cohérente dans une telle perspective, ou se dissout-elle en simple utilité pragmatique ?' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'That, I suspect, is where reductionism and holism must finally confront each other. And neither, I venture, can claim final victory — only a more or less fruitful engagement with the question.', translation: 'C\'est là, je soupçonne, que le réductionnisme et le holisme doivent enfin s\'affronter. Et ni l\'un ni l\'autre, j\'ose dire, ne peut revendiquer la victoire finale — seulement un engagement plus ou moins fécond avec la question.' },
  ],
  conversationTitle: 'Structuralisme et relativisme',
  pronunciation: [
    { word: 'Dialectics', phonetic: '/ˌdaɪəˈlɛktɪks/', meaning: 'Dialectique', tip: 'Accent sur « LEK » : dy-uh-LEK-tiks. Le « di » se prononce « dy » comme dans « diameter ». Ne dites pas « dee-uh-lek-tiks ».' },
    { word: 'Immanent', phonetic: '/ˈɪmənənt/', meaning: 'Immanent', tip: 'Accent sur la première syllabe : IM-uh-nent. ATTENTION : ne confondez pas avec "imminent" /ˈɪmɪnənt/ (qui va se produire). La distinction phonétique est subtile mais importante en philosophie.' },
    { word: 'Antinomy', phonetic: '/ænˈtɪnəmi/', meaning: 'Antinomie', tip: 'Accent sur "tin" : an-TIN-uh-mee. Le "y" final se prononce "ee" comme dans "philosophy". Ne dites pas "an-tee-nomee".' },
    { word: 'Verisimilitude', phonetic: '/ˌvɛrɪsɪˈmjuːlɪtjuːd/', meaning: 'Vraisemblance', tip: 'Accent principal sur "mu" : ver-ih-sih-MYOO-lih-tyood. Le "i" de "simili" est réduit. Ce mot long nécessite une respiration avant l\'accent principal.' },
  ],
}

// ─── c2-l14: Phenomenological Description — Pronouncing philosophical terminology ───
export const C2_L14: LessonContent = {
  vocab: [
    { english: 'Epoché', french: 'Épochè', phonetic: '/ˈɛpəkeɪ/', example: 'The epoché suspends judgment about the existence of the external world.', exampleTranslation: 'L\'epoché suspend le jugement sur l\'existence du monde extérieur.' },
    { english: 'Intentionality', french: 'Intentionnalité', phonetic: '/ˌɪntɛnˈʃɒnəlti/', example: 'Intentionality is the defining feature of consciousness according to Brentano.', exampleTranslation: 'L\'intentionnalité est la caractéristique déterminante de la conscience selon Brentano.' },
    { english: 'Noema', french: 'Noème', phonetic: '/noʊˈiːmə/', example: 'The noema is the object-as-intended, distinct from the real object.', exampleTranslation: 'Le noème est l\'objet-tel-qu\'intentionné, distinct de l\'objet réel.' },
    { english: 'Dasein', french: 'Dasein', phonetic: '/ˈdɑːzaɪn/', example: 'Heidegger\'s Dasein refers to the being for whom its own being is an issue.', exampleTranslation: 'Le Dasein de Heidegger désigne l\'être pour lequel son propre être est en question.' },
    { english: 'Empiricism', french: 'Empirisme', phonetic: '/ɪmˈpɪrɪsɪzəm/', example: 'Empiricism holds that knowledge derives primarily from sensory experience rather than innate ideas.', exampleTranslation: 'L\'empirisme soutient que la connaissance dérive principalement de l\'expérience sensorielle plutôt que d\'idées innées.' },
  ],
  grammar: {
    title: 'Nominalisation and Abstract Noun Phrases in Philosophical Writing',
    explanation: 'Le discours philosophique anglais recourt massivement à la nominalisation — la transformation de processus verbaux en noms abstraits — pour créer des chaînes argumentatives denses. Ainsi, "we can know" devient "the possibility of knowledge", "they are conscious of" devient "consciousness of", et "it intends toward" devient "intentionality". Cette transformation permet d\'empiler des concepts dans des syntagmes nominaux étendus : "the irreducibility of first-person phenomenal experience to third-person objective description". Cependant, la nominalisation excessive peut obscurcir le sens. À C2, il faut maîtriser l\'équilibre : utiliser les nominalisations pour la précision conceptuelle, tout en sachant les décomposer quand la clarté l\'exige. Les adverbes épistémiques ("arguably", "purportedly", "presumably", "ostensibly") jouent aussi un rôle crucial dans le hedging philosophique nominal.',
    examples: [
      { sentence: 'The irreducibility of the noema to the physical substrate constitutes a fundamental challenge to naturalism.', translation: 'L\'irréductibilité du noème au substrat physique constitue un défi fondamental au naturalisme.', isCorrect: true },
      { sentence: 'The epoché\'s suspension of the natural attitude enables the purification of phenomenological description from empirical presuppositions.', translation: 'La suspension de l\'attitude naturelle par l\'epoché permet la purification de la description phénoménologique des présuppositions empiriques.', isCorrect: true },
      { sentence: 'The intentionality of consciousness is what distinguishes from mere physical causation.', translation: '', isCorrect: false },
      { sentence: 'Dasein\'s being-toward-death is arguably the most existentially authentic modality of human existence.', translation: 'L\'être-pour-la-mort du Dasein est sans doute la modalité existentiellement la plus authentique de l\'existence humaine.', isCorrect: true },
    ],
    commonMistakes: [
      { wrong: 'The intentionality of consciousness is what distinguishes from mere physical causation.', correct: 'The intentionality of consciousness is what distinguishes it from mere physical causation.', explanation: 'Le verbe "distinguish" est transitif quand il signifie "distinguer X de Y" : "distinguishes IT from". Sans objet direct, la phrase est agrammaticale. En philosophie, cette erreur est fréquente car les nominalisations font perdre de vue la structure verbale sous-jacente.' },
      { wrong: 'The empiricism are inherently limited.', correct: 'Empiricism is inherently limited.', explanation: '"Empiricism" est un nom singulier invariable. Il ne prend pas de "s" au pluriel et s\'accorde au singulier : "empiricism is", pas "empiricism are". De même : "Dasein is" (pas "Dasein are"), "the noema is" (le pluriel est "noemata").' },
    ],
  },
  conversation: [
    { speaker: 'Dr. Ashworth', role: 'A', text: 'The epoché, properly understood, is not a metaphysical denial of the world but a methodological refraining — a suspension that discloses the intentional structure of consciousness itself.', translation: 'L\'epoché, correctement compris, n\'est pas un déni métaphysique du monde mais un refrainement méthodologique — une suspension qui dévoile la structure intentionnelle de la conscience elle-même.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'Precisely. And once that structure is disclosed, the noema emerges as irreducible to any purely causal account of perception. The object-as-intended is not the object-as-physical.', translation: 'Précisément. Et une fois cette structure dévoilée, le noème apparaît comme irréductible à tout compte rendu purement causal de la perception. L\'objet-tel-qu\'intentionné n\'est pas l\'objet-tel-que-physique.' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'That, presumably, is where the Heideggerian critique intervenes. Dasein\'s being-in-the-world is prior to any subject-object distinction that the epoché might subsequently reveal.', translation: 'C\'est, vraisemblablement, là qu\'intervient la critique heideggérienne. L\'être-au-monde du Dasein est antérieur à toute distinction sujet-objet que l\'epoché pourrait ultérieurement révéler.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'Indeed — and yet one must not conflate chronological priority with logical priority. The phenomenological reduction may be methodologically posterior while remaining ontologically illuminating.', translation: 'En effet — et cependant il ne faut pas confondre priorité chronologique et priorité logique. La réduction phénoménologique peut être méthodologiquement postérieure tout en restant ontologiquement éclairante.' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'Be that as it may, the question of empiricism remains. If phenomenology is to transcend mere description, it must account for how sensory experience grounds our knowledge of the world.', translation: 'Quoi qu\'il en soit, la question de l\'empirisme demeure. Si la phénoménologie doit transcender la simple description, elle doit expliquer comment l\'expérience sensorielle fonde notre connaissance du monde.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'Which is, I think, precisely where empiricism reaches its limit — for perception is never passive reception of sensory data but always already an embodied interpretation, a being-toward-the-world that precedes and enables reflection.', translation: 'C\'est, je pense, précisément là que l\'empirisme atteint sa limite — car la perception n\'est jamais réception passive de données sensorielles mais toujours déjà une interprétation incarnée, un être-vers-le-monde qui précède et rend possible la réflexion.' },
  ],
  conversationTitle: 'Phénoménologie et incarnation',
  pronunciation: [
    { word: 'Epoché', phonetic: '/ˈɛpəkeɪ/', meaning: 'Épochè', tip: 'Mot emprunté au grec : EP-uh-kay. L\'accent est sur la première syllabe. La finale "é" se prononce "kay" comme dans "café". Ne dites pas "eh-po-shay" à la française.' },
    { word: 'Intentionality', phonetic: '/ˌɪntɛnˈʃɒnəlti/', meaning: 'Intentionnalité', tip: 'Accent sur "shon" : in-ten-SHON-uh-tee. Le "tion" = "shon" (anglais) et non "see-on" (français). Le "al" se prononce "ul" réduit.' },
    { word: 'Noema', phonetic: '/noʊˈiːmə/', meaning: 'Noème', tip: 'Accent sur "ee" : no-EE-muh. Mot grec : le "oe" n\'est pas une voyelle unique mais deux syllabes "o-ee". Le "a" final est réduit. Ne dites pas "no-ay-ma".' },
    { word: 'Dasein', phonetic: '/ˈdɑːzaɪn/', meaning: 'Dasein (l\'être-là)', tip: 'Mot allemand anglicisé : DAH-zyne. Le "ei" allemand = "eye"/"aï" en anglais. L\'accent est sur la première syllabe. Ne prononcez pas à l\'allemande "dah-zyne" avec le "r" français — gardez le "z" anglais sonore.' },
  ],
}

// ─── c2-l15: Philosophy Sounds — Rhythm and intonation in academic discourse ──────
export const C2_L15: LessonContent = {
  vocab: [
    { english: 'Synecdoche', french: 'Synecdoque', phonetic: '/sɪˈnɛkdəki/', example: 'Using "wheels" to mean "car" is a synecdoche where a part represents the whole.', exampleTranslation: 'Utiliser « wheels » pour désigner une voiture est une synecdoque où une partie représente le tout.' },
    { english: 'Sublate', french: 'Relever (aufheben)', phonetic: '/sʌbˈleɪt/', example: 'The Hegelian dialectic sublates the contradiction into a higher synthesis.', exampleTranslation: 'La dialectique hégélienne relève la contradiction dans une synthèse supérieure.' },
    { english: 'Prolegomena', french: 'Prolégomènes', phonetic: '/ˌproʊlɛˈɡɒmɪnə/', example: 'Kant\'s Prolegomena serves as a concise introduction to the Critique of Pure Reason.', exampleTranslation: 'Les Prolégomènes de Kant servent d\'introduction concise à la Critique de la raison pure.' },
    { english: 'Quiddity', french: 'Quiddité', phonetic: '/ˈkwɪdɪti/', example: 'The quiddity of a thing is its "whatness" — that which makes it what it is.', exampleTranslation: 'La quiddité d\'une chose est sa « quiddité » — ce qui fait qu\'elle est ce qu\'elle est.' },
    { english: 'Haecceity', french: 'Héccéité', phonetic: '/hɛkˈsiːɪti/', example: 'Haecceity denotes the "thisness" that distinguishes a particular from all others.', exampleTranslation: 'L\'héccéité désigne la « cécité » qui distingue un particulier de tous les autres.' },
  ],
  grammar: {
    title: 'Rhythm, Intonation, and Prosodic Marking in Academic Discourse',
    explanation: 'Le discours académique anglais possède un rythme prosodique spécifique que le locuteur C2 doit maîtriser. L\'anglais est une langue stress-timed : les syllabes accentuées sont émises à intervalles réguliers, les syllabes inaccentuées étant réduites et compressées. En philosophie, l\'accent tonique remplit une fonction sémantique cruciale : "The REA-son" (la raison) vs "rea-SO-nable" (raisonnable) ; "ON-tol-o-gy" (ontologie) vs "on-to-LO-gi-cal" (ontologique). L\'intonation montante en fin de phrase (high-rise terminal) signale une question ou un doute, tandis que l\'intonation descendante (low-fall) affirme une conclusion. Le "list intonation" — succession de plateaux tonals descendants avec une chute finale — est typique des énumérations argumentatives. À C2, on maîtrise aussi le "continuation rise" (montée prosodique indiquant que la phrase continue) et le "contrastive stress" (accent contrastif sur un mot-clé pour opposer deux concepts). Enfin, les pauses stratégiques avant les termes clés ("...what we might call — [pause] — the quiddity of the matter") sont un marqueur de sophistication académique.',
    examples: [
      { sentence: 'It is not merely a CON-tradiction, but a pro-FOUND antinomy.', translation: 'Ce n\'est pas simplement une contradiction, mais une antinomie profonde.', isCorrect: true },
      { sentence: 'The DIA-lectic SUB-lates the thesis ↗ and the antithesis ↗ into a higher SYN-the-sis ↘.', translation: 'La dialectique relève la thèse et l\'antithèse dans une synthèse supérieure.', isCorrect: true },
      { sentence: 'What the argument pre-SUP-poses is not the EX-is-tence of the world, but rather the IN-tel-li-gi-bi-li-ty of experience.', translation: 'Ce que l\'argument présuppose n\'est pas l\'existence du monde, mais plutôt l\'intelligibilité de l\'expérience.', isCorrect: true },
      { sentence: 'The PRO-le-go-me-na to any future metaphysics could arguably has established the limits of reason.', translation: '', isCorrect: false },
    ],
    commonMistakes: [
      { wrong: 'The PRO-le-go-me-na to any future metaphysics could arguably has established the limits of reason.', correct: 'The PRO-le-go-me-na to any future metaphysics could arguably have established the limits of reason.', explanation: 'Après un modal ("could"), on utilise "have" + participe passé, jamais "has" : "could have established". Même si le sujet est "prolegomena" (apparemment pluriel), le modal est invariable. "Prolegomena" est d\'ailleurs un pluriel grec, mais le sens global est singulier ici.' },
      { wrong: 'He SUB-lated the contradiction into an higher synthesis.', correct: 'He sublated the contradiction into a higher synthesis.', explanation: 'Devant un "h" prononcé (comme dans "higher" /ˈhaɪər/), on utilise "a" et non "an" : "a higher synthesis". "An" ne s\'emploie que devant des voyelles phonétiques. En contexte académique, cette erreur est particulièrement noticeable.' },
    ],
  },
  conversation: [
    { speaker: 'Dr. Ashworth', role: 'A', text: 'Consider the rhythm of philosophical prose itself. The sublation of contradiction into synthesis mirrors, on the level of form, the Hegelian movement from thesis through antithesis to resolution.', translation: 'Considérez le rythme de la prose philosophique elle-même. Le relèvement de la contradiction en synthèse reflète, au niveau de la forme, le mouvement hégélien de la thèse à travers l\'antithèse jusqu\'à la résolution.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'An astute observation. And yet one must ask: does the prosodic structure of English philosophical argument — its stress-timed cadence, its cascading subordination — subtly shape the very content of the thought it purports to express?', translation: 'Une observation perspicace. Et pourtant il faut se demander : la structure prosodique de l\'argument philosophique anglais — sa cadence accentuelle, sa subordination en cascade — façonne-t-elle subtilement le contenu même de la pensée qu\'elle prétend exprimer ?' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'That is a question of quiddity versus haecceity. The "whatness" of a philosophical claim may be translinguistic, but its "thisness" — its particular texture in English — is irrevocably shaped by the intonation patterns of the language.', translation: 'C\'est une question de quiddité versus héccéité. La « quiddité » d\'une affirmation philosophique peut être translinguistique, mais sa « cécité » — sa texture particulière en anglais — est irrévocablement façonnée par les schémas d\'intonation de la langue.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'If that is so, then the Prolegomena to any genuinely comparative philosophy must include a prolegomenon to the prosody of the languages in which the philosophy is articulated.', translation: 'Si tel est le cas, alors les Prolégomènes à toute philosophie véritablement comparative doivent inclure un prolégomène à la prosodie des langues dans lesquelles la philosophie est articulée.' },
    { speaker: 'Dr. Ashworth', role: 'A', text: 'Precisely. And that, I think, is where metalepsis becomes more than a rhetorical figure — it becomes a philosophical condition. We do not merely speak about philosophy; we speak from within it, and the rhythm of our speech carries the imprint of the tradition that shapes us.', translation: 'Précisément. Et c\'est, je pense, là où la métalepse devient plus qu\'une figure rhétorique — elle devient une condition philosophique. Nous ne parlons pas simplement de la philosophie ; nous parlons de son intérieur, et le rythme de notre parole porte l\'empreinte de la tradition qui nous façonne.' },
    { speaker: 'Prof. N\'Dour', role: 'B', text: 'Then the final lesson of philosophical mastery may well be this: to speak philosophically in another language is not merely to translate concepts, but to inhabit another rhythm of thought — and in so doing, to discover that thought itself is more various than any single language can contain.', translation: 'Alors la leçon ultime de la maîtrise philosophique pourrait bien être celle-ci : parler philosophiquement dans une autre langue, ce n\'est pas simplement traduire des concepts, mais habiter un autre rythme de la pensée — et ce faisant, découvrir que la pensée elle-même est plus diverse qu\'aucune langue unique ne peut contenir.' },
  ],
  conversationTitle: 'Le rythme de la pensée philosophique',
  pronunciation: [
    { word: 'Synecdoche', phonetic: '/sɪˈnɛkdəki/', meaning: 'Synecdoque', tip: 'Accent sur « NEK » : sih-NEK-duh-kee. Le « ch » se prononce « k » (pas « sh »). Le « doche » final = « duh-kee ». Mot grec souvent mal prononcé : ne dites pas « sin-ek-do-shay ».' },
    { word: 'Sublate', phonetic: '/sʌbˈleɪt/', meaning: 'Relever (aufheben)', tip: 'Accent sur "late" : sub-LATE. Le "u" = son court comme dans "cup". Ce néologisme philosophique anglais suit le patron accentuel des verbes en -ate : accent sur la dernière syllabe.' },
    { word: 'Prolegomena', phonetic: '/ˌproʊlɛˈɡɒmɪnə/', meaning: 'Prolégomènes', tip: 'Accent principal sur "gom" : pro-leh-GOM-ih-nuh. Accent secondaire sur "pro". C\'est un pluriel grec. Ne mettez PAS l\'accent sur "pro" comme en français "pro-lé-go-mè-nes".' },
    { word: 'Haecceity', phonetic: '/hɛkˈsiːɪti/', meaning: 'Héccéité', tip: 'Accent sur "see" : hek-SEE-ih-tee. Le "haec" se prononce "hek" (non "hayk"). Le "cci" = "see-ih" avec un léger hiatus. Mot médiéval dérivé du latin "haec" (celle-ci).' },
  ],
}
