// ─── Comprehensive Exercise Data for YOELANG ─────────────────────────────────
// 30+ exercises per type per level (A1-C2)
// Uses base data from course-data.ts + generated exercises to reach 30+

import {
  VOCAB_BY_LEVEL as BASE_VOCAB,
  QUIZ_BY_LEVEL as BASE_QUIZ,
  GRAMMAR_BY_LEVEL as BASE_GRAMMAR,
  PRONUNCIATION_BY_LEVEL as BASE_PRONUNCIATION,
  type VocabCard,
  type QuizQuestion,
  type GrammarExercise,
  type PronunciationWord,
} from '@/lib/course-data'

export type { VocabCard, QuizQuestion, GrammarExercise, PronunciationWord }

// ─── Level Definitions ──────────────────────────────────────────────────────

export interface ExerciseLevel {
  code: string
  name: string
  description: string
  icon: string
  color: string
  gradient: string
  borderColor: string
  exerciseCount: string
}

export const EXERCISE_LEVELS: ExerciseLevel[] = [
  {
    code: 'A1',
    name: 'Débutant',
    description: 'Premiers pas en anglais : mots et phrases de base',
    icon: '🌱',
    color: 'text-green-600',
    gradient: 'from-green-400 to-emerald-500',
    borderColor: 'border-green-400/40',
    exerciseCount: '30+',
  },
  {
    code: 'A2',
    name: 'Élémentaire',
    description: 'Conversations simples et vocabulaire courant',
    icon: '🌿',
    color: 'text-emerald-600',
    gradient: 'from-emerald-400 to-teal-500',
    borderColor: 'border-emerald-400/40',
    exerciseCount: '30+',
  },
  {
    code: 'B1',
    name: 'Intermédiaire',
    description: 'Gérez la plupart des situations de voyage et de travail',
    icon: '🌳',
    color: 'text-teal-600',
    gradient: 'from-teal-400 to-cyan-500',
    borderColor: 'border-teal-400/40',
    exerciseCount: '30+',
  },
  {
    code: 'B2',
    name: 'Intermédiaire Supérieur',
    description: 'Communiquez avec fluidité sur des sujets complexes',
    icon: '🏔️',
    color: 'text-cyan-600',
    gradient: 'from-cyan-400 to-sky-500',
    borderColor: 'border-cyan-400/40',
    exerciseCount: '30+',
  },
  {
    code: 'C1',
    name: 'Avancé',
    description: 'Exprimez vos idées avec nuance et précision',
    icon: '⭐',
    color: 'text-amber-600',
    gradient: 'from-amber-400 to-orange-500',
    borderColor: 'border-amber-400/40',
    exerciseCount: '30+',
  },
  {
    code: 'C2',
    name: 'Maîtrise',
    description: 'Maîtrise quasi-native et aisance culturelle',
    icon: '👑',
    color: 'text-purple-600',
    gradient: 'from-violet-400 to-purple-500',
    borderColor: 'border-violet-400/40',
    exerciseCount: '30+',
  },
]

export function getExerciseLevelByCode(code: string): ExerciseLevel | undefined {
  return EXERCISE_LEVELS.find((l) => l.code === code)
}

// ─── Additional Vocab Data per Level ─────────────────────────────────────────

const EXTRA_VOCAB: Record<string, VocabCard[]> = {
  A1: [
    { id: 'a1-v21', english: 'Good', french: 'Bon/Bonne', example: 'This is good food.', phonetic: '/ɡʊd/' },
    { id: 'a1-v22', english: 'Big', french: 'Grand/Grande', example: 'The house is big.', phonetic: '/bɪɡ/' },
    { id: 'a1-v23', english: 'Small', french: 'Petit/Petite', example: 'I have a small cat.', phonetic: '/smɔːl/' },
    { id: 'a1-v24', english: 'Happy', french: 'Heureux/Heureuse', example: 'I am happy today.', phonetic: '/ˈhæpi/' },
    { id: 'a1-v25', english: 'Sad', french: 'Triste', example: 'She looks sad.', phonetic: '/sæd/' },
    { id: 'a1-v26', english: 'Red', french: 'Rouge', example: 'The car is red.', phonetic: '/red/' },
    { id: 'a1-v27', english: 'Blue', french: 'Bleu/Bleue', example: 'The sky is blue.', phonetic: '/bluː/' },
    { id: 'a1-v28', english: 'Green', french: 'Vert/Verte', example: 'The grass is green.', phonetic: '/ɡriːn/' },
    { id: 'a1-v29', english: 'Dog', french: 'Chien', example: 'The dog is friendly.', phonetic: '/dɒɡ/' },
    { id: 'a1-v30', english: 'Cat', french: 'Chat', example: 'I have a black cat.', phonetic: '/kæt/' },
    { id: 'a1-v31', english: 'Car', french: 'Voiture', example: 'My car is new.', phonetic: '/kɑːr/' },
    { id: 'a1-v32', english: 'Rain', french: 'Pluie', example: 'The rain is falling.', phonetic: '/reɪn/' },
    { id: 'a1-v33', english: 'Sun', french: 'Soleil', example: 'The sun is bright.', phonetic: '/sʌn/' },
    { id: 'a1-v34', english: 'Time', french: 'Temps', example: 'What time is it?', phonetic: '/taɪm/' },
    { id: 'a1-v35', english: 'Work', french: 'Travail', example: 'I go to work every day.', phonetic: '/wɜːrk/' },
  ],
  A2: [
    { id: 'a2-v21', english: 'Forecast', french: 'Prévision', example: 'The weather forecast says rain.', phonetic: '/ˈfɔːrkæst/' },
    { id: 'a2-v22', english: 'Destination', french: 'Destination', example: 'Our destination is Paris.', phonetic: '/ˌdestɪˈneɪʃən/' },
    { id: 'a2-v23', english: 'Reservation', french: 'Réservation', example: 'I made a reservation for two.', phonetic: '/ˌrezərˈveɪʃən/' },
    { id: 'a2-v24', english: 'Symptom', french: 'Symptôme', example: 'What are your symptoms?', phonetic: '/ˈsɪmptəm/' },
    { id: 'a2-v25', english: 'Receipt', french: 'Reçu', example: 'Can I have the receipt?', phonetic: '/rɪˈsiːt/' },
    { id: 'a2-v26', english: 'Appointment', french: 'Rendez-vous', example: 'I have an appointment at 3.', phonetic: '/əˈpɔɪntmənt/' },
    { id: 'a2-v27', english: 'Equipment', french: 'Équipement', example: 'The gym has new equipment.', phonetic: '/ɪˈkwɪpmənt/' },
    { id: 'a2-v28', english: 'Departure', french: 'Départ', example: 'The departure is at 8 AM.', phonetic: '/dɪˈpɑːrtʃər/' },
    { id: 'a2-v29', english: 'Conference', french: 'Conférence', example: 'The conference starts tomorrow.', phonetic: '/ˈkɒnfərəns/' },
    { id: 'a2-v30', english: 'Colleague', french: 'Collègue', example: 'My colleague is very helpful.', phonetic: '/ˈkɒliːɡ/' },
    { id: 'a2-v31', english: 'Furniture', french: 'Meubles', example: 'We bought new furniture.', phonetic: '/ˈfɜːrnɪtʃər/' },
    { id: 'a2-v32', english: 'Painkiller', french: 'Antidouleur', example: 'I need a painkiller.', phonetic: '/ˈpeɪnkɪlər/' },
    { id: 'a2-v33', english: 'Bicycle', french: 'Vélo', example: 'I ride my bicycle to work.', phonetic: '/ˈbaɪsɪkl/' },
    { id: 'a2-v34', english: 'Dictionary', french: 'Dictionnaire', example: 'Look it up in the dictionary.', phonetic: '/ˈdɪkʃəneri/' },
    { id: 'a2-v35', english: 'Improvement', french: 'Amélioration', example: 'There has been an improvement.', phonetic: '/ɪmˈpruːvmənt/' },
  ],
  B1: [
    { id: 'b1-v21', english: 'Breakthrough', french: 'Percée', example: 'The discovery was a major breakthrough.', phonetic: '/ˈbreɪkθruː/' },
    { id: 'b1-v22', english: 'Perspective', french: 'Perspective', example: 'We need a different perspective.', phonetic: '/pərˈspektɪv/' },
    { id: 'b1-v23', english: 'Collaboration', french: 'Collaboration', example: 'Collaboration leads to innovation.', phonetic: '/kəˌlæbəˈreɪʃən/' },
    { id: 'b1-v24', english: 'Sustainable', french: 'Durable', example: 'We need sustainable solutions.', phonetic: '/səˈsteɪnəbl/' },
    { id: 'b1-v25', english: 'Innovation', french: 'Innovation', example: 'Innovation drives progress.', phonetic: '/ˌɪnəˈveɪʃən/' },
    { id: 'b1-v26', english: 'Diversity', french: 'Diversité', example: 'Diversity enriches our community.', phonetic: '/daɪˈvɜːrsəti/' },
    { id: 'b1-v27', english: 'Consequence', french: 'Conséquence', example: 'Every action has consequences.', phonetic: '/ˈkɒnsɪkwəns/' },
    { id: 'b1-v28', english: 'Negotiation', french: 'Négociation', example: 'The negotiation was successful.', phonetic: '/nɪˌɡoʊʃiˈeɪʃən/' },
    { id: 'b1-v29', english: 'Consumption', french: 'Consommation', example: 'Energy consumption must decrease.', phonetic: '/kənˈsʌmpʃən/' },
    { id: 'b1-v30', english: 'Legislation', french: 'Législation', example: 'New legislation was passed.', phonetic: '/ˌledʒɪsˈleɪʃən/' },
    { id: 'b1-v31', english: 'Assessment', french: 'Évaluation', example: 'The assessment shows improvement.', phonetic: '/əˈsesmənt/' },
    { id: 'b1-v32', english: 'Phenomenon', french: 'Phénomène', example: 'This is a natural phenomenon.', phonetic: '/fɪˈnɒmɪnən/' },
    { id: 'b1-v33', english: 'Advocacy', french: 'Plaidoyer', example: 'She works in advocacy.', phonetic: '/ˈædvəkəsi/' },
    { id: 'b1-v34', english: 'Endurance', french: 'Endurance', example: 'Marathon runners need endurance.', phonetic: '/ɪnˈdjʊrəns/' },
    { id: 'b1-v35', english: 'Interpretation', french: 'Interprétation', example: 'The interpretation varies by culture.', phonetic: '/ɪnˌtɜːrprɪˈteɪʃən/' },
  ],
  B2: [
    { id: 'b2-v21', english: 'Constituency', french: 'Circonscription', example: 'She represents her constituency well.', phonetic: '/kənˈstɪtjuənsi/' },
    { id: 'b2-v22', english: 'Prevalence', french: 'Prévalence', example: 'The prevalence of the disease is declining.', phonetic: '/ˈprevələns/' },
    { id: 'b2-v23', english: 'Epistemology', french: 'Épistémologie', example: 'Epistemology questions how we know things.', phonetic: '/ɪˌpɪstəˈmɒlədʒi/' },
    { id: 'b2-v24', english: 'Substantiate', french: 'Étayer', example: 'You must substantiate your claims.', phonetic: '/səbˈstænʃieɪt/' },
    { id: 'b2-v25', english: 'Anomaly', french: 'Anomalie', example: 'The data showed an anomaly.', phonetic: '/əˈnɒməli/' },
    { id: 'b2-v26', english: 'Delineate', french: 'Délimiter', example: 'The report delineates the key issues.', phonetic: '/dɪˈlɪnieɪt/' },
    { id: 'b2-v27', english: 'Corollary', french: 'Corollaire', example: 'This is a natural corollary of the theory.', phonetic: '/ˈkɒrəleri/' },
    { id: 'b2-v28', english: 'Scrutiny', french: 'Examen minutieux', example: 'The plan came under scrutiny.', phonetic: '/ˈskruːtəni/' },
    { id: 'b2-v29', english: 'Reconciliation', french: 'Réconciliation', example: 'Reconciliation requires compromise.', phonetic: '/ˌrekənˌsɪliˈeɪʃən/' },
    { id: 'b2-v30', english: 'Ambiguity', french: 'Ambiguïté', example: 'The ambiguity of the text is deliberate.', phonetic: '/ˌæmbɪˈɡjuːəti/' },
    { id: 'b2-v31', english: 'Discrepancy', french: 'Discordance', example: 'There is a discrepancy between the reports.', phonetic: '/dɪsˈkrepənsi/' },
    { id: 'b2-v32', english: 'Elaboration', french: 'Élaboration', example: 'Further elaboration is needed.', phonetic: '/ɪˌlæbəˈreɪʃən/' },
    { id: 'b2-v33', english: 'Precedent', french: 'Précédent', example: 'This sets a dangerous precedent.', phonetic: '/ˈpresɪdənt/' },
    { id: 'b2-v34', english: 'Remuneration', french: 'Rémunération', example: 'Fair remuneration is essential.', phonetic: '/rɪˌmjuːnəˈreɪʃən/' },
    { id: 'b2-v35', english: 'Comprehend', french: 'Comprendre', example: 'It is hard to comprehend the scale.', phonetic: '/ˌkɒmprɪˈhend/' },
  ],
  C1: [
    { id: 'c1-v16', english: 'Pragmatism', french: 'Pragmatisme', example: 'Pragmatism often trumps idealism.', phonetic: '/ˈpræɡmətɪzəm/' },
    { id: 'c1-v17', english: 'Hegemony', french: 'Hégémonie', example: 'Cultural hegemony shapes societies.', phonetic: '/hɪˈdʒeməni/' },
    { id: 'c1-v18', english: 'Discourse', french: 'Discours', example: 'Academic discourse requires precision.', phonetic: '/ˈdɪskɔːrs/' },
    { id: 'c1-v19', english: 'Dichotomy', french: 'Dichotomie', example: 'The dichotomy is false.', phonetic: '/daɪˈkɒtəmi/' },
    { id: 'c1-v20', english: 'Synergy', french: 'Synergie', example: 'The synergy between teams was remarkable.', phonetic: '/ˈsɪnərdʒi/' },
    { id: 'c1-v21', english: 'Catalyst', french: 'Catalyseur', example: 'The event was a catalyst for change.', phonetic: '/ˈkætəlɪst/' },
    { id: 'c1-v22', english: 'Efficacy', french: 'Efficacité', example: 'The efficacy of the treatment was proven.', phonetic: '/ˈefɪkəsi/' },
    { id: 'c1-v23', english: 'Autonomy', french: 'Autonomie', example: 'Regional autonomy was granted.', phonetic: '/ɔːˈtɒnəmi/' },
    { id: 'c1-v24', english: 'Repercussion', french: 'Répercussion', example: 'The repercussions were far-reaching.', phonetic: '/ˌriːpərˈkʌʃən/' },
    { id: 'c1-v25', english: 'Juxtaposition', french: 'Juxtaposition', example: 'The juxtaposition is striking.', phonetic: '/ˌdʒʌkstəpəˈzɪʃən/' },
    { id: 'c1-v26', english: 'Nuance', french: 'Nuance', example: 'Appreciate the nuance of the argument.', phonetic: '/ˈnjuːɑːns/' },
    { id: 'c1-v27', english: 'Plausible', french: 'Plausible', example: 'The explanation seems plausible.', phonetic: '/ˈplɔːzəbl/' },
    { id: 'c1-v28', english: 'Unprecedented', french: 'Sans précédent', example: 'This is an unprecedented situation.', phonetic: '/ʌnˈpresɪdentɪd/' },
    { id: 'c1-v29', english: 'Stipulation', french: 'Stipulation', example: 'The contract has a clear stipulation.', phonetic: '/ˌstɪpjʊˈleɪʃən/' },
    { id: 'c1-v30', english: 'Implication', french: 'Implication', example: 'The implication was clear to everyone.', phonetic: '/ˌɪmplɪˈkeɪʃən/' },
  ],
  C2: [
    { id: 'c2-v16', english: 'Dialectic', french: 'Dialectique', example: 'The dialectic between thesis and antithesis.', phonetic: '/ˌdaɪəˈlektɪk/' },
    { id: 'c2-v17', english: 'Exegesis', french: 'Exégèse', example: 'The exegesis of the ancient text took years.', phonetic: '/ˌeksɪˈdʒiːsɪs/' },
    { id: 'c2-v18', english: 'Perspicacity', french: 'Perspicacité', example: 'Her perspicacity was remarkable.', phonetic: '/ˌpɜːrspɪˈkæsəti/' },
    { id: 'c2-v19', english: 'Verisimilitude', french: 'Vraisemblance', example: 'The novel achieves remarkable verisimilitude.', phonetic: '/ˌverɪsɪˈmɪlɪtjuːd/' },
    { id: 'c2-v20', english: 'Aporia', french: 'Aporie', example: 'The philosophical text ends in aporia.', phonetic: '/əˈpɔːriə/' },
    { id: 'c2-v21', english: 'Teleology', french: 'Téléologie', example: 'Teleology examines purpose in nature.', phonetic: '/ˌteliˈɒlədʒi/' },
    { id: 'c2-v22', english: 'Prolepsis', french: 'Prolepse', example: 'The prolepsis anticipates the reader\'s objection.', phonetic: '/proʊˈlepsɪs/' },
    { id: 'c2-v23', english: 'Liminality', french: 'Liminalité', example: 'The concept of liminality in rites of passage.', phonetic: '/ˌlɪmɪˈnæləti/' },
    { id: 'c2-v24', english: 'Polyphony', french: 'Polyphonie', example: 'Bakhtin\'s concept of polyphony in novels.', phonetic: '/pəˈlɪfəni/' },
    { id: 'c2-v25', english: 'Mimesis', french: 'Mimésis', example: 'Aristotle\'s concept of mimesis in art.', phonetic: '/mɪˈmiːsɪs/' },
    { id: 'c2-v26', english: 'Ontological', french: 'Ontologique', example: 'The ontological argument for God\'s existence.', phonetic: '/ˌɒntəˈlɒdʒɪkl/' },
    { id: 'c2-v27', english: 'Phenomenology', french: 'Phénoménologie', example: 'Husserl founded phenomenology.', phonetic: '/fɪˌnɒmɪˈnɒlədʒi/' },
    { id: 'c2-v28', english: 'Hermeneutic', french: 'Herméneutique', example: 'The hermeneutic circle of interpretation.', phonetic: '/ˌhɜːrməˈnjuːtɪk/' },
    { id: 'c2-v29', english: 'Aleatory', french: 'Aléatoire', example: 'Aleatory music involves chance elements.', phonetic: '/ˈeɪliətɔːri/' },
    { id: 'c2-v30', english: 'Sublime', french: 'Sublime', example: 'Kant distinguished the beautiful from the sublime.', phonetic: '/səˈblaɪm/' },
  ],
}

// ─── Additional Quiz Data per Level ──────────────────────────────────────────

const EXTRA_QUIZ: Record<string, QuizQuestion[]> = {
  A1: [
    { id: 'a1-q9', question: 'What is "bonjour" in English?', options: ['Goodbye', 'Hello', 'Thanks', 'Please'], correctIndex: 1, explanation: '"Bonjour" signifie "Hello" en anglais.' },
    { id: 'a1-q10', question: 'Complete: "I ___ a student."', options: ['am', 'is', 'are', 'be'], correctIndex: 0, explanation: 'On utilise "am" avec "I".' },
    { id: 'a1-q11', question: 'What is "rouge" in English?', options: ['Blue', 'Green', 'Red', 'Yellow'], correctIndex: 2, explanation: '"Rouge" se traduit par "Red" en anglais.' },
    { id: 'a1-q12', question: 'Complete: "They ___ my friends."', options: ['am', 'is', 'are', 'be'], correctIndex: 2, explanation: 'On utilise "are" avec "They".' },
    { id: 'a1-q13', question: 'Which word means "grand"?', options: ['Small', 'Big', 'Good', 'Bad'], correctIndex: 1, explanation: '"Grand" se traduit par "Big" en anglais.' },
    { id: 'a1-q14', question: 'What is "chat" in English?', options: ['Dog', 'Bird', 'Cat', 'Fish'], correctIndex: 2, explanation: '"Chat" se traduit par "Cat" en anglais.' },
    { id: 'a1-q15', question: 'Complete: "She ___ a teacher."', options: ['am', 'is', 'are', 'be'], correctIndex: 1, explanation: 'On utilise "is" avec "She".' },
    { id: 'a1-q16', question: 'What is "soleil" in English?', options: ['Moon', 'Star', 'Cloud', 'Sun'], correctIndex: 3, explanation: '"Soleil" se traduit par "Sun" en anglais.' },
    { id: 'a1-q17', question: 'Complete: "We ___ from France."', options: ['am', 'is', 'are', 'be'], correctIndex: 2, explanation: 'On utilise "are" avec "We".' },
    { id: 'a1-q18', question: 'Which is a greeting?', options: ['Goodbye', 'Good morning', 'See you', 'Bye'], correctIndex: 1, explanation: '"Good morning" est une salutation (greeting).' },
    { id: 'a1-q19', question: 'What is "eau" in English?', options: ['Milk', 'Juice', 'Water', 'Tea'], correctIndex: 2, explanation: '"Eau" se traduit par "Water" en anglais.' },
    { id: 'a1-q20', question: 'Complete: "He ___ a book."', options: ['have', 'has', 'having', 'had'], correctIndex: 1, explanation: 'On utilise "has" avec "He" (3e personne).' },
    { id: 'a1-q21', question: 'What is "maison" in English?', options: ['Car', 'House', 'School', 'Office'], correctIndex: 1, explanation: '"Maison" se traduit par "House" en anglais.' },
    { id: 'a1-q22', question: 'Complete: "___ you like coffee?"', options: ['Do', 'Does', 'Are', 'Is'], correctIndex: 0, explanation: 'On utilise "Do" avec "you" au présent simple.' },
    { id: 'a1-q23', question: 'What is "merci" in English?', options: ['Hello', 'Goodbye', 'Thank you', 'Please'], correctIndex: 2, explanation: '"Merci" se traduit par "Thank you" en anglais.' },
    { id: 'a1-q24', question: 'Complete: "I ___ not like fish."', options: ['do', 'does', 'am', 'is'], correctIndex: 0, explanation: 'La négation au présent simple avec "I" utilise "do not".' },
    { id: 'a1-q25', question: 'Which number is "twenty"?', options: ['12', '20', '2', '22'], correctIndex: 1, explanation: '"Twenty" signifie 20 en anglais.' },
    { id: 'a1-q26', question: 'Complete: "This is ___ apple."', options: ['a', 'an', 'the', 'no article'], correctIndex: 1, explanation: 'On utilise "an" devant un son voyelle.' },
    { id: 'a1-q27', question: 'What is "pain" in English?', options: ['Rice', 'Bread', 'Meat', 'Cake'], correctIndex: 1, explanation: '"Pain" se traduit par "Bread" en anglais.' },
    { id: 'a1-q28', question: 'Complete: "She ___ to school every day."', options: ['go', 'goes', 'going', 'gone'], correctIndex: 1, explanation: '3e personne du singulier : on ajoute -s au verbe.' },
    { id: 'a1-q29', question: 'What is "livre" in English?', options: ['Pen', 'Table', 'Book', 'Chair'], correctIndex: 2, explanation: '"Livre" se traduit par "Book" en anglais.' },
    { id: 'a1-q30', question: 'Complete: "There ___ three cats."', options: ['is', 'are', 'am', 'be'], correctIndex: 1, explanation: '"There are" s\'utilise avec les noms pluriels.' },
  ],
  A2: [
    { id: 'a2-q9', question: 'Complete: "She ___ to Paris last summer."', options: ['go', 'goes', 'went', 'going'], correctIndex: 2, explanation: 'Le passé simple de "go" est "went".' },
    { id: 'a2-q10', question: 'What is "météo" in English?', options: ['Climate', 'Weather', 'Season', 'Temperature'], correctIndex: 1, explanation: '"Météo" se traduit par "Weather" en anglais.' },
    { id: 'a2-q11', question: 'Complete: "If it rains, we ___ stay home."', options: ['will', 'would', 'should', 'could'], correctIndex: 0, explanation: 'Dans le first conditional, la clause principale utilise "will".' },
    { id: 'a2-q12', question: 'Which is uncountable?', options: ['Apples', 'Chairs', 'Furniture', 'Books'], correctIndex: 2, explanation: '"Furniture" est un nom indénombrable en anglais.' },
    { id: 'a2-q13', question: 'Complete: "I have been waiting ___ two hours."', options: ['since', 'for', 'during', 'while'], correctIndex: 1, explanation: 'On utilise "for" avec une durée.' },
    { id: 'a2-q14', question: 'What is "ordonnance" in English?', options: ['Recipe', 'Prescription', 'Receipt', 'Invoice'], correctIndex: 1, explanation: '"Ordonnance" se traduit par "Prescription" en anglais.' },
    { id: 'a2-q15', question: 'Complete: "The book was ___ by a famous author."', options: ['write', 'wrote', 'written', 'writing'], correctIndex: 2, explanation: 'La voix passive utilise le participe passé : "written".' },
    { id: 'a2-q16', question: 'Which means "plus cher"?', options: ['Cheaper', 'More expensive', 'Less expensive', 'As expensive'], correctIndex: 1, explanation: '"Plus cher" = "More expensive" en anglais.' },
    { id: 'a2-q17', question: 'Complete: "She ___ study harder."', options: ['should', 'shall', 'would', 'could'], correctIndex: 0, explanation: '"Should" exprime un conseil.' },
    { id: 'a2-q18', question: 'What is "bagage" in English?', options: ['Ticket', 'Passport', 'Luggage', 'Journey'], correctIndex: 2, explanation: '"Bagage" se traduit par "Luggage" en anglais.' },
    { id: 'a2-q19', question: 'Complete: "I ___ TV when the phone rang."', options: ['watch', 'watched', 'was watching', 'have watched'], correctIndex: 2, explanation: 'Le past continuous décrit une action en cours : "was watching".' },
    { id: 'a2-q20', question: 'Which is the correct question?', options: ['How much people?', 'How many people?', 'How people?', 'How much persons?'], correctIndex: 1, explanation: '"People" est dénombrable, donc on utilise "How many".' },
    { id: 'a2-q21', question: 'Complete: "He is ___ than his brother."', options: ['tall', 'taller', 'tallest', 'more tall'], correctIndex: 1, explanation: 'Le comparatif des adjectifs courts : adjective + -er.' },
    { id: 'a2-q22', question: 'What is "aéroport" in English?', options: ['Station', 'Harbor', 'Airport', 'Terminal'], correctIndex: 2, explanation: '"Aéroport" se traduit par "Airport" en anglais.' },
    { id: 'a2-q23', question: 'Complete: "We have ___ milk left."', options: ['few', 'a few', 'little', 'a little'], correctIndex: 3, explanation: '"Milk" est indénombrable. "A little" = un peu.' },
    { id: 'a2-q24', question: 'Which tense for future plans?', options: ['Present simple', 'Past simple', 'Going to + verb', 'Present perfect'], correctIndex: 2, explanation: '"Going to" exprime des plans futurs intentionnels.' },
    { id: 'a2-q25', question: 'Complete: "___ I use your phone?"', options: ['Must', 'Should', 'Can', 'Will'], correctIndex: 2, explanation: '"Can" est utilisé pour demander la permission poliment.' },
    { id: 'a2-q26', question: 'What is "voisin" in English?', options: ['Friend', 'Neighbor', 'Relative', 'Colleague'], correctIndex: 1, explanation: '"Voisin" se traduit par "Neighbor" en anglais.' },
    { id: 'a2-q27', question: 'Complete: "I ___ to the gym three times last week."', options: ['go', 'goes', 'went', 'have gone'], correctIndex: 2, explanation: 'Le passé simple "went" est utilisé pour des actions terminées.' },
    { id: 'a2-q28', question: 'Which preposition: "She is afraid ___ spiders"?', options: ['from', 'of', 'by', 'with'], correctIndex: 1, explanation: 'On dit "afraid of" en anglais.' },
    { id: 'a2-q29', question: 'Complete: "You ___ drive without a license."', options: ['mustn\'t', 'don\'t have to', 'shouldn\'t', 'couldn\'t'], correctIndex: 0, explanation: '"Mustn\'t" exprime l\'interdiction.' },
    { id: 'a2-q30', question: 'What is "entretien" in English?', options: ['Entertainment', 'Interview', 'Agreement', 'Maintenance'], correctIndex: 1, explanation: '"Entretien" (d\'embauche) se traduit par "Interview" en anglais.' },
  ],
  B1: [
    { id: 'b1-q9', question: 'Which uses the passive voice correctly?', options: ['The report wrote yesterday', 'The report was written yesterday', 'The report is writing yesterday', 'The report written yesterday'], correctIndex: 1, explanation: 'Voix passive : was/were + participe passé.' },
    { id: 'b1-q10', question: 'Complete: "If I ___ you, I would accept."', options: ['am', 'was', 'were', 'be'], correctIndex: 2, explanation: 'Le second conditional utilise "were" pour tous les sujets.' },
    { id: 'b1-q11', question: 'What does "conservation" mean?', options: ['Conversation', 'Preservation', 'Consideration', 'Constipation'], correctIndex: 1, explanation: '"Conservation" signifie préservation des ressources.' },
    { id: 'b1-q12', question: 'Complete: "She said she ___ the movie."', options: ['enjoys', 'enjoyed', 'has enjoyed', 'is enjoying'], correctIndex: 1, explanation: 'Le reported speech fait reculer le temps : present → past.' },
    { id: 'b1-q13', question: 'Which is a relative clause?', options: ['She is happy', 'The book which I read', 'I like coffee', 'He runs fast'], correctIndex: 1, explanation: 'Une relative clause commence par who/which/that.' },
    { id: 'b1-q14', question: 'Complete: "I wish I ___ more time."', options: ['have', 'had', 'will have', 'having'], correctIndex: 1, explanation: '"Wish" + past simple exprime un souhait actuel.' },
    { id: 'b1-q15', question: 'What does "heritage" mean in French?', options: ['Héritage/Patrimoine', 'Hérésie', 'Hésitation', 'Hébergement'], correctIndex: 0, explanation: '"Heritage" = patrimoine culturel.' },
    { id: 'b1-q16', question: 'Complete: "By 2030, scientists ___ a cure."', options: ['will find', 'will have found', 'would find', 'found'], correctIndex: 1, explanation: 'Le future perfect : will have + participe passé.' },
    { id: 'b1-q17', question: 'Which uses the gerund correctly?', options: ['I enjoy to swim', 'I enjoy swimming', 'I enjoy swim', 'I enjoy swam'], correctIndex: 1, explanation: 'Après "enjoy", on utilise le gérondif (-ing).' },
    { id: 'b1-q18', question: 'Complete: "The house ___ in 1990 is now a museum."', options: ['built', 'building', 'was built', 'has built'], correctIndex: 0, explanation: 'Participe passé comme adjectif : "built in 1990".' },
    { id: 'b1-q19', question: 'What does "discrimination" mean?', options: ['Distinction', 'Discrimination', 'Discipline', 'Discussion'], correctIndex: 1, explanation: '"Discrimination" = traitement inégal.' },
    { id: 'b1-q20', question: 'Complete: "It\'s illegal, ___?"', options: ['is it', 'isn\'t it', 'doesn\'t it', 'won\'t it'], correctIndex: 1, explanation: 'Question tag : affirmation → négation.' },
    { id: 'b1-q21', question: 'Which uses the third conditional?', options: ['If I had studied, I would pass', 'If I had studied, I would have passed', 'If I study, I will pass', 'If I studied, I would pass'], correctIndex: 1, explanation: 'Third conditional : If + past perfect, would have + PP.' },
    { id: 'b1-q22', question: 'Complete: "I enjoy ___ science fiction."', options: ['read', 'reading', 'to read', 'reads'], correctIndex: 1, explanation: 'Le gérondif suit "enjoy".' },
    { id: 'b1-q23', question: 'What is "bien-être" in English?', options: ['Wellness', 'Welfare', 'Goodness', 'Welcome'], correctIndex: 0, explanation: '"Bien-être" se traduit par "Wellness".' },
    { id: 'b1-q24', question: 'Complete: "She has ___ to Paris three times."', options: ['be', 'been', 'being', 'was'], correctIndex: 1, explanation: 'Present perfect : have/has + been.' },
    { id: 'b1-q25', question: 'Which is the correct reported speech?', options: ['He said he is tired', 'He said he was tired', 'He said he will be tired', 'He said he has been tired'], correctIndex: 1, explanation: 'Le reported speech fait reculer le temps.' },
    { id: 'b1-q26', question: 'Complete: "The planet ___ we live on is fragile."', options: ['who', 'which', 'whom', 'whose'], correctIndex: 1, explanation: '"Which" pour les choses dans les relative clauses.' },
    { id: 'b1-q27', question: 'What does "sustainable" mean?', options: ['Supportable', 'Durable/Viable', 'Suspicious', 'Substantial'], correctIndex: 1, explanation: '"Sustainable" = qui peut être maintenu à long terme.' },
    { id: 'b1-q28', question: 'Complete: "He ___ have left early."', options: ['must', 'can', 'will', 'shall'], correctIndex: 0, explanation: '"Must have" exprime une déduction passée.' },
    { id: 'b1-q29', question: 'Which phrasal verb means "to calm down"?', options: ['Calm up', 'Calm down', 'Calm off', 'Calm away'], correctIndex: 1, explanation: '"Calm down" = se calmer.' },
    { id: 'b1-q30', question: 'Complete: "I wish I ___ more money."', options: ['have', 'had', 'will have', 'would have'], correctIndex: 1, explanation: '"Wish" + past simple pour un souhait présent.' },
  ],
  B2: [
    { id: 'b2-q9', question: 'Which demonstrates nominalization?', options: ['They decided quickly', 'Their decision was quick', 'They made a quick decide', 'Quickly deciding'], correctIndex: 1, explanation: 'La nominalisation transforme un verbe en nom.' },
    { id: 'b2-q10', question: 'Complete: "Rarely ___ to that restaurant."', options: ['she goes', 'does she go', 'goes she', 'she does go'], correctIndex: 1, explanation: 'L\'inversion après un adverbe négatif en début de phrase.' },
    { id: 'b2-q11', question: 'What does "litigation" mean?', options: ['Lighting', 'Legal proceedings', 'Literacy', 'Literal meaning'], correctIndex: 1, explanation: '"Litigation" = procédure judiciaire.' },
    { id: 'b2-q12', question: 'Complete: "Had I known, I ___ differently."', options: ['would act', 'would have acted', 'will act', 'acted'], correctIndex: 1, explanation: 'Third conditional inversé : Had + PP, would have + PP.' },
    { id: 'b2-q13', question: 'Which is a hedging phrase?', options: ['This proves', 'It appears that', 'This confirms', 'This demonstrates'], correctIndex: 1, explanation: '"It appears that" est une formule de prudence académique.' },
    { id: 'b2-q14', question: 'Complete: "Not only ___ the exam, but she got the highest score."', options: ['she passed', 'did she pass', 'passed she', 'she did pass'], correctIndex: 1, explanation: 'Inversion après "Not only" en début de phrase.' },
    { id: 'b2-q15', question: 'What does "compliance" mean?', options: ['Complaint', 'Adherence to rules', 'Complexity', 'Completion'], correctIndex: 1, explanation: '"Compliance" = conformité aux règles.' },
    { id: 'b2-q16', question: 'Complete: "The contract, ___ was signed yesterday, is valid."', options: ['that', 'which', 'who', 'whom'], correctIndex: 1, explanation: 'Relative clause non-définissante : "which" obligatoire.' },
    { id: 'b2-q17', question: 'Which uses inversion correctly?', options: ['Seldom she goes', 'Seldom does she go', 'Seldom goes she', 'Seldom do she goes'], correctIndex: 1, explanation: 'Inversion : adverbe négatif + auxiliary + subject + verb.' },
    { id: 'b2-q18', question: 'Complete: "The rapid ___ of the company was unexpected."', options: ['expand', 'expansion', 'expanding', 'expanse'], correctIndex: 1, explanation: 'Nominalisation : expand → expansion.' },
    { id: 'b2-q19', question: 'What does "paradigm" mean?', options: ['A paradox', 'A model or pattern', 'A paragraph', 'A parameter'], correctIndex: 1, explanation: '"Paradigm" = modèle de référence.' },
    { id: 'b2-q20', question: 'Complete: "It ___ that further research is needed."', options: ['appears', 'appearing', 'appeared', 'has appearing'], correctIndex: 0, explanation: 'Hedging : "It appears that" = Il semble que.' },
    { id: 'b2-q21', question: 'What is "conformité" in English?', options: ['Conformity', 'Compliance', 'Confirmation', 'Conference'], correctIndex: 1, explanation: '"Conformité" = Compliance en contexte réglementaire.' },
    { id: 'b2-q22', question: 'Complete: "The data ___ collected over five years."', options: ['was', 'were', 'is being', 'has'], correctIndex: 1, explanation: '"Data" est pluriel en anglais académique : "were".' },
    { id: 'b2-q23', question: 'Which uses the passive infinitive?', options: ['The work must do', 'The work must be done', 'The work must doing', 'The work must to do'], correctIndex: 1, explanation: 'Infinitif passif : must + be + participe passé.' },
    { id: 'b2-q24', question: 'Complete: "So great ___ that everyone stopped."', options: ['was the noise', 'the noise was', 'the noise is', 'is the noise'], correctIndex: 0, explanation: 'Inversion après "So + adjective" en début de phrase.' },
    { id: 'b2-q25', question: 'What does "coherence" mean?', options: ['Cohesion', 'Consistency', 'Coincidence', 'Cooperation'], correctIndex: 1, explanation: '"Coherence" = cohérence/logique d\'un texte.' },
    { id: 'b2-q26', question: 'Complete: "Under no circumstances ___ reveal the source."', options: ['you should', 'should you', 'you must', 'must you to'], correctIndex: 1, explanation: 'Inversion après "Under no circumstances".' },
    { id: 'b2-q27', question: 'Which is a defining relative clause?', options: ['Paris, which is beautiful', 'The book that I bought', 'My mother, who is kind', 'London, where I live'], correctIndex: 1, explanation: 'Defining relative clause = sans virgule, essentielle au sens.' },
    { id: 'b2-q28', question: 'Complete: "Had the proposal ___, we would have started."', options: ['approved', 'been approved', 'approving', 'being approved'], correctIndex: 1, explanation: 'Third conditional passif : Had + been + PP.' },
    { id: 'b2-q29', question: 'What does "symbolism" mean?', options: ['Symbol', 'Use of symbols', 'Symmetry', 'Sympathy'], correctIndex: 1, explanation: '"Symbolism" = l\'utilisation de symboles dans l\'art.' },
    { id: 'b2-q30', question: 'Complete: "Only then ___ understand the problem."', options: ['did I', 'I did', 'do I', 'I do'], correctIndex: 0, explanation: 'Inversion après "Only then" en début de phrase.' },
  ],
  C1: [
    { id: 'c1-q9', question: 'Which uses an embedded clause?', options: ['She said something', 'What she said was surprising', 'She was surprised', 'Surprisingly, she spoke'], correctIndex: 1, explanation: 'Embedded clause : "What she said" = sujet nominal.' },
    { id: 'c1-q10', question: 'Complete: "If I had studied medicine, I ___ a doctor now."', options: ['would be', 'would have been', 'will be', 'am'], correctIndex: 0, explanation: 'Mixed conditional : past condition → present result.' },
    { id: 'c1-q11', question: 'What does "pragmatics" study?', options: ['Grammar', 'Language in social context', 'Word origins', 'Sound systems'], correctIndex: 1, explanation: 'La pragmatique étudie le langage en contexte social.' },
    { id: 'c1-q12', question: 'Complete: "Not until the results ___ will we know."', options: ['are published', 'published', 'will publish', 'publishing'], correctIndex: 0, explanation: 'Après "Not until", la subordonnée garde l\'ordre normal.' },
    { id: 'c1-q13', question: 'Which is a cleft sentence?', options: ['John called', 'It was John who called', 'John was calling', 'A call from John'], correctIndex: 1, explanation: 'Cleft : "It was X who/that..." pour mettre en relief.' },
    { id: 'c1-q14', question: 'Complete: "___ we accept the premise, what follows?"', options: ['Supposing', 'Suppose', 'Supposed', 'Supposes'], correctIndex: 0, explanation: '"Supposing" = conjonction conditionnelle.' },
    { id: 'c1-q15', question: 'What does "sovereignty" mean?', options: ['Generosity', 'Supreme authority', 'Sympathy', 'Solitude'], correctIndex: 1, explanation: '"Sovereignty" = autorité suprême d\'un État.' },
    { id: 'c1-q16', question: 'Complete: "So great ___ that action was taken immediately."', options: ['was the urgency', 'the urgency was', 'is the urgency', 'the urgency is'], correctIndex: 0, explanation: 'Inversion après "So + adjective".' },
    { id: 'c1-q17', question: 'Which uses "whose" correctly?', options: ['The man whose car', 'The man who\'s car', 'The man whom car', 'The man which car'], correctIndex: 0, explanation: '"Whose" = adjectif possessif relatif.' },
    { id: 'c1-q18', question: 'Complete: "The findings ___ to support the hypothesis."', options: ['tend', 'tends', 'tending', 'has tended'], correctIndex: 0, explanation: '"Tend to" = formule de prudence académique.' },
    { id: 'c1-q19', question: 'What is "euphémisme" in English?', options: ['Eulogy', 'Euphemism', 'Evacuation', 'Evaluation'], correctIndex: 1, explanation: '"Euphemism" = terme plus doux pour une réalité dure.' },
    { id: 'c1-q20', question: 'Complete: "It was the CEO ___ made the decision."', options: ['which', 'who', 'whom', 'whose'], correctIndex: 1, explanation: 'Cleft sentence pour les personnes : "who".' },
    { id: 'c1-q21', question: 'What does "connotation" mean?', options: ['Definition', 'Associated meaning', 'Grammar rule', 'Pronunciation'], correctIndex: 1, explanation: '"Connotation" = sens implicite/associé d\'un mot.' },
    { id: 'c1-q22', question: 'Complete: "___ the urgency, action was taken."', options: ['Such was', 'Such is', 'So was', 'So is'], correctIndex: 0, explanation: '"Such was" en début de phrase = inversion.' },
    { id: 'c1-q23', question: 'Which demonstrates fronting?', options: ['I have never seen that', 'Never have I seen that', 'I never saw that', 'That I never saw'], correctIndex: 1, explanation: 'Le fronting déplace l\'élément négatif en tête + inversion.' },
    { id: 'c1-q24', question: 'Complete: "The report, the author of ___ is unknown, raises questions."', options: ['that', 'which', 'who', 'whom'], correctIndex: 1, explanation: 'Relative clause non-définissante : "which" obligatoire.' },
    { id: 'c1-q25', question: 'What does "empirical" mean?', options: ['Theoretical', 'Based on observation', 'Emotional', 'Imperial'], correctIndex: 1, explanation: '"Empirical" = basé sur l\'observation et l\'expérience.' },
    { id: 'c1-q26', question: 'Complete: "Hardly ___ when the phone rang."', options: ['had I arrived', 'I had arrived', 'I arrived', 'did I arrive'], correctIndex: 0, explanation: 'Inversion après "Hardly" : had + subject + PP.' },
    { id: 'c1-q27', question: 'Which is a mixed conditional?', options: ['If I had studied, I would pass', 'If I studied, I would have passed', 'If I study, I will pass', 'If I had studied, I would have passed'], correctIndex: 0, explanation: 'Mixed : condition passée → résultat présent.' },
    { id: 'c1-q28', question: 'Complete: "At no time ___ the regulations."', options: ['did we violate', 'we violated', 'we did violate', 'violated we'], correctIndex: 0, explanation: 'Inversion après "At no time".' },
    { id: 'c1-q29', question: 'What does "jurisdiction" mean?', options: ['Justice', 'Legal authority', 'Jurisprudence', 'Jury selection'], correctIndex: 1, explanation: '"Jurisdiction" = autorité légale/compétence juridique.' },
    { id: 'c1-q30', question: 'Complete: "Only after the meeting ___ the decision."', options: ['was announced', 'announced', 'has announcing', 'announcing'], correctIndex: 0, explanation: 'Inversion passive après "Only after".' },
  ],
  C2: [
    { id: 'c2-q9', question: 'What does "hermeneutics" study?', options: ['Heraldry', 'Interpretation theory', 'Heredity', 'Hypnosis'], correctIndex: 1, explanation: 'L\'herméneutique est la théorie de l\'interprétation.' },
    { id: 'c2-q10', question: 'Which is an example of chiasmus?', options: ['Ask not what your country can do for you', 'I came, I saw, I conquered', 'To be or not to be', 'Out, out, brief candle'], correctIndex: 0, explanation: 'Le chiasme inverse l\'ordre des mots dans des phrases parallèles.' },
    { id: 'c2-q11', question: 'What does "semiotics" study?', options: ['Semi-precious stones', 'Signs and symbols', 'Semitic languages', 'Semiconductors'], correctIndex: 1, explanation: 'La sémiotique étudie les signes et symboles.' },
    { id: 'c2-q12', question: 'Complete: "Little ___ how significant the discovery would prove."', options: ['did anyone realize', 'anyone realized', 'anyone did realize', 'realized anyone'], correctIndex: 0, explanation: 'Inversion après "Little" en début de phrase.' },
    { id: 'c2-q13', question: 'What is "intertextuality"?', options: ['Internet text', 'References between texts', 'Internal structure', 'Interactive text'], correctIndex: 1, explanation: 'L\'intertextualité = relations entre différents textes.' },
    { id: 'c2-q14', question: 'Complete the zeugma: "He ___ his tea and his patience."', options: ['drank', 'lost', 'finished', 'consumed'], correctIndex: 3, explanation: 'Le zeugme utilise un verbe avec deux compléments dans des sens différents.' },
    { id: 'c2-q15', question: 'What does "deontology" mean?', options: ['Dentistry', 'Ethics based on duty', 'Demonology', 'Deontology'], correctIndex: 1, explanation: 'La déontologie est une éthique basée sur le devoir.' },
    { id: 'c2-q16', question: 'Which demonstrates anacoluthon?', options: ['If he had come, I would have left', 'If he had come — but he didn\'t — well, never mind', 'If he comes, I will leave', 'If he came, I would leave'], correctIndex: 1, explanation: 'L\'anacoluthe est une rupture délibérée de structure grammaticale.' },
    { id: 'c2-q17', question: 'Complete: "Had it not ___ for the intervention, the crisis would have deepened."', options: ['been', 'be', 'being', 'was'], correctIndex: 0, explanation: 'Conditionnel inversé passif : Had it not been for.' },
    { id: 'c2-q18', question: 'What is "provenance" in context?', options: ['Providence', 'Origin and history', 'Provision', 'Probability'], correctIndex: 1, explanation: '"Provenance" = origine et historique d\'un objet.' },
    { id: 'c2-q19', question: 'Complete: "___ the inherent contradictions, the theory remains influential."', options: ['Notwithstanding', 'Not standing', 'With standing', 'Standing not'], correctIndex: 0, explanation: '"Notwithstanding" = concession formelle = malgré.' },
    { id: 'c2-q20', question: 'Which uses syllepsis?', options: ['She took her coat and her leave', 'She took a coat and a hat', 'She left her coat and left', 'She wore a coat and took a hat'], correctIndex: 0, explanation: 'Le syllepse utilise un mot dans plusieurs sens à la fois.' },
    { id: 'c2-q21', question: 'What does "epistemology" study?', options: ['Epidemics', 'Nature of knowledge', 'Epigraphy', 'Epidemiology'], correctIndex: 1, explanation: 'L\'épistémologie étudie la nature et les limites du savoir.' },
    { id: 'c2-q22', question: 'Complete: "The very fact ___ she refused speaks volumes."', options: ['that', 'which', 'what', 'who'], correctIndex: 0, explanation: 'Appositive clause avec "the fact that".' },
    { id: 'c2-q23', question: 'What is "enjambment"?', options: ['A type of rhyme', 'Running a line into the next', 'A poetic meter', 'A stanza form'], correctIndex: 1, explanation: 'L\'enjambement = continuation d\'une phrase au vers suivant.' },
    { id: 'c2-q24', question: 'Complete: "Such ___ the complexity that even experts struggled."', options: ['was', 'is', 'were', 'being'], correctIndex: 0, explanation: 'Inversion après "Such + be" : Such was... (passé).' },
    { id: 'c2-q25', question: 'What does "polemic" mean?', options: ['Pole vaulting', 'Controversial argument', 'Political science', 'Police matter'], correctIndex: 1, explanation: '"Polemic" = argumentation polémique/agressive.' },
    { id: 'c2-q26', question: 'Complete: "It is not so much the content ___ the form that matters."', options: ['as', 'that', 'but', 'than'], correctIndex: 0, explanation: 'Correlative conjunction : "Not so much X as Y".' },
    { id: 'c2-q27', question: 'What is "satire"?', options: ['Saturation', 'Use of humor to criticize', 'Satisfaction', 'Satellite'], correctIndex: 1, explanation: 'La satire utilise l\'humour pour critiquer la société.' },
    { id: 'c2-q28', question: 'Complete: "The text can ___ as both critique and celebration."', options: ['be read', 'read', 'reading', 'being read'], correctIndex: 0, explanation: 'Infinitif passif : can + be + participe passé.' },
    { id: 'c2-q29', question: 'What does "existentialism" emphasize?', options: ['Existence of God', 'Individual freedom and choice', 'External reality', 'Expedition'], correctIndex: 1, explanation: 'L\'existentialisme met l\'accent sur la liberté individuelle.' },
    { id: 'c2-q30', question: 'Complete: "The argument ___ on the assumption that all values are relative."', options: ['rests', 'rest', 'resting', 'rested'], correctIndex: 0, explanation: '"Rests on" = repose sur. Accord singulier.' },
  ],
}

// ─── Additional Grammar Data per Level ───────────────────────────────────────

const EXTRA_GRAMMAR: Record<string, GrammarExercise[]> = {
  A1: [
    { id: 'a1-g9', sentence: 'We ___ (to be) from Paris.', answer: 'are', hint: 'Première personne pluriel' },
    { id: 'a1-g10', sentence: 'He ___ (to like) coffee.', answer: 'likes', hint: '3e personne singulier, présent simple' },
    { id: 'a1-g11', sentence: '___ (I/you) want some tea?', answer: 'Do', hint: 'Question avec "you" au présent simple' },
    { id: 'a1-g12', sentence: 'She ___ (to not/play) football.', answer: "doesn't play", hint: 'Négation, 3e personne singulier' },
    { id: 'a1-g13', sentence: '___ (there be) two cats on the sofa.', answer: 'There are', hint: 'Pluriel avec "there"' },
    { id: 'a1-g14', sentence: 'I ___ (to can) swim.', answer: 'can', hint: 'Modal verb, pas de -s' },
    { id: 'a1-g15', sentence: 'They ___ (to not/be) happy.', answer: "aren't", hint: 'Négation de "are"' },
    { id: 'a1-g16', sentence: '___ (question word) is your name?', answer: 'What', hint: 'Pour demander le nom' },
    { id: 'a1-g17', sentence: 'My sister ___ (to work) in a bank.', answer: 'works', hint: '3e personne singulier + -s' },
    { id: 'a1-g18', sentence: '___ (article) university is important.', answer: 'A', hint: 'Bien que "u" soit voyelle, le son est consonant' },
    { id: 'a1-g19', sentence: 'The children ___ (to be) in the garden.', answer: 'are', hint: 'Pluriel irrégulier : child → children' },
    { id: 'a1-g20', sentence: '___ (where/when) do you live?', answer: 'Where', hint: 'Pour demander le lieu' },
    { id: 'a1-g21', sentence: 'I ___ (to have) two brothers.', answer: 'have', hint: 'Première personne, présent simple' },
    { id: 'a1-g22', sentence: 'She ___ (to not/have) a car.', answer: "doesn't have", hint: 'Négation avec "does not"' },
    { id: 'a1-g23', sentence: '___ (how/what) old are you?', answer: 'How', hint: 'Pour demander l\'âge' },
    { id: 'a1-g24', sentence: 'He ___ (to go) to work by bus.', answer: 'goes', hint: '3e personne : go → goes' },
    { id: 'a1-g25', sentence: 'We ___ (to not/like) spicy food.', answer: "don't like", hint: 'Négation avec "do not"' },
    { id: 'a1-g26', sentence: '___ (this/these) is my book.', answer: 'This', hint: 'Singulier : proche' },
    { id: 'a1-g27', sentence: '___ (that/those) are my shoes.', answer: 'Those', hint: 'Pluriel : éloigné' },
    { id: 'a1-g28', sentence: 'The cat is ___ (preposition) the table.', answer: 'on', hint: 'Sur la table' },
    { id: 'a1-g29', sentence: 'I get up ___ (preposition) 7 o\'clock.', answer: 'at', hint: 'Pour les heures exactes' },
    { id: 'a1-g30', sentence: 'She ___ (to watch) TV every evening.', answer: 'watches', hint: '3e personne : watch → watches (après ch)' },
  ],
  A2: [
    { id: 'a2-g9', sentence: 'If I ___ (to have) more time, I would travel.', answer: 'had', hint: 'Second conditional : past simple' },
    { id: 'a2-g10', sentence: 'I ___ (to eat) dinner when you called.', answer: 'was eating', hint: 'Past continuous : was + verb-ing' },
    { id: 'a2-g11', sentence: 'She ___ (to go) to London next week.', answer: 'is going', hint: 'Futur planifié : be going to' },
    { id: 'a2-g12', sentence: 'We ___ (to be) friends since 2015.', answer: 'have been', hint: 'Present perfect avec "since"' },
    { id: 'a2-g13', sentence: '___ (much/many) sugar do you need?', answer: 'How much', hint: '"Much" pour les indénombrables' },
    { id: 'a2-g14', sentence: 'He ___ (to be) born in 1990.', answer: 'was', hint: 'Passé simple de "be"' },
    { id: 'a2-g15', sentence: 'I ___ (to already/finish) my homework.', answer: 'have already finished', hint: 'Present perfect + already' },
    { id: 'a2-g16', sentence: '___ (some/any) people came to the party.', answer: 'Some', hint: '"Some" dans les phrases affirmatives' },
    { id: 'a2-g17', sentence: 'She is ___ (tall) than her sister.', answer: 'taller', hint: 'Comparatif : adjective + -er' },
    { id: 'a2-g18', sentence: 'This is the ___ (beautiful) city I have ever seen.', answer: 'most beautiful', hint: 'Superlatif des adjectifs longs' },
    { id: 'a2-g19', sentence: 'You ___ (to not/have to) come if you don\'t want to.', answer: "don't have to", hint: 'Pas obligatoire' },
    { id: 'a2-g20', sentence: 'I ___ (to live) here for five years.', answer: 'have lived', hint: 'Present perfect avec "for"' },
    { id: 'a2-g21', sentence: 'The train ___ (to leave) at 9 AM every day.', answer: 'leaves', hint: 'Présent simple pour les horaires' },
    { id: 'a2-g22', sentence: 'She ___ (to be) able to swim since she was five.', answer: 'has been', hint: 'Present perfect de "be"' },
    { id: 'a2-g23', sentence: 'I ___ (to never/see) that movie.', answer: 'have never seen', hint: 'Present perfect + never' },
    { id: 'a2-g24', sentence: 'He ___ (to break) his leg while skiing.', answer: 'broke', hint: 'Passé simple de "break"' },
    { id: 'a2-g25', sentence: 'We ___ (to go) to the beach tomorrow.', answer: 'are going', hint: 'Be going to pour les plans' },
    { id: 'a2-g26', sentence: 'The restaurant ___ (to close) at 10 PM.', answer: 'closes', hint: '3e personne + -es après s/z' },
    { id: 'a2-g27', sentence: 'I wish I ___ (to can) speak Chinese.', answer: 'could', hint: 'Past de "can" après "wish"' },
    { id: 'a2-g28', sentence: 'She ___ (to study) English for three years.', answer: 'has studied', hint: 'Present perfect avec durée' },
    { id: 'a2-g29', sentence: '___ (there be) enough food for everyone?', answer: 'Is there', hint: 'Question avec "there"' },
    { id: 'a2-g30', sentence: 'They ___ (to move) to Paris next month.', answer: 'are going to move', hint: 'Plan futur : be going to' },
  ],
  B1: [
    { id: 'b1-g9', sentence: 'The report ___ (to publish) last week.', answer: 'was published', hint: 'Passive voice, past' },
    { id: 'b1-g10', sentence: 'If I ___ (to be) you, I would accept.', answer: 'were', hint: 'Second conditional : were' },
    { id: 'b1-g11', sentence: 'By 2030, scientists ___ (to discover) new treatments.', answer: 'will have discovered', hint: 'Future perfect' },
    { id: 'b1-g12', sentence: 'She suggested that he ___ (to leave) early.', answer: 'leave', hint: 'Subjunctive after suggest' },
    { id: 'b1-g13', sentence: 'I wish I ___ (to save) more money.', answer: 'had saved', hint: 'Wish + past perfect for past regrets' },
    { id: 'b1-g14', sentence: 'He denied ___ (to steal) the money.', answer: 'stealing', hint: 'Gerund after deny' },
    { id: 'b1-g15', sentence: 'The house ___ (to build) in 1990 is now a museum.', answer: 'built', hint: 'Reduced relative clause' },
    { id: 'b1-g16', sentence: 'She is used ___ (preposition) working late.', answer: 'to', hint: '"Be used to" + -ing' },
    { id: 'b1-g17', sentence: 'I would rather you ___ (to come) tomorrow.', answer: 'came', hint: 'Would rather + past' },
    { id: 'b1-g18', sentence: 'He ___ (to work) here since 2010.', answer: 'has worked', hint: 'Present perfect + since' },
    { id: 'b1-g19', sentence: 'The book ___ (to write) by a famous author became a bestseller.', answer: 'written', hint: 'Participle passé comme adjectif' },
    { id: 'b1-g20', sentence: 'She insisted on ___ (to pay) for the meal.', answer: 'paying', hint: 'Gerund after "insist on"' },
    { id: 'b1-g21', sentence: 'He must ___ (to work) late last night.', answer: 'have worked', hint: 'Must have + PP = déduction passée' },
    { id: 'b1-g22', sentence: 'I regret ___ (to not/study) harder at school.', answer: 'not studying', hint: 'Regret + gerund = regret for past action' },
    { id: 'b1-g23', sentence: 'It\'s time we ___ (to leave).', answer: 'left', hint: '"It\'s time" + past simple' },
    { id: 'b1-g24', sentence: 'They made him ___ (to work) overtime.', answer: 'work', hint: 'Make + object + bare infinitive' },
    { id: 'b1-g25', sentence: '___ (to be) a doctor, she knows about health.', answer: 'Being', hint: 'Participle présent pour exprimer la cause' },
    { id: 'b1-g26', sentence: 'Not until he arrived ___ (we/to start) the meeting.', answer: 'did we start', hint: 'Inversion après "Not until"' },
    { id: 'b1-g27', sentence: 'I ___ (to never/see) such a beautiful sunset before.', answer: 'had never seen', hint: 'Past perfect : had + PP' },
    { id: 'b1-g28', sentence: 'She reminded me ___ (to call) the doctor.', answer: 'to call', hint: 'Remind + object + infinitive' },
    { id: 'b1-g29', sentence: 'He is considering ___ (to change) jobs.', answer: 'changing', hint: 'Consider + gerund' },
    { id: 'b1-g30', sentence: 'If she ___ (to know) the answer, she would tell us.', answer: 'knew', hint: 'Second conditional : past simple' },
  ],
  B2: [
    { id: 'b2-g9', sentence: 'Rarely ___ (she/to go) to that restaurant.', answer: 'does she go', hint: 'Negative adverbial inversion' },
    { id: 'b2-g10', sentence: 'The rapid ___ (to expand) was unexpected.', answer: 'expansion', hint: 'Nominalization : expand → expansion' },
    { id: 'b2-g11', sentence: 'Had the proposal ___ (to approve), we would have started.', answer: 'been approved', hint: 'Third conditional passive' },
    { id: 'b2-g12', sentence: 'Not only ___ (she/to pass), but she got the highest score.', answer: 'did she pass', hint: 'Inversion after "Not only"' },
    { id: 'b2-g13', sentence: 'It ___ (to appear) that further research is needed.', answer: 'appears', hint: 'Hedging phrase' },
    { id: 'b2-g14', sentence: 'The data ___ (to collect) over five years.', answer: 'were collected', hint: 'Passive voice, data = plural' },
    { id: 'b2-g15', sentence: 'Under no circumstances ___ (you/to reveal) the source.', answer: 'should you reveal', hint: 'Inversion after negative fronting' },
    { id: 'b2-g16', sentence: 'So great ___ (the urgency/to be) that action was taken.', answer: 'was the urgency', hint: 'Inversion after "So + adjective"' },
    { id: 'b2-g17', sentence: 'The contract, ___ (which/that) was signed yesterday, is valid.', answer: 'which', hint: 'Non-defining relative clause' },
    { id: 'b2-g18', sentence: 'The research ___ (to tend) to support the hypothesis.', answer: 'tends', hint: 'Hedging with "tend to"' },
    { id: 'b2-g19', sentence: 'Only then ___ (I/to understand) the problem.', answer: 'did I understand', hint: 'Inversion after "Only then"' },
    { id: 'b2-g20', sentence: 'The findings, ___ (which/that) were published last month, are significant.', answer: 'which', hint: 'Non-defining relative clause uses "which"' },
    { id: 'b2-g21', sentence: 'No sooner ___ (she/to arrive) than the phone rang.', answer: 'had she arrived', hint: 'Inversion after "No sooner"' },
    { id: 'b2-g22', sentence: 'He took it for ___ (to grant) that she would agree.', answer: 'granted', hint: '"Take for granted" = considérer comme acquis' },
    { id: 'b2-g23', sentence: 'She was ___ (to/in order to) exhausted to continue.', answer: 'too', hint: '"Too... to" = trop... pour' },
    { id: 'b2-g24', sentence: 'The government, ___ (whose/who\'s) policy was controversial, defended it.', answer: 'whose', hint: 'Possessive relative pronoun' },
    { id: 'b2-g25', sentence: 'He ___ (to account) for the discrepancy in the data.', answer: 'accounted', hint: '"Account for" = expliquer' },
    { id: 'b2-g26', sentence: 'It is imperative that the report ___ (to submit) on time.', answer: 'be submitted', hint: 'Subjunctive passive after "imperative"' },
    { id: 'b2-g27', sentence: 'The method ___ (to employ) in this study is innovative.', answer: 'employed', hint: 'Participle passé comme adjectif' },
    { id: 'b2-g28', sentence: 'She could not but ___ (to agree) with the conclusion.', answer: 'agree', hint: '"Cannot but" + bare infinitive' },
    { id: 'b2-g29', sentence: 'The report, the significance of ___ cannot be overstated, was published today.', answer: 'which', hint: 'Relative clause with "of which"' },
    { id: 'b2-g30', sentence: 'The more you practice, the ___ (good) you become.', answer: 'better', hint: 'Correlative comparative : the + comparative' },
  ],
  C1: [
    { id: 'c1-g9', sentence: 'What ___ (she/to say) at the meeting was surprising.', answer: 'she said', hint: 'Embedded clause : subject-verb order' },
    { id: 'c1-g10', sentence: 'If I ___ (to study) medicine, I would be a doctor now.', answer: 'had studied', hint: 'Mixed conditional : past condition → present result' },
    { id: 'c1-g11', sentence: 'So great ___ (the urgency/to be) that action was taken immediately.', answer: 'was the urgency', hint: 'Inversion after "So + adjective"' },
    { id: 'c1-g12', sentence: 'It was the CEO ___ (who/which) made the decision.', answer: 'who', hint: 'Cleft sentence for emphasis' },
    { id: 'c1-g13', sentence: '___ (to suppose) we accept the premise, what follows?', answer: 'Supposing', hint: 'Conditional conjunction' },
    { id: 'c1-g14', sentence: 'Not until the report ___ (to publish) will we know the truth.', answer: 'is published', hint: 'Negative fronting + present simple' },
    { id: 'c1-g15', sentence: 'The minister, ___ (whose/who\'s) position was untenable, resigned.', answer: 'whose', hint: 'Possessive relative pronoun' },
    { id: 'c1-g16', sentence: 'The findings ___ (to tend) to support the hypothesis.', answer: 'tend', hint: 'Hedging with "tend to"' },
    { id: 'c1-g17', sentence: 'Hardly ___ (she/to arrive) when the meeting started.', answer: 'had she arrived', hint: 'Inversion after "Hardly"' },
    { id: 'c1-g18', sentence: 'It is not so much the content ___ (as/that) the form that matters.', answer: 'as', hint: 'Correlative : not so much X as Y' },
    { id: 'c1-g19', sentence: 'At no time ___ (we/to consider) abandoning the project.', answer: 'did we consider', hint: 'Inversion after "At no time"' },
    { id: 'c1-g20', sentence: 'The report, the implications of ___ are far-reaching, demands attention.', answer: 'which', hint: 'Relative clause : of which' },
    { id: 'c1-g21', sentence: 'Were the situation ___ (to reverse), the outcome would be different.', answer: 'to be reversed', hint: 'Inverted conditional passive' },
    { id: 'c1-g22', sentence: 'Only by ___ (to examine) the data can we draw conclusions.', answer: 'examining', hint: 'Gerund after preposition + inversion' },
    { id: 'c1-g23', sentence: 'She speaks as though she ___ (to know) everything.', answer: 'knew', hint: 'As if/as though + past (irrealis)' },
    { id: 'c1-g24', sentence: 'The very fact ___ (that/which) she refused is significant.', answer: 'that', hint: 'Appositive clause use "that"' },
    { id: 'c1-g25', sentence: '___ (to see) from this perspective, the decision makes sense.', answer: 'Seen', hint: 'Past participle for passive meaning' },
    { id: 'c1-g26', sentence: 'Much ___ (to anticipate), the results exceeded expectations.', answer: 'anticipated', hint: 'Past participle : much anticipated' },
    { id: 'c1-g27', sentence: 'He would sooner ___ (to resign) than compromise his principles.', answer: 'resign', hint: 'Would sooner + bare infinitive' },
    { id: 'c1-g28', sentence: 'Notwithstanding the difficulties, the team ___ (to persevere).', answer: 'persevered', hint: '"Notwithstanding" = malgré' },
    { id: 'c1-g29', sentence: 'Little ___ (they/to realize) how much things would change.', answer: 'did they realize', hint: 'Inversion after "Little"' },
    { id: 'c1-g30', sentence: 'The proposal, ___ (far/from) being rejected, was warmly received.', answer: 'far', hint: '"Far from" + gerund : loin de' },
  ],
  C2: [
    { id: 'c2-g9', sentence: 'Little ___ (anyone/to realize) how significant the discovery would prove.', answer: 'did anyone realize', hint: 'Negative adverbial inversion with "little"' },
    { id: 'c2-g10', sentence: 'The text can ___ (to read) as both critique and celebration.', answer: 'be read', hint: 'Passive infinitive' },
    { id: 'c2-g11', sentence: 'Had it not ___ (to be) for the intervention, the crisis would have deepened.', answer: 'been', hint: 'Inverted conditional : Had it not been for' },
    { id: 'c2-g12', sentence: 'Such ___ (to be) the complexity that even experts struggled.', answer: 'was', hint: 'Inversion after "Such + be"' },
    { id: 'c2-g13', sentence: 'The argument ___ (to rest) on the assumption that all values are relative.', answer: 'rests', hint: 'Subject-verb agreement with singular' },
    { id: 'c2-g14', sentence: '___ (to be) the inherent contradictions, the theory remains influential.', answer: 'Notwithstanding', hint: 'Formal concession' },
    { id: 'c2-g15', sentence: 'The very fact ___ (that/which) she refused speaks volumes.', answer: 'that', hint: 'Appositive clause with "the fact that"' },
    { id: 'c2-g16', sentence: 'It is not so much the content ___ (as/that) the form that matters.', answer: 'as', hint: 'Correlative conjunction : not so much X as Y' },
    { id: 'c2-g17', sentence: '___ (to suppose) the data are unreliable, what conclusions can we draw?', answer: 'Supposing', hint: 'Conditional conjunction in formal register' },
    { id: 'c2-g18', sentence: 'Nowhere in the text ___ (the author/to acknowledge) this possibility.', answer: 'does the author acknowledge', hint: 'Inversion after negative adverbial' },
    { id: 'c2-g19', sentence: 'To say nothing of the ethical implications, the practical difficulties ___ (to be) considerable.', answer: 'are', hint: 'Subject-verb agreement after parenthetical' },
    { id: 'c2-g20', sentence: 'Seldom ___ (such/a) nuanced analysis been presented.', answer: 'has such', hint: 'Inversion after "Seldom" with present perfect' },
    { id: 'c2-g21', sentence: 'The monograph, ___ (which/that) was published posthumously, remains definitive.', answer: 'which', hint: 'Non-defining relative clause' },
    { id: 'c2-g22', sentence: 'Only when the evidence ___ (to become) irrefutable did they concede.', answer: 'became', hint: 'Inversion after "Only when" + past simple' },
    { id: 'c2-g23', sentence: 'Be that as it ___ (to be), the practical implications are clear.', answer: 'may', hint: 'Fixed expression : "Be that as it may"' },
    { id: 'c2-g24', sentence: 'The discourse, far from ___ (to be) coherent, is riddled with contradictions.', answer: 'being', hint: '"Far from" + gerund' },
    { id: 'c2-g25', sentence: '___ (to come) to the crux of the matter, the issue is one of interpretation.', answer: 'Coming', hint: 'Present participle as discourse marker' },
    { id: 'c2-g26', sentence: 'In no uncertain terms ___ (she/to reject) the proposal.', answer: 'did she reject', hint: 'Inversion after "In no uncertain terms"' },
    { id: 'c2-g27', sentence: 'The more rigorously the methodology ___ (to apply), the more reliable the results.', answer: 'is applied', hint: 'Correlative comparative + passive' },
    { id: 'c2-g28', sentence: 'Thus ___ (to end) the most controversial chapter in the institution\'s history.', answer: 'ended', hint: 'Formal/literary inversion after "thus"' },
    { id: 'c2-g29', sentence: 'Were the truth ___ (to know), public reaction would be severe.', answer: 'to be known', hint: 'Inverted conditional passive infinitive' },
    { id: 'c2-g30', sentence: 'Notwithstanding the objections, the board ___ (to ratify) the decision unanimously.', answer: 'ratified', hint: 'Formal concession + past simple' },
  ],
}

// ─── Additional Pronunciation Data per Level ─────────────────────────────────

const EXTRA_PRONUNCIATION: Record<string, PronunciationWord[]> = {
  A1: [
    { id: 'a1-p11', word: 'Beautiful', phonetic: '/ˈbjuːtɪfl/', tip: 'Dites "biou-ti-foul". L\'accent est sur "biou".', difficulty: 'medium' },
    { id: 'a1-p12', word: 'Friend', phonetic: '/frend/', tip: 'Le "ie" se prononce "é" comme dans "fren-de".', difficulty: 'easy' },
    { id: 'a1-p13', word: 'Mother', phonetic: '/ˈmʌðər/', tip: 'Le "th" est doux comme dans "this". Accent sur "muh".', difficulty: 'medium' },
    { id: 'a1-p14', word: 'Brother', phonetic: '/ˈbrʌðər/', tip: 'Même "th" doux que "mother". Accent sur "bruh".', difficulty: 'medium' },
    { id: 'a1-p15', word: 'Sister', phonetic: '/ˈsɪstər/', tip: 'Le "i" est court comme dans "si". Le "er" final est léger.', difficulty: 'easy' },
    { id: 'a1-p16', word: 'Bread', phonetic: '/bred/', tip: 'Le "ea" se prononce "é" court. Pas "i" comme dans "read".', difficulty: 'medium' },
    { id: 'a1-p17', word: 'Money', phonetic: '/ˈmʌni/', tip: 'Le "o" sonne comme "eu" français. Accent sur "muh".', difficulty: 'easy' },
    { id: 'a1-p18', word: 'Number', phonetic: '/ˈnʌmbər/', tip: 'Le "u" est comme "eu" français. Le "b" est léger.', difficulty: 'easy' },
    { id: 'a1-p19', word: 'Eight', phonetic: '/eɪt/', tip: 'Se prononce "èïte". Le "gh" est muet.', difficulty: 'medium' },
    { id: 'a1-p20', word: 'Twelve', phonetic: '/twelv/', tip: 'Dites "tou-èl-v". Le "w" est arrondi.', difficulty: 'medium' },
    { id: 'a1-p21', word: 'Yellow', phonetic: '/ˈjeloʊ/', tip: 'Le "y" sonne comme un "i" français. Accent sur "yé".', difficulty: 'easy' },
    { id: 'a1-p22', word: 'Purple', phonetic: '/ˈpɜːrpəl/', tip: 'Le "ur" sonne "eur". Le "ple" est doux.', difficulty: 'medium' },
    { id: 'a1-p23', word: 'Orange', phonetic: '/ˈɒrɪndʒ/', tip: 'Le "a" est ouvert. Le "ge" final sonne "dj".', difficulty: 'medium' },
    { id: 'a1-p24', word: 'White', phonetic: '/waɪt/', tip: 'Le "wh" sonne "ou". Dites "ou-aïte".', difficulty: 'easy' },
    { id: 'a1-p25', word: 'Black', phonetic: '/blæk/', tip: 'Le "a" est ouvert comme dans "cat".', difficulty: 'easy' },
    { id: 'a1-p26', word: 'Seventy', phonetic: '/ˈsevənti/', tip: 'Accent sur "se". Le "ty" se dit "ti".', difficulty: 'medium' },
    { id: 'a1-p27', word: 'Hundred', phonetic: '/ˈhʌndrəd/', tip: 'Le "u" sonne "eu". Le "dr" est lié.', difficulty: 'medium' },
    { id: 'a1-p28', word: 'Today', phonetic: '/təˈdeɪ/', tip: 'Accent sur "day". Le premier "o" est schwa (ə).', difficulty: 'easy' },
    { id: 'a1-p29', word: 'Tomorrow', phonetic: '/təˈmɒroʊ/', tip: 'Accent sur "mo". Le premier "o" est schwa.', difficulty: 'medium' },
    { id: 'a1-p30', word: 'Yesterday', phonetic: '/ˈjestərdeɪ/', tip: 'Accent sur "yes". Le "y" initial = "i" français.', difficulty: 'medium' },
  ],
  A2: [
    { id: 'a2-p11', word: 'Destination', phonetic: '/ˌdestɪˈneɪʃən/', tip: 'Accent sur "na". 4 syllabes.', difficulty: 'hard' },
    { id: 'a2-p12', word: 'Restaurant', phonetic: '/ˈrestərɒnt/', tip: 'Se dit "res-teu-ront" en anglais, pas "res-to-ran".', difficulty: 'medium' },
    { id: 'a2-p13', word: 'Luggage', phonetic: '/ˈlʌɡɪdʒ/', tip: 'Le "u" = "eu". Le "age" final sonne "idj".', difficulty: 'medium' },
    { id: 'a2-p14', word: 'Bicycle', phonetic: '/ˈbaɪsɪkl/', tip: 'Se dit "baï-si-kel". 3 syllabes.', difficulty: 'easy' },
    { id: 'a2-p15', word: 'Furniture', phonetic: '/ˈfɜːrnɪtʃər/', tip: 'Accent sur "fur". Le "ni" est léger.', difficulty: 'hard' },
    { id: 'a2-p16', word: 'Wardrobe', phonetic: '/ˈwɔːrdroʊb/', tip: 'Le "w" est arrondi. Le "obe" sonne "ôbe".', difficulty: 'medium' },
    { id: 'a2-p17', word: 'Prescription', phonetic: '/prɪˈskrɪpʃən/', tip: 'Accent sur "scrip". Le "tion" = "chən".', difficulty: 'hard' },
    { id: 'a2-p18', word: 'Diagnosis', phonetic: '/ˌdaɪəɡˈnoʊsɪs/', tip: 'Le "g" est muet devant "n". Accent sur "no".', difficulty: 'hard' },
    { id: 'a2-p19', word: 'Temperature', phonetic: '/ˈtemprətʃər/', tip: 'Se dit souvent "tem-pruh-cher" rapidement.', difficulty: 'hard' },
    { id: 'a2-p20', word: 'Receipt', phonetic: '/rɪˈsiːt/', tip: 'Le "p" est MUET. Dites "ri-sïte".', difficulty: 'medium' },
    { id: 'a2-p21', word: 'Reservation', phonetic: '/ˌrezərˈveɪʃən/', tip: 'Accent sur "va". Le "tion" = "chən".', difficulty: 'medium' },
    { id: 'a2-p22', word: 'Conference', phonetic: '/ˈkɒnfərəns/', tip: 'Accent sur "con". Le "fer" est léger.', difficulty: 'medium' },
    { id: 'a2-p23', word: 'Improvement', phonetic: '/ɪmˈpruːvmənt/', tip: 'Accent sur "prove". Le "ment" est très léger.', difficulty: 'medium' },
    { id: 'a2-p24', word: 'Environment', phonetic: '/ɪnˈvaɪrənmənt/', tip: 'Accent sur "vi". On dit "en-VI-ren-ment".', difficulty: 'hard' },
    { id: 'a2-p25', word: 'Education', phonetic: '/ˌedʒʊˈkeɪʃən/', tip: 'Accent sur "ca". Le "e" initial est court.', difficulty: 'medium' },
    { id: 'a2-p26', word: 'Delicious', phonetic: '/dɪˈlɪʃəs/', tip: 'Accent sur "li". Le "ious" se dit "əs".', difficulty: 'medium' },
    { id: 'a2-p27', word: 'Comfortable', phonetic: '/ˈkʌmftəbl/', tip: 'Se dit souvent "kamf-teu-bel" (3 syllabes), pas 4.', difficulty: 'hard' },
    { id: 'a2-p28', word: 'Vegetable', phonetic: '/ˈvedʒtəbl/', tip: 'Se dit "vej-teu-bel". Le "e" après "g" est muet.', difficulty: 'medium' },
    { id: 'a2-p29', word: 'Breakfast', phonetic: '/ˈbrekfəst/', tip: 'Se dit "brek-feust". Pas "bre-a-kfast".', difficulty: 'medium' },
    { id: 'a2-p30', word: 'Chocolate', phonetic: '/ˈtʃɒklət/', tip: 'Se dit "tchok-let" (3 syllabes), pas 4.', difficulty: 'easy' },
  ],
  B1: [
    { id: 'b1-p11', word: 'Achievement', phonetic: '/əˈtʃiːvmənt/', tip: 'Accent sur "chieve". Le "a" initial est schwa.', difficulty: 'medium' },
    { id: 'b1-p12', word: 'Determination', phonetic: '/dɪˌtɜːrmɪˈneɪʃən/', tip: 'Accent principal sur "na". Mot long à syllabes régulières.', difficulty: 'hard' },
    { id: 'b1-p13', word: 'Discrimination', phonetic: '/dɪˌskrɪmɪˈneɪʃən/', tip: 'Accent sur "na". Rythme régulier malgré la longueur.', difficulty: 'hard' },
    { id: 'b1-p14', word: 'Conservation', phonetic: '/ˌkɒnsərˈveɪʃən/', tip: 'Accent sur "va". Le "tion" se dit "chən".', difficulty: 'medium' },
    { id: 'b1-p15', word: 'Responsibility', phonetic: '/rɪˌspɒnsəˈbɪləti/', tip: 'Accent sur "bi". Pratiquez syllabe par syllabe.', difficulty: 'hard' },
    { id: 'b1-p16', word: 'Opportunity', phonetic: '/ˌɒpəˈtjuːnəti/', tip: 'Accent sur "tu". Dites "op-er-TU-ni-ti".', difficulty: 'hard' },
    { id: 'b1-p17', word: 'Collaboration', phonetic: '/kəˌlæbəˈreɪʃən/', tip: 'Accent sur "ra". 5 syllabes.', difficulty: 'medium' },
    { id: 'b1-p18', word: 'Sustainable', phonetic: '/səˈsteɪnəbl/', tip: 'Accent sur "stain". Le "able" final est doux.', difficulty: 'medium' },
    { id: 'b1-p19', word: 'Innovation', phonetic: '/ˌɪnəˈveɪʃən/', tip: 'Accent sur "va". Le "tion" = "chən".', difficulty: 'medium' },
    { id: 'b1-p20', word: 'Consequence', phonetic: '/ˈkɒnsɪkwəns/', tip: 'Accent sur "con". Le "quence" sonne "kouenss".', difficulty: 'medium' },
    { id: 'b1-p21', word: 'Negotiation', phonetic: '/nɪˌɡoʊʃiˈeɪʃən/', tip: 'Accent sur "a". 5 syllabes régulières.', difficulty: 'hard' },
    { id: 'b1-p22', word: 'Breakthrough', phonetic: '/ˈbreɪkθruː/', tip: 'Deux mots : "break" + "through". Accent sur "break".', difficulty: 'medium' },
    { id: 'b1-p23', word: 'Perspective', phonetic: '/pərˈspektɪv/', tip: 'Accent sur "spec". Le "per" initial est schwa.', difficulty: 'medium' },
    { id: 'b1-p24', word: 'Phenomenon', phonetic: '/fɪˈnɒmɪnən/', tip: 'Accent sur "no". Pluriel irrégulier : phenomena.', difficulty: 'hard' },
    { id: 'b1-p25', word: 'Legislation', phonetic: '/ˌledʒɪsˈleɪʃən/', tip: 'Accent sur "la". Le "gis" sonne "djis".', difficulty: 'hard' },
    { id: 'b1-p26', word: 'Assessment', phonetic: '/əˈsesmənt/', tip: 'Accent sur "ses". Double "s" = son "s".', difficulty: 'medium' },
    { id: 'b1-p27', word: 'Advocacy', phonetic: '/ˈædvəkəsi/', tip: 'Accent sur "ad". Le "cy" se dit "si".', difficulty: 'medium' },
    { id: 'b1-p28', word: 'Endurance', phonetic: '/ɪnˈdjʊrəns/', tip: 'Accent sur "dur". Le "ance" se dit "enss".', difficulty: 'medium' },
    { id: 'b1-p29', word: 'Interpretation', phonetic: '/ɪnˌtɜːrprɪˈteɪʃən/', tip: 'Accent sur "ta". 5 syllabes.', difficulty: 'hard' },
    { id: 'b1-p30', word: 'Consumption', phonetic: '/kənˈsʌmpʃən/', tip: 'Accent sur "sump". Le "tion" = "chən".', difficulty: 'hard' },
  ],
  B2: [
    { id: 'b2-p11', word: 'Methodology', phonetic: '/ˌmeθəˈdɒlədʒi/', tip: 'Accent sur "dol". Le "th" est dur. Le "gy" = "dji".', difficulty: 'hard' },
    { id: 'b2-p12', word: 'Infrastructure', phonetic: '/ˈɪnfrəstrʌktʃər/', tip: 'Accent sur "in". Le "struc" a un "u" court.', difficulty: 'hard' },
    { id: 'b2-p13', word: 'Consciousness', phonetic: '/ˈkɒnʃəsnəs/', tip: 'Le "sci" ne se prononce pas. Dites "kon-shəs-nəs".', difficulty: 'hard' },
    { id: 'b2-p14', word: 'Nominalization', phonetic: '/ˌnɒmɪnəlaɪˈzeɪʃən/', tip: 'Accent sur "za". 6 syllabes.', difficulty: 'hard' },
    { id: 'b2-p15', word: 'Epistemology', phonetic: '/ɪˌpɪstəˈmɒlədʒi/', tip: 'Accent sur "mol". Le "pi" est court.', difficulty: 'hard' },
    { id: 'b2-p16', word: 'Discrepancy', phonetic: '/dɪsˈkrepənsi/', tip: 'Accent sur "crep". Le "cy" se dit "si".', difficulty: 'medium' },
    { id: 'b2-p17', word: 'Remuneration', phonetic: '/rɪˌmjuːnəˈreɪʃən/', tip: 'Accent sur "ra". Le "mu" = "miou".', difficulty: 'hard' },
    { id: 'b2-p18', word: 'Substantiate', phonetic: '/səbˈstænʃieɪt/', tip: 'Accent sur "stan". Le "ti" = "chi".', difficulty: 'hard' },
    { id: 'b2-p19', word: 'Reconciliation', phonetic: '/ˌrekənˌsɪliˈeɪʃən/', tip: 'Accent sur "li". 6 syllabes.', difficulty: 'hard' },
    { id: 'b2-p20', word: 'Comprehend', phonetic: '/ˌkɒmprɪˈhend/', tip: 'Accent sur "hend". Le "pre" est léger.', difficulty: 'medium' },
    { id: 'b2-p21', word: 'Elaboration', phonetic: '/ɪˌlæbəˈreɪʃən/', tip: 'Accent sur "ra". Le "e" initial est schwa.', difficulty: 'medium' },
    { id: 'b2-p22', word: 'Ambiguity', phonetic: '/ˌæmbɪˈɡjuːəti/', tip: 'Accent sur "bi". Le "gu" = "giou".', difficulty: 'hard' },
    { id: 'b2-p23', word: 'Scrutiny', phonetic: '/ˈskruːtəni/', tip: 'Accent sur "scru". Le "ti" = "təni".', difficulty: 'medium' },
    { id: 'b2-p24', word: 'Prevalence', phonetic: '/ˈprevələns/', tip: 'Accent sur "pre". Le "va" est léger.', difficulty: 'medium' },
    { id: 'b2-p25', word: 'Delineate', phonetic: '/dɪˈlɪnieɪt/', tip: 'Accent sur "li". 4 syllabes.', difficulty: 'hard' },
    { id: 'b2-p26', word: 'Anomaly', phonetic: '/əˈnɒməli/', tip: 'Accent sur "no". Le "a" initial est schwa.', difficulty: 'medium' },
    { id: 'b2-p27', word: 'Corollary', phonetic: '/ˈkɒrəleri/', tip: 'Accent sur "co". 4 syllabes.', difficulty: 'medium' },
    { id: 'b2-p28', word: 'Constituency', phonetic: '/kənˈstɪtjuənsi/', tip: 'Accent sur "sti". 5 syllabes.', difficulty: 'hard' },
    { id: 'b2-p29', word: 'Precedent', phonetic: '/ˈpresɪdənt/', tip: 'Accent sur "pre". Le "ced" sonne "sid".', difficulty: 'medium' },
    { id: 'b2-p30', word: 'Compliance', phonetic: '/kəmˈplaɪəns/', tip: 'Accent sur "pli". Le "com" est schwa.', difficulty: 'medium' },
  ],
  C1: [
    { id: 'c1-p11', word: 'Pragmatics', phonetic: '/præɡˈmætɪks/', tip: 'Accent sur "ma". Le "pra" est court.', difficulty: 'hard' },
    { id: 'c1-p12', word: 'Hegemony', phonetic: '/hɪˈdʒeməni/', tip: 'Accent sur "ge". Le "he" = "hi".', difficulty: 'hard' },
    { id: 'c1-p13', word: 'Dichotomy', phonetic: '/daɪˈkɒtəmi/', tip: 'Accent sur "ko". Le "di" = "daï".', difficulty: 'hard' },
    { id: 'c1-p14', word: 'Jurisdiction', phonetic: '/ˌdʒʊərɪsˈdɪkʃən/', tip: 'Accent sur "dic". Le "ju" sonne "djou".', difficulty: 'hard' },
    { id: 'c1-p15', word: 'Connotation', phonetic: '/ˌkɒnəˈteɪʃən/', tip: 'Accent sur "na". Le "co" est court.', difficulty: 'medium' },
    { id: 'c1-p16', word: 'Euphemism', phonetic: '/ˈjuːfəmɪzəm/', tip: 'Accent sur "yu". Le "eu" = "you".', difficulty: 'hard' },
    { id: 'c1-p17', word: 'Discourse', phonetic: '/ˈdɪskɔːrs/', tip: 'Accent sur "dis". Le "course" = "kors".', difficulty: 'medium' },
    { id: 'c1-p18', word: 'Synergy', phonetic: '/ˈsɪnərdʒi/', tip: 'Accent sur "sin". Le "gy" = "dji".', difficulty: 'medium' },
    { id: 'c1-p19', word: 'Efficacy', phonetic: '/ˈefɪkəsi/', tip: 'Accent sur "ef". Le "cy" = "si".', difficulty: 'medium' },
    { id: 'c1-p20', word: 'Autonomy', phonetic: '/ɔːˈtɒnəmi/', tip: 'Accent sur "to". Le "au" = "o".', difficulty: 'medium' },
    { id: 'c1-p21', word: 'Plausible', phonetic: '/ˈplɔːzəbl/', tip: 'Accent sur "plaw". Le "au" sonne "o" ouvert.', difficulty: 'medium' },
    { id: 'c1-p22', word: 'Catalyst', phonetic: '/ˈkætəlɪst/', tip: 'Accent sur "ca". Le "a" est ouvert.', difficulty: 'medium' },
    { id: 'c1-p23', word: 'Unprecedented', phonetic: '/ʌnˈpresɪdentɪd/', tip: 'Accent sur "pre". 5 syllabes.', difficulty: 'hard' },
    { id: 'c1-p24', word: 'Stipulation', phonetic: '/ˌstɪpjʊˈleɪʃən/', tip: 'Accent sur "la". Le "u" après "p" est court.', difficulty: 'hard' },
    { id: 'c1-p25', word: 'Repercussion', phonetic: '/ˌriːpərˈkʌʃən/', tip: 'Accent sur "cus". Le "per" est léger.', difficulty: 'medium' },
    { id: 'c1-p26', word: 'Implication', phonetic: '/ˌɪmplɪˈkeɪʃən/', tip: 'Accent sur "ca". Le "im" est court.', difficulty: 'medium' },
    { id: 'c1-p27', word: 'Nuance', phonetic: '/ˈnjuːɑːns/', tip: 'Accent sur "nu". Son français emprunté.', difficulty: 'medium' },
    { id: 'c1-p28', word: 'Juxtaposition', phonetic: '/ˌdʒʌkstəpəˈzɪʃən/', tip: 'Accent sur "zi". Le "jus" = "djus".', difficulty: 'hard' },
    { id: 'c1-p29', word: 'Specification', phonetic: '/ˌspesɪfɪˈkeɪʃən/', tip: 'Accent sur "ca". 5 syllabes.', difficulty: 'hard' },
    { id: 'c1-p30', word: 'Editorial', phonetic: '/ˌedɪˈtɔːriəl/', tip: 'Accent sur "to". Le "ri" est léger.', difficulty: 'medium' },
  ],
  C2: [
    { id: 'c2-p11', word: 'Deconstruction', phonetic: '/ˌdiːkənˈstrʌkʃən/', tip: 'Accent sur "struc". 4 syllabes.', difficulty: 'hard' },
    { id: 'c2-p12', word: 'Hermeneutics', phonetic: '/ˌhɜːrməˈnjuːtɪks/', tip: 'Accent sur "meu". Le "tics" = "tiks".', difficulty: 'hard' },
    { id: 'c2-p13', word: 'Epistemology', phonetic: '/ɪˌpɪstəˈmɒlədʒi/', tip: 'Accent sur "mol". 6 syllabes.', difficulty: 'hard' },
    { id: 'c2-p14', word: 'Intertextuality', phonetic: '/ˌɪntərˌtekstʃuˈæləti/', tip: 'Accent sur "teks". 7 syllabes.', difficulty: 'hard' },
    { id: 'c2-p15', word: 'Semiotics', phonetic: '/ˌsiːmiˈɒtɪks/', tip: 'Accent sur "o". Le "tics" = "tiks".', difficulty: 'hard' },
    { id: 'c2-p16', word: 'Phenomenology', phonetic: '/fɪˌnɒmɪˈnɒlədʒi/', tip: 'Accent sur "no". 6 syllabes.', difficulty: 'hard' },
    { id: 'c2-p17', word: 'Existentialism', phonetic: '/ˌeɡzɪˈstenʃəlɪzəm/', tip: 'Accent sur "sten". Le "ism" = "izəm".', difficulty: 'hard' },
    { id: 'c2-p18', word: 'Nomenclature', phonetic: '/ˈnoʊmənˌkleɪtʃər/', tip: 'Accent sur "no". Le "cla" est secondaire.', difficulty: 'hard' },
    { id: 'c2-p19', word: 'Verisimilitude', phonetic: '/ˌverɪsɪˈmɪlɪtjuːd/', tip: 'Accent sur "mi". 6 syllabes.', difficulty: 'hard' },
    { id: 'c2-p20', word: 'Perspicacity', phonetic: '/ˌpɜːrspɪˈkæsəti/', tip: 'Accent sur "ca". 5 syllabes.', difficulty: 'hard' },
    { id: 'c2-p21', word: 'Provenance', phonetic: '/ˈprɒvənəns/', tip: 'Accent sur "pro". Le "və" est léger.', difficulty: 'medium' },
    { id: 'c2-p22', word: 'Exegesis', phonetic: '/ˌeksɪˈdʒiːsɪs/', tip: 'Accent sur "gi". 4 syllabes.', difficulty: 'hard' },
    { id: 'c2-p23', word: 'Teleology', phonetic: '/ˌteliˈɒlədʒi/', tip: 'Accent sur "o". 5 syllabes.', difficulty: 'hard' },
    { id: 'c2-p24', word: 'Liminality', phonetic: '/ˌlɪmɪˈnæləti/', tip: 'Accent sur "na". 5 syllabes.', difficulty: 'hard' },
    { id: 'c2-p25', word: 'Polyphony', phonetic: '/pəˈlɪfəni/', tip: 'Accent sur "li". 4 syllabes.', difficulty: 'hard' },
    { id: 'c2-p26', word: 'Mimesis', phonetic: '/mɪˈmiːsɪs/', tip: 'Accent sur "mi". 4 syllabes.', difficulty: 'hard' },
    { id: 'c2-p27', word: 'Aleatory', phonetic: '/ˈeɪliətɔːri/', tip: 'Accent sur "a". 4 syllabes.', difficulty: 'hard' },
    { id: 'c2-p28', word: 'Dialectic', phonetic: '/ˌdaɪəˈlektɪk/', tip: 'Accent sur "lec". Le "di" = "daï".', difficulty: 'hard' },
    { id: 'c2-p29', word: 'Ontological', phonetic: '/ˌɒntəˈlɒdʒɪkl/', tip: 'Accent sur "lo". 5 syllabes.', difficulty: 'hard' },
    { id: 'c2-p30', word: 'Sublime', phonetic: '/səˈblaɪm/', tip: 'Accent sur "blime". Le "su" est schwa.', difficulty: 'medium' },
  ],
}

// ─── Merge base + extra data ─────────────────────────────────────────────────

export const VOCAB_BY_LEVEL: Record<string, VocabCard[]> = {}
export const QUIZ_BY_LEVEL: Record<string, QuizQuestion[]> = {}
export const GRAMMAR_BY_LEVEL: Record<string, GrammarExercise[]> = {}
export const PRONUNCIATION_BY_LEVEL: Record<string, PronunciationWord[]> = {}

const ALL_LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']

for (const level of ALL_LEVELS) {
  VOCAB_BY_LEVEL[level] = [
    ...(BASE_VOCAB[level] || []),
    ...(EXTRA_VOCAB[level] || []),
  ]
  QUIZ_BY_LEVEL[level] = [
    ...(BASE_QUIZ[level] || []),
    ...(EXTRA_QUIZ[level] || []),
  ]
  GRAMMAR_BY_LEVEL[level] = [
    ...(BASE_GRAMMAR[level] || []),
    ...(EXTRA_GRAMMAR[level] || []),
  ]
  PRONUNCIATION_BY_LEVEL[level] = [
    ...(BASE_PRONUNCIATION[level] || []),
    ...(EXTRA_PRONUNCIATION[level] || []),
  ]
}
